import { PublicHeader } from "./Header";

export function LegalPage({ kind }: { kind: "privacy" | "terms" }) {
  const privacy = kind === "privacy";
  return (
    <main className="site-shell legal-page">
      <PublicHeader />
      <article className="legal-wrap">
        <header><span className="eyebrow">PLAIN ENGLISH · FAMILY VERSION 1.0</span><h1>{privacy ? "Family learning should stay in the family." : "One adult account. One shared learning space."}</h1><p>{privacy ? "A parent or legal guardian holds the account and stays beside the child. Children do not create accounts." : "These rules explain how a parent and child use Math together."}</p></header>
        {privacy ? <PrivacyCopy /> : <TermsCopy />}
        <footer><p>Last updated: August 30, 2026</p><a className="primary-button" href="/">Return home <span>→</span></a></footer>
      </article>
    </main>
  );
}

function PrivacyCopy() {
  return <div className="legal-sections">
    <section><span>01</span><div><h2>Who holds the account</h2><p>Only an adult parent or legal guardian may sign in. The child does not receive a login, account, email connection, or public identity. The adult agrees to stay present while the child uses a learning activity.</p></div></section>
    <section><span>02</span><div><h2>Parent sign-in and consent records</h2><p>Google sends a signed credential so Math can confirm that the same adult account has returned. Math transforms Google’s stable account subject with a private server HMAC key. It saves that protected key—not the parent’s Google name, email address, profile photo, or raw Google credential. During sign-in the parent must accept the current family agreement. Math saves the agreement version, acceptance time, account creation time, last successful sign-in time, timezone, and scheduled deletion dates.</p></div></section>
    <section><span>03</span><div><h2>What is stored in Cloudflare D1</h2><p>Signed-in information is stored in this site’s managed Cloudflare D1 database, currently running in Cloudflare’s APAC region with read replication disabled. The shared family record can contain a random family codename and symbol; theme and frame choices; lesson and challenge progress; answer correctness; attempt and hint counts; review timing; stars; XP; badges; streaks and private rewards. D1 also stores random request de-duplication keys used to protect saved changes. Raw written answers and interactive graph equations are checked but not retained. Because a child may do the activity beside the parent, this record can reflect the child’s learning and is visible to the parent account holder.</p></div></section>
    <section><span>04</span><div><h2>Sessions, browser data, and protection</h2><p>The browser receives a Secure, HttpOnly, SameSite session cookie. D1 stores only a hash of that session token and its expiration time. A no-sign-in preview stores temporary progress in this browser rather than D1. Information is sent over HTTPS. Math does not use session replay, cross-site advertising profiles, or sell family information.</p></div></section>
    <section><span>05</span><div><h2>Four-month and six-month deletion</h2><p>Every successful parent sign-in restarts two periods from that sign-in date. If there is no new successful sign-in, all saved learning, appearance, reward, and feedback data is scheduled for deletion after four calendar months. The remaining parent account key, consent record, and deletion record are scheduled for deletion after six calendar months. A daily UTC cleanup normally completes deletion within 24 hours after each deadline. Simply opening a page does not restart either period. Signing in between months four and six opens the existing parent account with a new blank family record.</p></div></section>
    <section><span>06</span><div><h2>Delete by category or delete everything</h2><p>Family space lets the parent delete learning records and rewards; family appearance settings; feedback discussions; or all saved family data while retaining the parent login. Complete account deletion requires fresh Google verification and removes the protected account key, consent record, active sessions, and all linked D1 information. These actions cannot be undone in the active service.</p></div></section>
    <section><span>07</span><div><h2>Parent feedback discussions</h2><p>Only signed-in adult account holders can submit or read the feedback area. D1 stores the topic category, message, review status, request-key hash, feedback notice version, publication-consent time, creation and update times, and any site-owner reply. A new topic is visible only to its author and the site owner until approved; approved topics and replies can be read by other signed-in parents. Internal account IDs are not shown. Do not include a child’s identity, school, contact details, links, or other identifying information.</p></div></section>
    <section><span>08</span><div><h2>What Math does not ask for</h2><p>Math does not ask for a child’s name, email, exact birth date, school, class, photo, voice, address, or social account. Math does not load AdSense or other advertising code. There are no child logins, separate child profiles, public learning histories, public rankings, direct messages, or public child submissions.</p></div></section>
    <section><span>09</span><div><h2>Cloudflare operational records and backups</h2><p>Cloudflare may separately process network, security, and diagnostic request records to operate and protect the service. Those provider records are not used for learning profiles and follow Cloudflare’s own retention controls. D1 backup history can temporarily retain a recoverable version after active deletion—up to Cloudflare’s available Time Travel window for the service plan—before it expires. It is used only for infrastructure recovery, not to restore a family record after a parent asks to delete it.</p></div></section>
    <section><span>10</span><div><h2>Important consent boundary</h2><p>The adult confirmation records acceptance of this family-use agreement; it is not represented as third-party identity proof or as a substitute for every jurisdiction’s verifiable-parental-consent requirements. Separate child profiles, school use, advertising, and child-to-child interaction remain disabled while those controls are not available.</p></div></section>
  </div>;
}

function TermsCopy() {
  return <div className="legal-sections">
    <section><span>01</span><div><h2>Who may hold an account</h2><p>The account holder must be at least 18 years old and be the child’s parent or legal guardian. The adult remains present and responsible for the shared session. A child may participate beside the adult but may not create or control an account.</p></div></section>
    <section><span>02</span><div><h2>Family learning—not school administration</h2><p>Math is an independent Grades 7–12 family learning aid, not a school grading, attendance, credential, class-management, or student-record service. Do not upload school rosters or use the family account to monitor students outside your household.</p></div></section>
    <section><span>03</span><div><h2>AI-assisted creation and accuracy</h2><p>Math is built through collaboration between a human creator and AI tools. AI has helped produce code, explanations, questions, stories, and visual directions. Human review and automated tests reduce mistakes but cannot guarantee that every answer, image, or statement is correct. Check important material against a trusted teacher, textbook, or another reliable source, and please report anything that needs correction.</p></div></section>
    <section><span>04</span><div><h2>Open reuse of original material</h2><p>You may freely copy, share, and adapt Math’s original learning text and original image assets for learning, teaching, or creative work without asking first. Attribution or a link is appreciated but not required. This permission does not cover third-party advertisements, trademarks, linked services, fonts, software, or other material governed by separate terms. Anyone reusing material is responsible for checking its accuracy and deciding whether it fits their purpose.</p></div></section>
    <section><span>05</span><div><h2>Safe family use</h2><p>Do not enter a child’s name, contact information, school, exact birth date, photo, voice, or other identifying details. Do not automate answers or interfere with the service. Private rewards have no cash value and cannot be sold or transferred.</p></div></section>
    <section><span>06</span><div><h2>Your parent account</h2><p>Your Google sign-in is used only to return you to the same private family learning record. You are responsible for access to that Google account. Math cannot recover progress without it.</p></div></section>
    <section><span>07</span><div><h2>Availability and changes</h2><p>The service may change lessons, correct errors, adjust private rewards, or temporarily pause features for safety and maintenance. Family progress will be preserved where reasonably possible.</p></div></section>
    <section><span>08</span><div><h2>Feedback with the site owner</h2><p>A signed-in parent may send feedback for review. The site owner may approve, hide, reply to, or delete a topic. Approved topics are visible only to other signed-in parents. Parents may not message one another, post links or attachments, or include child or contact information. The author can delete a topic, and Family space also provides feedback-category deletion.</p></div></section>
    <section><span>09</span><div><h2>Ending use and inactivity</h2><p>The adult account holder may delete categories or the complete family account at any time. Without another successful sign-in, saved family data is removed after four calendar months and the remaining account after six calendar months, normally within 24 hours of the deadline. Access may be limited when these terms are abused or when necessary to protect children, families, and the service.</p></div></section>
    <section><span>10</span><div><h2>Features intentionally not offered</h2><p>This family version does not offer child accounts, public rankings, public child comments, parent-to-parent replies, direct messages, third-party advertising, separate child profiles, school rosters, or teacher surveillance.</p></div></section>
  </div>;
}
