import { buildPracticeQuestion, type GraphChoicePlot, type QuestionInteractionConfig } from "./question-interactions.ts";
import type { CognitiveDemand, DepthQuestion, LessonDepthPack, QuestionEvidence } from "./curriculum-depth-types.ts";

type Response = { choices?: string[]; interactionConfig?: QuestionInteractionConfig };
const options = (...choices: string[]): Response => ({ choices });
const table = (columns: string[], rows: Array<[string, ...string[]]>): Response => ({ choices: rows.map(([value]) => value), interactionConfig: { kind: "table-choice", columns, rows: rows.map(([value, ...cells]) => ({ value, cells })) } });
const grid = (): Response => ({ interactionConfig: { kind: "coordinate-grid", xMin: -6, xMax: 6, yMin: -6, yMax: 6, step: 1 } });
const graph = (plots: GraphChoicePlot[], xMin: number, xMax: number, yMin: number, yMax: number): Response => ({ choices: plots.map((plot) => plot.value), interactionConfig: { kind: "graph-choice", plots, xMin, xMax, yMin, yMax } });
const evidence = (objectiveId: string, demand: CognitiveDemand, representation: QuestionEvidence["representation"], misconception: string, difficulty: 1 | 2 | 3 = 2): QuestionEvidence => ({ objectiveId, demand, representation, difficulty, misconception, variantFamily: `${objectiveId}-pair-v3` });
const q = (n: number, prompt: string, answer: string, hint: string, explanation: string, detail: QuestionEvidence, response: Response = {}): DepthQuestion => ({ ...buildPracticeQuestion({ id: `d3-q${n}`, prompt, answer, hint, ...response, interaction: response.interactionConfig?.kind }), evidence: detail, explanation });
const pack = (value: LessonDepthPack): LessonDepthPack => ({ ...value, objectives: value.objectives.map((objective) => ({ ...objective, id: `${value.lessonSlug}:d3:${objective.id}` })), questions: value.questions.map((question) => ({ ...question, evidence: { ...question.evidence, objectiveId: `${value.lessonSlug}:d3:${question.evidence.objectiveId}`, variantFamily: `${value.lessonSlug}:d3:${question.evidence.variantFamily}` } })) });

export const round3MiddleDepthPacks: LessonDepthPack[] = [
  pack({
    lessonSlug: "g7-scale-drawings",
    objectives: [
      { id: "scale-rectangular-area", description: "Convert both scaled side lengths to real units before calculating a rectangular area.", requiredDemands: ["procedure"] },
      { id: "audit-plan-dimensions", description: "Read proposed drawing dimensions and check both against a specified real rectangle and scale.", requiredDemands: ["representation"] },
      { id: "revise-resized-map-scale", description: "Determine the real distance per drawing unit after a map is enlarged or reduced uniformly.", requiredDemands: ["reasoning", "application"] },
    ],
    legacyObjectives: {},
    example: "A rectangular plan is 7 cm by 2 cm at a scale of 1 cm to 3 m. The real rectangle has area 126 m².",
    exampleSteps: ["Convert the first dimension: 7 × 3 = 21 m.", "Convert the second dimension: 2 × 3 = 6 m.", "Multiply the real lengths: 21 × 6 = 126 m².", "Both dimensions scale, so the drawing area 14 cm² corresponds to 14 × 3² = 126 m²."],
    questions: [
      q(1, "A rectangular room is 6 cm by 4 cm on a plan with scale 1:200. What is the actual floor area in square meters?", "96", "The scale ratio uses matching units: 200 cm is 2 m for each centimeter on the plan.", "The actual sides are 6 × 2 = 12 m and 4 × 2 = 8 m. Their product is 96 m²; multiplying the drawing area by only one length factor would miss the scaling of the other side.", evidence("scale-rectangular-area", "procedure", "verbal", "Applying the length scale once to an area or leaving square centimeters unconverted.")),
      q(2, "A garden plan measures 5 cm by 3 cm and uses scale 1:300. Find the actual rectangular garden area in square meters.", "135", "First express the real distance represented by 1 cm in meters.", "Each plan centimeter represents 300 cm = 3 m. Thus the garden is 15 m by 9 m and has area 15 × 9 = 135 m².", evidence("scale-rectangular-area", "procedure", "verbal", "Converting one dimension correctly but keeping the other in drawing units.")),
      q(3, "A real room is 12 m long and 8 m wide. Which proposed plan uses the required scale of 1 cm to 2 m in both directions?", "Plan A", "The correct drawing dimensions must be 12/2 and 8/2, not merely have the right ratio to each other.", "The required plan is 6 cm by 4 cm, shown in A. D preserves the room's shape but uses the wrong scale; B and C also fail at least one required dimension.", evidence("audit-plan-dimensions", "representation", "table", "Accepting a similar rectangle even when its scale differs from the specified one."), table(["Plan", "Drawn length (cm)", "Drawn width (cm)"], [["Plan A", "A", "6", "4"], ["Plan B", "B", "6", "8"], ["Plan C", "C", "12", "8"], ["Plan D", "D", "3", "2"]])),
      q(4, "A field is 15 m long and 10 m wide. Which drawing in the table uses a scale of 1 cm to 2.5 m for both dimensions?", "Plan B", "Divide each real dimension by 2.5 meters per drawing centimeter.", "The drawn length should be 15/2.5 = 6 cm and the width 10/2.5 = 4 cm. Only B meets both measurements, including the required scale.", evidence("audit-plan-dimensions", "representation", "table", "Checking only the longer side when a drawing must use one scale in both directions."), table(["Plan", "Drawn length (cm)", "Drawn width (cm)"], [["Plan A", "A", "6", "5"], ["Plan B", "B", "6", "4"], ["Plan C", "C", "3", "2"], ["Plan D", "D", "15", "10"]])),
      q(5, "A map originally represents 4 m with each centimeter. A copier enlarges every drawn length to 150% of its original length. What is the new scale?", "Each new centimeter represents 8/3 meters.", "The same real 4 m now occupies 1.5 cm, so divide the real distance by the new drawn distance.", "After enlargement, 1.5 cm represents 4 m. Therefore 1 cm represents 4/1.5 = 8/3 m. Enlarging the drawing reduces the real distance represented by one centimeter.", evidence("revise-resized-map-scale", "reasoning", "verbal", "Multiplying the real distance per centimeter by the enlargement factor instead of dividing."), options("Each new centimeter represents 6 meters.", "Each new centimeter represents 4 meters.", "Each new centimeter represents 8/3 meters.", "Each new centimeter represents 3/8 meter.")),
      q(6, "A route map uses 1 cm to 3 km. Every drawn length is reduced to 60% of its original length. What does 1 cm represent on the reduced map?", "5 kilometers.", "A former 1 cm segment becomes 0.6 cm but still represents the same 3 km.", "On the reduced map, 0.6 cm represents 3 km. The new scale is 3/0.6 = 5 km per centimeter, consistent with more real distance fitting into each drawn centimeter.", evidence("revise-resized-map-scale", "application", "verbal", "Shrinking the represented real distance when only the drawing is resized."), options("1.8 kilometers.", "5 kilometers.", "3 kilometers.", "0.2 kilometer.")),
    ],
    remainingGaps: ["Constructing a scale drawing interactively and checking angles or irregular shapes.", "Area comparisons for composite scale drawings and interpreting inaccurate or distorted maps."],
  }),
  pack({
    lessonSlug: "g7-rational-word-problems",
    objectives: [
      { id: "recover-signed-start", description: "Recover a starting quantity by reversing a sequence of positive and negative decimal changes.", requiredDemands: ["procedure"] },
      { id: "trace-signed-ledger", description: "Read a sequence of signed changes and locate the first running value crossing a stated threshold.", requiredDemands: ["representation"] },
      { id: "distinguish-net-and-travel", description: "Distinguish signed displacement from total distance across a two-stage route with a reversal.", requiredDemands: ["reasoning", "application"] },
    ],
    legacyObjectives: {},
    example: "After a $6.50 withdrawal and a $2.25 deposit, a balance is −$1. The starting balance was $3.25.",
    exampleSteps: ["Let the starting balance be B; the withdrawal changes it by −6.50 and the deposit by +2.25.", "Write B − 6.50 + 2.25 = −1, or B − 4.25 = −1.", "Add 4.25 to get B = 3.25 dollars.", "Check forward: 3.25 − 6.50 + 2.25 = −1."],
    questions: [
      q(1, "A diver descends 2.25 m, then ascends 1.5 m, ending at elevation −7.5 m relative to the surface. What was the starting elevation in meters?", "-6.75", "Reverse the ascent and then the descent, or subtract the net change from the final elevation.", "The net change is −2.25 + 1.5 = −0.75 m. If the start is s, then s − 0.75 = −7.5, so s = −6.75 m.", evidence("recover-signed-start", "procedure", "verbal", "Applying the same changes again to the final value instead of undoing them.")),
      q(2, "A bank balance is −$3.25 after a $12.50 withdrawal followed by a $7.75 deposit. What was the balance before these two transactions, in dollars?", "1.5|1.50", "The two transactions have a combined change of −4.75 dollars.", "The starting balance B satisfies B − 12.50 + 7.75 = −3.25. Since the net change is −4.75, B = −3.25 + 4.75 = 1.50 dollars.", evidence("recover-signed-start", "procedure", "verbal", "Treating a deposit as a negative change because the final balance is negative.")),
      q(3, "A balance starts at $5.50. Apply the listed transactions in order. After which transaction does the running balance first become negative?", "Transaction B", "Keep a running total from the stated starting balance instead of comparing transaction sizes alone.", "After A the balance is 5.50 − 2.25 = 3.25. After B it is 3.25 − 4 = −0.75, the first negative value. Later transactions do not change when that first crossing occurred.", evidence("trace-signed-ledger", "representation", "table", "Identifying the largest withdrawal rather than tracing the running balance."), table(["Transaction order", "Change ($)"], [["Transaction A", "A: first", "−2.25"], ["Transaction B", "B: second", "−4.00"], ["Transaction C", "C: third", "+3.00"], ["Transaction D", "D: fourth", "−1.75"]])),
      q(4, "A temperature starts at 3°C. The table lists consecutive changes. After which change does the temperature first fall below −2°C?", "Change C", "Add each signed change to the previous temperature, checking the threshold after every row.", "The temperatures are 1.75°C after A, 0.25°C after B, −2.25°C after C, and −1.25°C after D. C is the first below −2°C.", evidence("trace-signed-ledger", "representation", "table", "Comparing each change with the threshold instead of comparing the accumulated temperature."), table(["Change order", "Change (°C)"], [["Change A", "A: first", "−1.25"], ["Change B", "B: second", "−1.50"], ["Change C", "C: third", "−2.50"], ["Change D", "D: fourth", "+1.00"]])),
      q(5, "A lift moves from elevation −2.5 m to 4 m, then down to 1 m. Which statement gives its signed net change and total distance traveled?", "Net change +3.5 m; total distance 9.5 m.", "Use final minus initial for net change; add the positive length of each trip for distance.", "The net change is 1 − (−2.5) = +3.5 m. The lift travels 6.5 m upward and 3 m downward, so the total distance is 6.5 + 3 = 9.5 m.", evidence("distinguish-net-and-travel", "reasoning", "verbal", "Subtracting reversed travel when computing total distance or making net change always positive."), options("Net change +3.5 m; total distance 3.5 m.", "Net change +9.5 m; total distance 9.5 m.", "Net change +3.5 m; total distance 9.5 m.", "Net change −3.5 m; total distance 6.5 m.")),
      q(6, "A submarine moves vertically from −3 m to −8.5 m, then to −1 m. Which statement correctly compares its net elevation change and distance traveled?", "Net change +2 m; total distance 13 m.", "The first leg goes down 5.5 m and the second goes up 7.5 m.", "Final minus initial is −1 − (−3) = +2 m. The two traveled lengths are 5.5 m and 7.5 m, totaling 13 m despite the small net change.", evidence("distinguish-net-and-travel", "application", "verbal", "Using the final depth as the total distance or canceling opposite trips in a distance total."), options("Net change −1 m; total distance 1 m.", "Net change +2 m; total distance 13 m.", "Net change +13 m; total distance 2 m.", "Net change −2 m; total distance 13 m.")),
    ],
    remainingGaps: ["Longer rational-number models combining fractional rates, repeated changes, and unknown durations.", "Drawing a complete signed route and distinguishing distance, speed, and signed velocity."],
  }),
  pack({
    lessonSlug: "g7-inequalities-g7",
    objectives: [
      { id: "interpret-integer-bound", description: "Solve a two-step contextual bound and choose the feasible whole-number minimum or maximum.", requiredDemands: ["procedure"] },
      { id: "read-dual-bound-data", description: "Read option measurements and apply both inclusive and strict constraints to select a feasible option.", requiredDemands: ["representation"] },
      { id: "justify-negative-division", description: "Explain the sign reversal needed when solving a two-step inequality with a negative coefficient.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "A $24 budget covers a $7 fee and $2.50 per item. The greatest whole number of items affordable is 6.",
    exampleSteps: ["Write 7 + 2.5n ≤ 24, where n is a nonnegative integer.", "Subtract 7 and divide by 2.5: n ≤ 17/2.5 = 6.8.", "The greatest whole number at or below 6.8 is 6.", "Check: 6 items cost $22, while 7 cost $24.50 and exceed the budget."],
    questions: [
      q(1, "A player has 18 points and earns 4.5 points per completed round. What is the minimum whole number of additional rounds needed to reach at least 40 points?", "5", "Solve 18 + 4.5r ≥ 40 and choose a whole number that reaches the goal.", "The bound is r ≥ 22/4.5, about 4.89. Four rounds give only 36 points; five give 40.5, so the minimum is 5.", evidence("interpret-integer-bound", "procedure", "verbal", "Rounding a minimum requirement down and leaving the target unmet.")),
      q(2, "A $35 budget must cover an $8 booking fee and $3.50 per ticket. What is the maximum whole number of tickets that can be purchased?", "7", "After removing the fixed fee, divide the remaining budget by the ticket price.", "The inequality 8 + 3.5n ≤ 35 gives n ≤ 27/3.5, about 7.71. Seven tickets cost $32.50; eight cost $36, so only 7 are affordable.", evidence("interpret-integer-bound", "procedure", "verbal", "Rounding a maximum affordable count upward beyond the budget.")),
      q(3, "Choose a tour lasting at least 2 hours and costing no more than $30. Which table row meets both requirements?", "Tour B", "Apply the time lower bound and price upper bound together.", "B lasts 2.5 hours and costs $28, so it satisfies both bounds. A and D are too short, while C exceeds the price limit.", evidence("read-dual-bound-data", "representation", "table", "Satisfying one requirement while ignoring the other."), table(["Tour", "Duration (hours)", "Price ($)"], [["Tour A", "A", "1", "20"], ["Tour B", "B", "2.5", "28"], ["Tour C", "C", "3", "32"], ["Tour D", "D", "1.5", "24"]])),
      q(4, "A battery must have capacity at least 2,500 mAh and cost strictly less than $12. Which option qualifies?", "Battery C", "Equality is allowed at the capacity threshold but not at the price threshold.", "C has capacity 3,000 mAh and costs $11.50. B meets the capacity threshold but costs exactly $12, which the strict price bound excludes; A is too small and D is too expensive.", evidence("read-dual-bound-data", "representation", "table", "Treating a strict price bound as inclusive because another constraint is inclusive."), table(["Battery", "Capacity (mAh)", "Price ($)"], [["Battery A", "A", "2400", "9"], ["Battery B", "B", "2500", "12"], ["Battery C", "C", "3000", "11.5"], ["Battery D", "D", "2600", "12.5"]])),
      q(5, "Which solution and explanation are correct for 5 − 2x < 11?", "x > −3; dividing −2x < 6 by −2 reverses the inequality.", "Subtracting 5 preserves the direction; dividing by a negative number is the step that reverses it.", "Subtract 5 to obtain −2x < 6. Dividing by −2 gives x > −3, reversing the inequality. For example, x = 0 works, while x = −4 does not.", evidence("justify-negative-division", "reasoning", "symbolic", "Reversing when subtracting instead of when dividing by a negative number."), options("x < −3; dividing by a negative keeps the direction.", "x > −3; dividing −2x < 6 by −2 reverses the inequality.", "x > 3; ignore the negative coefficient.", "x ≥ −3; the division adds equality.")),
      q(6, "Which solution and explanation are correct for 4 − 3x ≥ 19?", "x ≤ −5; dividing −3x ≥ 15 by −3 reverses the inequality.", "First isolate the term −3x, then preserve equality while reversing the comparison direction.", "Subtract 4 to get −3x ≥ 15. Divide by −3 to obtain x ≤ −5. Equality remains allowed because the original comparison included it.", evidence("justify-negative-division", "reasoning", "symbolic", "Losing equality or retaining the original direction after division by a negative coefficient."), options("x ≥ −5; the comparison direction never changes.", "x < −5; equality disappears after division.", "x ≤ 5; divide by the positive magnitude only.", "x ≤ −5; dividing −3x ≥ 15 by −3 reverses the inequality.")),
    ],
    remainingGaps: ["Constructing complete shaded solution rays with open and closed endpoints.", "Writing and comparing multi-constraint models from longer contexts with rational coefficients."],
  }),
  pack({
    lessonSlug: "g7-informal-inference",
    objectives: [
      { id: "compare-projected-counts", description: "Estimate a difference between population counts using proportions from random samples of different sizes.", requiredDemands: ["procedure"] },
      { id: "read-repeated-sample-variation", description: "Compare the observed ranges of estimates across repeated random samples without treating those ranges as guarantees.", requiredDemands: ["representation"] },
      { id: "qualify-threshold-claim", description: "Check whether a stated plausible sampling-variation range supports a claim that a population proportion is above or below one half.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "Random samples find support from 21 of 30 people in town A and 18 of 30 in town B. With 1,000 residents in each town, the estimated difference in supporters is 100.",
    exampleSteps: ["Estimate town A's support proportion as 21/30 = 0.70.", "Estimate town B's support proportion as 18/30 = 0.60.", "Apply these proportions to 1,000 residents: about 700 and 600 supporters.", "Subtract to estimate 100 more supporters in A, while recognizing that random samples do not give exact population counts."],
    questions: [
      q(1, "Random samples find 25 supporters among 50 residents in town A and 30 among 75 in town B. Each town has 2,000 residents. Using these sample proportions, estimate how many more supporters A has than B.", "200", "Compare the proportions before multiplying by the equal population sizes.", "A's estimate is 25/50 = 0.50 and B's is 30/75 = 0.40. The projected counts are 1,000 and 800, giving an estimated difference of 200, not an exact census result.", evidence("compare-projected-counts", "procedure", "verbal", "Comparing favorable sample counts directly when the sample sizes differ.")),
      q(2, "Two campuses each have 1,500 students. In independent random samples, 18 of 40 students at A and 28 of 80 at B favor a schedule. Estimate the number of additional supporters at A using these proportions.", "150", "The larger favorable sample count need not represent a larger favorable proportion.", "The proportions are 18/40 = 0.45 and 28/80 = 0.35. Their estimated difference is 0.10, corresponding to 0.10 × 1,500 = 150 students.", evidence("compare-projected-counts", "procedure", "verbal", "Scaling the difference in sample counts instead of the difference in sample proportions.")),
      q(3, "Each row shows support percentages from five repeated random samples of the same population. Which design had the smallest observed range of estimates in these runs?", "Design C", "Subtract the smallest percentage in each row from the largest; use all five observations.", "The observed ranges are A: 65 − 35 = 30, B: 54 − 44 = 10, C: 52 − 48 = 4, and D: 55 − 40 = 15 percentage points. C is narrowest in these runs; five runs do not prove a guaranteed bound for future samples.", evidence("read-repeated-sample-variation", "representation", "table", "Comparing only one estimate with 50% rather than the variation across repeated samples."), table(["Design", "Sample size", "Five estimates (%)"], [["Design A", "A", "20", "45, 65, 35, 55, 60"], ["Design B", "B", "100", "48, 54, 44, 52, 49"], ["Design C", "C", "400", "49, 51, 50, 48, 52"], ["Design D", "D", "50", "40, 55, 45, 50, 53"]])),
      q(4, "A simulation repeats each random-sampling design five times for one population. Which row shows the most stable estimates as measured by the smallest observed range?", "Design D", "Stability here has a specific measure: maximum estimate minus minimum estimate.", "The ranges are A: 6, B: 30, C: 15, and D: 2 percentage points. D has the smallest observed spread. This describes the listed simulation runs rather than guaranteeing every future estimate.", evidence("read-repeated-sample-variation", "representation", "table", "Equating a large sample with a guarantee instead of checking the observed variation measure."), table(["Design", "Sample size", "Five estimates (%)"], [["Design A", "A", "100", "47, 53, 50, 49, 51"], ["Design B", "B", "20", "35, 60, 50, 65, 40"], ["Design C", "C", "50", "40, 55, 45, 50, 53"], ["Design D", "D", "500", "49, 50, 51, 50, 49"]])),
      q(5, "A random sample estimates 52% support. A repeated-sampling model suggests using 52% ± 6 percentage points as a plausible range, not a guarantee. Does this range place the population support entirely above 50%?", "No; the plausible range is 46% to 58%, which crosses 50%.", "Subtract and add 6 percentage points, then compare the entire range with the halfway threshold.", "The stated range is 46% through 58%. It includes values below and above 50%, so it does not establish that support is above one half; the point estimate alone is not enough.", evidence("qualify-threshold-claim", "reasoning", "verbal", "Using the point estimate alone to claim a majority despite a plausible range crossing one half."), options("Yes; 52% is above 50%, so uncertainty cannot change the claim.", "No; the plausible range is 46% to 58%, which crosses 50%.", "Yes; every plausible value is at least 52%.", "No; the population must have exactly 46% support.")),
      q(6, "A random sample estimates 47% support. Use 47% ± 5 percentage points as a plausible range from a repeated-sampling model, not as a guarantee. Is this range entirely below 50%?", "No; the plausible range is 42% to 52%, which includes values above 50%.", "Compute the upper as well as the lower end before claiming less than half support.", "The range extends from 47 − 5 = 42% to 47 + 5 = 52%. Because its upper part exceeds 50%, it does not place population support entirely below one half.", evidence("qualify-threshold-claim", "reasoning", "verbal", "Claiming a minority from a point estimate without checking the upper end of the variation range."), options("Yes; any sample result below 50% proves a population minority.", "Yes; the entire plausible range ends at 47%.", "No; the plausible range is 42% to 52%, which includes values above 50%.", "No; the population must have exactly 52% support.")),
    ],
    remainingGaps: ["Creating repeated-sampling simulations and interpreting their full distributions.", "Formal interval procedures, confidence levels, and unequal population sizes or sampling weights."],
  }),
  pack({
    lessonSlug: "scientific-operations",
    objectives: [
      { id: "align-scientific-powers", description: "Add or subtract quantities with different powers of ten and express the result in normalized scientific notation.", requiredDemands: ["procedure"] },
      { id: "compare-scientific-totals", description: "Read scientific-notation measurements and counts to compare total quantities across rows.", requiredDemands: ["representation"] },
      { id: "calculate-scientific-duration", description: "Divide a scientific-notation quantity by a compatible rate and interpret the resulting duration and units.", requiredDemands: ["reasoning", "application"] },
    ],
    legacyObjectives: {},
    example: "The sum 3.6 × 10⁴ + 8 × 10³ is 4.4 × 10⁴.",
    exampleSteps: ["Rewrite 8 × 10³ as 0.8 × 10⁴ so both quantities use the same power of ten.", "Add the matching coefficients: 3.6 + 0.8 = 4.4.", "Keep the common power: the sum is 4.4 × 10⁴.", "Check in standard form: 36,000 + 8,000 = 44,000."],
    questions: [
      q(1, "Calculate 4.2 × 10⁵ + 6 × 10⁴ and choose the result in scientific notation.", "4.8 × 10^5", "Rewrite 6 × 10⁴ as 0.6 × 10⁵ before adding coefficients.", "The powers must match for addition: (4.2 + 0.6) × 10⁵ = 4.8 × 10⁵. Directly adding 4.2 and 6 without adjusting the exponents would overstate the second quantity.", evidence("align-scientific-powers", "procedure", "symbolic", "Adding scientific-notation coefficients while their powers of ten differ."), options("4.8 × 10^5", "4.8 × 10^4", "1.02 × 10^6", "4.26 × 10^5")),
      q(2, "Calculate 7.1 × 10⁻³ − 8 × 10⁻⁴ and choose the result in scientific notation.", "6.3 × 10^-3", "Express the second quantity as a multiple of 10⁻³.", "Since 8 × 10⁻⁴ = 0.8 × 10⁻³, subtract coefficients to get (7.1 − 0.8) × 10⁻³ = 6.3 × 10⁻³. In decimal form, 0.0071 − 0.0008 = 0.0063.", evidence("align-scientific-powers", "procedure", "symbolic", "Treating a more negative exponent as a larger place value during subtraction."), options("6.3 × 10^-4", "7.02 × 10^-3", "6.3 × 10^-3", "7.9 × 10^-3")),
      q(3, "Each packet in a batch has the size shown. Which batch contains the greatest total number of bytes?", "Batch B", "Multiply the bytes per packet by the packet count for each row before comparing.", "The totals are A: 6 × 10⁵, B: 7.2 × 10⁵, C: 5 × 10⁵, and D: 6 × 10⁵ bytes. B has the greatest total despite having the smallest individual packet size.", evidence("compare-scientific-totals", "representation", "table", "Ranking only individual scientific-notation measurements without multiplying by their counts."), table(["Batch", "Bytes per packet", "Packet count"], [["Batch A", "A", "2 × 10^5", "3"], ["Batch B", "B", "9 × 10^4", "8"], ["Batch C", "C", "5 × 10^5", "1"], ["Batch D", "D", "1.2 × 10^5", "5"]])),
      q(4, "Each trial uses drops of the per-drop volume shown in its row. Which trial uses the greatest total volume of liquid?", "Trial D", "Compute drop volume times number of drops, keeping liters as the common unit.", "The total volumes are A: 1.5 × 10⁻³ L, B: 1.6 × 10⁻³ L, C: 1.2 × 10⁻³ L, and D: 2 × 10⁻³ L. D is greatest.", evidence("compare-scientific-totals", "representation", "table", "Assuming the most drops or the largest drop alone determines the total volume."), table(["Trial", "Volume per drop (L)", "Drop count"], [["Trial A", "A", "3 × 10^-4", "5"], ["Trial B", "B", "8 × 10^-5", "20"], ["Trial C", "C", "6 × 10^-4", "2"], ["Trial D", "D", "2.5 × 10^-4", "8"]])),
      q(5, "A file contains 6 × 10⁸ bytes. A connection transfers a constant 2 × 10⁶ bytes per second with no overhead. Which transfer time and unit reasoning are correct?", "300 seconds; dividing bytes by bytes per second leaves seconds.", "Divide the file size by the transfer rate, and subtract the exponents in the quotient.", "The duration is (6/2) × 10^(8 − 6) = 3 × 10² = 300. The units are bytes ÷ (bytes/second) = seconds, so this is a time rather than a rate.", evidence("calculate-scientific-duration", "reasoning", "verbal", "Multiplying by a rate or retaining the numerator unit after division."), options("300 bytes; the original file unit remains.", "3 seconds; the powers of ten cancel completely.", "300 seconds; dividing bytes by bytes per second leaves seconds.", "12 × 10^14 seconds; multiply size by rate.")),
      q(6, "A probe travels 8.4 × 10⁸ m at a constant 2.1 × 10⁶ m/s. Ignoring acceleration, how long is the trip?", "400 seconds.", "Distance divided by speed gives time; handle coefficients and powers separately.", "Time is (8.4/2.1) × 10^(8 − 6) = 4 × 10² = 400 seconds. Meters cancel from m ÷ (m/s), leaving seconds.", evidence("calculate-scientific-duration", "application", "verbal", "Subtracting coefficients along with exponents or interpreting a quotient as a distance."), options("4 seconds.", "400 seconds.", "40,000 seconds.", "400 meters.")),
    ],
    remainingGaps: ["Mixed-operation expressions with several normalization steps and significant-figure constraints.", "Scientific notation in measured data with uncertainty and cross-unit rate conversions."],
  }),
  pack({
    lessonSlug: "systems-algebra",
    objectives: [
      { id: "solve-scaled-elimination", description: "Solve a two-variable system by scaling equations before eliminating one variable.", requiredDemands: ["procedure"] },
      { id: "plot-algebraic-system-solution", description: "Solve a two-equation system and locate its common ordered-pair solution on a coordinate grid.", requiredDemands: ["representation"] },
      { id: "classify-expanded-systems", description: "Expand and compare equations to distinguish an inconsistent system from equivalent equations.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "For 2x + 5y = 19 and 3x − 2y = 0, elimination gives x = 2 and y = 3.",
    exampleSteps: ["Multiply the first equation by 2 and the second by 5: 4x + 10y = 38 and 15x − 10y = 0.", "Add to eliminate y: 19x = 38, so x = 2.", "Substitute into 3x − 2y = 0: 6 − 2y = 0, giving y = 3.", "Check the other equation: 2(2) + 5(3) = 19."],
    questions: [
      q(1, "For the system 2x + 3y = 17 and 3x − 2y = 6, find x.", "4", "Multiply the equations by 2 and 3 so the y-coefficients become opposites.", "The scaled equations are 4x + 6y = 34 and 9x − 6y = 18. Adding gives 13x = 52, so x = 4; then y = 3 satisfies both originals.", evidence("solve-scaled-elimination", "procedure", "symbolic", "Multiplying a variable coefficient without multiplying every term and the right side.")),
      q(2, "For 3x + 2y = 4 and 5x − 3y = 13, find y.", "-1", "Eliminate y first by using multipliers 3 and 2, then substitute to find the requested variable.", "The equations become 9x + 6y = 12 and 10x − 6y = 26, so 19x = 38 and x = 2. Substitution gives 6 + 2y = 4, so y = −1.", evidence("solve-scaled-elimination", "procedure", "symbolic", "Returning the eliminated system's x-value when the prompt requests y.")),
      q(3, "Solve 2x + y = 8 and x − 2y = −1. Plot the solution on the coordinate grid.", "(3, 2)", "The first equation gives y = 8 − 2x; substitute it into the second before plotting.", "Substituting gives x − 2(8 − 2x) = −1, so 5x = 15 and x = 3. Then y = 2; the point (3, 2) satisfies 6 + 2 = 8 and 3 − 4 = −1.", evidence("plot-algebraic-system-solution", "representation", "graph", "Plotting the coordinates in the opposite order or solving only one equation."), grid()),
      q(4, "Solve 3x − y = −7 and 2x + 3y = 10. Plot their common solution.", "(-1, 4)", "Multiply the first equation by 3 so adding eliminates y.", "Adding 9x − 3y = −21 to 2x + 3y = 10 gives 11x = −11, so x = −1. Then −3 − y = −7 gives y = 4, producing (−1, 4).", evidence("plot-algebraic-system-solution", "representation", "graph", "Losing a negative sign while locating a solution to the left of the y-axis."), grid()),
      q(5, "Classify the system 2(x + y) = 10 and 4x + 4y = 24. Which explanation is valid?", "No solution; doubling the first equation requires 4x + 4y = 20, contradicting 24.", "Expand the first equation and compare equal left sides after scaling.", "The first equation is 2x + 2y = 10, whose double is 4x + 4y = 20. The second assigns the same expression the different value 24, so no ordered pair can satisfy both.", evidence("classify-expanded-systems", "reasoning", "symbolic", "Assuming proportional variable coefficients imply equivalent equations even when constants do not match."), options("Infinitely many solutions because the variable coefficients are proportional.", "One solution because there are two equations.", "No solution; doubling the first equation requires 4x + 4y = 20, contradicting 24.", "Only (0, 0), because both variables can cancel.")),
      q(6, "Classify 3(x − 2y) = 12 and 6x − 12y = 24. Which conclusion is justified?", "Infinitely many solutions; the second equation is twice the expanded first equation.", "Distribute the 3 to both terms before comparing the complete equations.", "The first expands to 3x − 6y = 12. Doubling every term gives exactly 6x − 12y = 24, so both equations describe the same line and every point on it is shared.", evidence("classify-expanded-systems", "reasoning", "symbolic", "Interpreting an identity after elimination as one solution instead of a shared line."), options("No solution because all variable terms cancel.", "Only x = 0 and y = 0.", "One solution because the coefficients are different.", "Infinitely many solutions; the second equation is twice the expanded first equation.")),
    ],
    remainingGaps: ["Choosing efficient algebraic methods across systems with fractional coefficients.", "Contextual systems with physical restrictions and comparisons between exact and graph-estimated solutions."],
  }),
  pack({
    lessonSlug: "g8-composed-transformations",
    objectives: [
      { id: "undo-transformation-sequence", description: "Recover a preimage by undoing a translation and then a reflection or rotation in reverse order.", requiredDemands: ["procedure"] },
      { id: "plot-composed-image", description: "Apply two specified rigid transformations in order and plot the final image of a point.", requiredDemands: ["representation"] },
      { id: "compare-transformation-order", description: "Calculate both orders of a transformation pair to demonstrate when the final images differ.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "A point is reflected across the x-axis, then translated left 2 and up 3, ending at (1, −1). Its original position was (3, 4).",
    exampleSteps: ["Undo the final translation first: (1, −1) becomes (1 + 2, −1 − 3) = (3, −4).", "Undo reflection across the x-axis by reversing the y-coordinate: (3, −4) becomes (3, 4).", "Check forward: reflection sends (3, 4) to (3, −4).", "Translating left 2 and up 3 then gives (1, −1), the stated final point."],
    questions: [
      q(1, "A point is reflected across the y-axis, then translated right 5 and down 2. Its final image is (1, 3). What was the original point?", "(4, 5)", "Undo the translation before undoing the reflection.", "Reversing the translation gives (1 − 5, 3 + 2) = (−4, 5). Reflection across the y-axis reverses x, so the preimage is (4, 5).", evidence("undo-transformation-sequence", "procedure", "symbolic", "Undoing transformations in the original order rather than reverse order.")),
      q(2, "A point is rotated 90° counterclockwise about the origin, then translated right 2 and down 1. The final point is (−3, 2). Find the original point.", "(3, 5)", "First undo the translation, then rotate 90° clockwise to reverse the original rotation.", "Undoing the translation gives (−5, 3). A 90° clockwise rotation sends (x, y) to (y, −x), yielding (3, 5). Forward rotation and translation return (−3, 2).", evidence("undo-transformation-sequence", "procedure", "symbolic", "Using the same rotation direction when attempting to recover a preimage.")),
      q(3, "Start with A = (−2, 1). Reflect across the y-axis, then rotate 90° counterclockwise about the origin. Plot the final image.", "(-1, 2)", "Update the point after reflection before applying (x, y) → (−y, x).", "Reflection sends (−2, 1) to (2, 1). The subsequent counterclockwise rotation gives (−1, 2), which is the point to plot.", evidence("plot-composed-image", "representation", "graph", "Applying the second rule to the original point instead of to the first image."), grid()),
      q(4, "Start with B = (1, −3). Rotate 90° clockwise about the origin, then translate right 4 and up 2. Plot the final point.", "(1, 1)", "A clockwise quarter-turn uses (x, y) → (y, −x), then the translation adds to that result.", "The rotation sends (1, −3) to (−3, −1). Adding (4, 2) gives (1, 1); applying the translation first would describe a different sequence.", evidence("plot-composed-image", "representation", "graph", "Using the counterclockwise coordinate rule for a clockwise rotation."), grid()),
      q(5, "For P = (1, 2), compare reflecting across the y-axis then translating right 2 with translating right 2 then reflecting across the y-axis. Which result is correct?", "The final points are (1, 2) and (−3, 2), respectively, so order matters.", "In the second sequence, the translation happens before the x-coordinate changes sign.", "Reflecting first gives (−1, 2), then (1, 2). Translating first gives (3, 2), then (−3, 2). The different final points show that these two operations do not commute for P.", evidence("compare-transformation-order", "reasoning", "symbolic", "Assuming every pair of rigid transformations can be reordered without changing its image."), options("Both sequences end at (1, 2), so order never matters.", "The final points are (1, 2) and (−3, 2), respectively, so order matters.", "The final points are (−3, 2) and (1, 2), respectively.", "Both sequences end at (3, 2), because reflection preserves x.")),
      q(6, "For P = (2, 1), compare a 90° counterclockwise rotation about the origin followed by reflection across the x-axis with the reverse order. Which statement is correct?", "The first sequence ends at (−1, −2); the reverse ends at (1, 2).", "Evaluate the intermediate image separately for each order.", "Rotation first gives (−1, 2), then reflection gives (−1, −2). Reflection first gives (2, −1), then rotation gives (1, 2), so the images differ.", evidence("compare-transformation-order", "reasoning", "symbolic", "Inferring equal final coordinates just because both sequences preserve lengths."), options("Both sequences end at (−1, −2).", "Both sequences end at (1, 2).", "The first sequence ends at (−1, −2); the reverse ends at (1, 2).", "The first sequence ends at (1, 2); the reverse ends at (−1, −2).")),
    ],
    remainingGaps: ["Transforming entire figures with connected edges and describing orientation changes visually.", "Classifying general compositions and proving equivalence beyond checking a single point."],
  }),
  pack({
    lessonSlug: "lines-of-fit",
    objectives: [
      { id: "derive-representative-line", description: "Construct a line through two specified representative points and use it to interpolate another output.", requiredDemands: ["procedure"] },
      { id: "compare-record-residuals", description: "Read observed coordinates and compare signed residuals relative to a supplied model.", requiredDemands: ["representation"] },
      { id: "compare-total-absolute-error", description: "Compare two proposed lines using an explicitly specified sum of absolute residuals across every observation.", requiredDemands: ["reasoning", "application"] },
    ],
    legacyObjectives: {},
    example: "A proposed line of fit passes through representative points (1, 6) and (5, 18). It predicts 12 at x = 3.",
    exampleSteps: ["Compute the slope: (18 − 6)/(5 − 1) = 12/4 = 3.", "Use (1, 6) to find the intercept: 6 = 3(1) + b, so b = 3.", "The proposed line is y = 3x + 3; at x = 3 it predicts 12.", "Because 3 lies between the representative inputs 1 and 5, this is interpolation within that interval."],
    questions: [
      q(1, "A proposed line of fit passes through representative points (2, 7) and (6, 15). What output does that line predict at x = 4?", "11", "Find the line's rate from both representative points, then advance from x = 2 to x = 4.", "The slope is (15 − 7)/(6 − 2) = 2 and the intercept is 7 − 2(2) = 3. The line predicts 2(4) + 3 = 11.", evidence("derive-representative-line", "procedure", "symbolic", "Using one observed output as an intercept or assuming the model equation is already known.")),
      q(2, "A proposed fitted line passes through (1, 18) and (5, 10). Find its predicted output at x = 3.", "14", "The output decreases as x increases, so the slope must be negative.", "The slope is (10 − 18)/(5 − 1) = −2, giving y = −2x + 20. At x = 3, the prediction is −6 + 20 = 14.", evidence("derive-representative-line", "procedure", "symbolic", "Dropping the slope's negative sign when interpolating a decreasing trend.")),
      q(3, "For the model y = 2x + 1, which recorded observation lies farthest above its predicted value?", "Record B", "Compute observed y minus predicted y for every row; compare the positive residuals.", "Predictions are 3, 5, 7, and 9, so the residuals are 1, 2, −1, and 0. B has the largest positive residual, meaning it is farthest above the model.", evidence("compare-record-residuals", "representation", "table", "Selecting the largest observed output instead of the largest observed-minus-predicted difference."), table(["Record", "x", "Observed y"], [["Record A", "A", "1", "4"], ["Record B", "B", "2", "7"], ["Record C", "C", "3", "6"], ["Record D", "D", "4", "9"]])),
      q(4, "For the model y = 3x + 2, which recorded observation is overpredicted by the greatest amount?", "Record D", "Overprediction means predicted y is larger than observed y, so look for the most negative residual.", "The model predicts 5, 8, 11, and 14. Observed-minus-predicted residuals are 0, −2, 1, and −4. D is overpredicted by 4, more than any other record.", evidence("compare-record-residuals", "representation", "table", "Choosing the most positive residual when the question asks about overprediction."), table(["Record", "x", "Observed y"], [["Record A", "A", "1", "5"], ["Record B", "B", "2", "6"], ["Record C", "C", "3", "12"], ["Record D", "D", "4", "10"]])),
      q(5, "For observations (0, 1), (1, 4), and (2, 5), compare line A: y = 2x + 1 with line B: y = 3x + 1. Using the sum of absolute residuals, which has the smaller total error?", "A; its total absolute error is 1, compared with 2 for B.", "Calculate every observed-minus-predicted difference, take each magnitude, then add them.", "A predicts 1, 3, 5, giving absolute errors 0, 1, 0 and total 1. B predicts 1, 4, 7, giving 0, 0, 2 and total 2. A is better under the stated criterion, even though B exactly matches the middle point.", evidence("compare-total-absolute-error", "reasoning", "verbal", "Selecting the line that matches one chosen point instead of comparing errors across all observations."), options("B; matching the middle point guarantees the best overall fit.", "They tie because each misses at most one point.", "A; its total absolute error is 1, compared with 2 for B.", "A; its signed residuals cancel to zero.")),
      q(6, "Observations are (0, 6), (1, 4), and (2, 3). Model A is y = 6 − x; model B is y = 6 − 2x. Which is better using the smaller sum of absolute residuals?", "B; its total absolute error is 1, while A's is 2.", "Both models match the first point; compare what happens at the other two inputs.", "A predicts 6, 5, 4 and has absolute errors 0, 1, 1, totaling 2. B predicts 6, 4, 2 and has absolute errors 0, 0, 1, totaling 1, so B is better by this stated rule.", evidence("compare-total-absolute-error", "application", "verbal", "Assuming models with the same intercept fit equally well or canceling signed errors before taking magnitudes."), options("A; a less steep line always has smaller errors.", "B; its total absolute error is 1, while A's is 2.", "They tie because both predict 6 at x = 0.", "Neither total can be calculated from three observations.")),
    ],
    remainingGaps: ["Reading or drawing an actual scatter plot and fitted line with residual segments.", "Least-squares fitting, influential observations, and checking predictions on new data."],
  }),
  pack({
    lessonSlug: "g9-systems-linear-inequalities",
    objectives: [
      { id: "count-feasible-integer-pairs", description: "Enumerate nonnegative or positive integer pairs satisfying a shared linear resource bound.", requiredDemands: ["procedure"] },
      { id: "compare-feasible-plans", description: "Read candidate plans, enforce two resource constraints, and choose the greatest stated objective among feasible rows.", requiredDemands: ["representation"] },
      { id: "reason-shared-boundaries", description: "Use strictness and equality to distinguish an empty overlap from a shared boundary line.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "For integers x ≥ 0 and y ≥ 0 with x + y ≤ 2, there are six feasible ordered pairs.",
    exampleSteps: ["When x = 0, y can be 0, 1, or 2, giving three pairs.", "When x = 1, y can be 0 or 1, giving two more pairs.", "When x = 2, only y = 0 works; larger x cannot satisfy the bound.", "The total is 3 + 2 + 1 = 6; (x, y) and (y, x) are different ordered pairs when the coordinates differ."],
    questions: [
      q(1, "How many ordered pairs of integers (x, y) satisfy x ≥ 0, y ≥ 0, and x + y ≤ 3?", "10", "List possible y-values separately for x = 0, 1, 2, and 3.", "For x = 0, 1, 2, and 3 there are respectively 4, 3, 2, and 1 possible y-values. Adding gives 10 feasible integer pairs, including boundary pairs and (0, 0).", evidence("count-feasible-integer-pairs", "procedure", "symbolic", "Counting only points on the boundary or treating ordered pairs as unordered.")),
      q(2, "How many ordered integer pairs satisfy x ≥ 1, y ≥ 1, and x + y ≤ 4?", "6", "Both coordinates must be positive, so exclude any pair with a zero coordinate.", "For x = 1, y may be 1, 2, or 3. For x = 2, y may be 1 or 2. For x = 3, y must be 1. The total is 3 + 2 + 1 = 6.", evidence("count-feasible-integer-pairs", "procedure", "symbolic", "Including axis points when the lower bounds require positive coordinates.")),
      q(3, "A production plan must satisfy 2x + y ≤ 10 and x + 3y ≤ 12. Among the listed nonnegative plans that meet both constraints, which makes the most total items x + y?", "Plan A", "Reject any row that exceeds either resource bound before comparing total output.", "A uses 10 and 10 resource units and makes 6 items. B uses 7 and 11 and makes 5. C violates the first bound with 11, while D violates the second with 13, so A is the best feasible listed plan.", evidence("compare-feasible-plans", "representation", "table", "Maximizing the objective before discarding plans that violate a required constraint."), table(["Plan", "x items", "y items"], [["Plan A", "A", "4", "2"], ["Plan B", "B", "2", "3"], ["Plan C", "C", "5", "1"], ["Plan D", "D", "1", "4"]])),
      q(4, "Plans must satisfy 3x + 2y ≤ 18 and x + y ≤ 7. Each x item earns $4 and each y item earns $3. Which feasible listed plan gives the greatest revenue?", "Plan C", "Compute feasibility first, then use 4x + 3y rather than just x + y to rank the survivors.", "A = (2, 5) satisfies both bounds and earns $23. C = (4, 3) uses 18 resource units, has 7 items, and earns $25. B violates the first bound with 19; D violates the second with 8 items. Thus C is best among the listed feasible plans.", evidence("compare-feasible-plans", "representation", "table", "Ranking by total item count when item types have different values."), table(["Plan", "x items", "y items"], [["Plan A", "A", "2", "5"], ["Plan B", "B", "5", "2"], ["Plan C", "C", "4", "3"], ["Plan D", "D", "1", "7"]])),
      q(5, "What is the solution set of y > x + 2 together with y ≤ x + 2?", "No points; y cannot be both greater than and at most the same value.", "The two comparisons use the identical expression x + 2, and the strict inequality excludes equality.", "For any fixed x, the first condition places y strictly above x + 2 while the second requires it at or below that value. They cannot both hold, including on the boundary.", evidence("reason-shared-boundaries", "reasoning", "symbolic", "Including a common boundary even when one required inequality is strict."), options("Every point on y = x + 2.", "Every point above y = x + 2.", "No points; y cannot be both greater than and at most the same value.", "Exactly the point (0, 2).")),
      q(6, "Describe the solutions of y ≥ 2x − 1 and y ≤ 2x − 1 taken together.", "Exactly the line y = 2x − 1; both bounds can hold only at equality.", "The inclusive lower and upper bounds coincide.", "The first bound requires y to be no smaller than 2x − 1 and the second no larger. Therefore y must equal 2x − 1, giving every point on that line and no points off it.", evidence("reason-shared-boundaries", "reasoning", "symbolic", "Assuming a feasible set must have area and cannot consist only of a boundary line."), options("No points because opposite half-planes cannot overlap.", "Exactly the line y = 2x − 1; both bounds can hold only at equality.", "All points in the plane.", "Only the intercept (0, −1).")),
    ],
    remainingGaps: ["Constructing and shading a full feasible region with solid and dashed boundaries.", "Finding an optimum over an entire continuous feasible region rather than comparing provided plans."],
  }),
  pack({
    lessonSlug: "g9-factoring-completely",
    objectives: [
      { id: "repeat-factoring-patterns", description: "Factor a fourth-degree difference of squares completely over the integers after removing a greatest common factor.", requiredDemands: ["procedure"] },
      { id: "plot-factored-intercepts", description: "Use complete factorization and the zero-product property to locate a requested polynomial x-intercept on a grid.", requiredDemands: ["representation"] },
      { id: "preserve-zero-factor-solutions", description: "Explain why division by a variable factor can remove valid zero solutions from a factored equation.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "The expression 4x⁴ − 2500 factors completely over the integers as 4(x − 5)(x + 5)(x² + 25).",
    exampleSteps: ["Remove the greatest common factor: 4x⁴ − 2500 = 4(x⁴ − 625).", "Apply difference of squares: x⁴ − 625 = (x² − 25)(x² + 25).", "Factor the remaining difference of squares: x² − 25 = (x − 5)(x + 5).", "The sum x² + 25 has no real zeros and no further integer factorization, so 4(x − 5)(x + 5)(x² + 25) is complete."],
    questions: [
      q(1, "Which expression is 2x⁴ − 32 factored completely over the integers?", "2(x − 2)(x + 2)(x² + 4)", "After taking out 2, apply difference of squares twice; check whether any quadratic factor can split further.", "First 2x⁴ − 32 = 2(x⁴ − 16) = 2(x² − 4)(x² + 4). Factoring x² − 4 gives 2(x − 2)(x + 2)(x² + 4); the sum x² + 4 is irreducible over the integers.", evidence("repeat-factoring-patterns", "procedure", "symbolic", "Stopping after the first difference-of-squares step or trying to split a positive sum of squares over the integers."), options("2(x − 2)(x + 2)(x² + 4)", "2(x² − 4)(x² + 4)", "2(x − 2)²(x + 2)²", "2(x − 4)(x + 4)")),
      q(2, "Choose the complete factorization over the integers of 3x⁴ − 243.", "3(x − 3)(x + 3)(x² + 9)", "The common factor leaves x⁴ − 81, which contains another difference of squares after one split.", "Take out 3: 3(x⁴ − 81) = 3(x² − 9)(x² + 9). Then x² − 9 = (x − 3)(x + 3), producing the stated complete form.", evidence("repeat-factoring-patterns", "procedure", "symbolic", "Forgetting the common factor or replacing a sum of squares with another difference."), options("3(x² − 9)(x² + 9)", "(x − 3)(x + 3)(x² + 9)", "3(x − 3)(x + 3)(x² + 9)", "3(x − 9)(x + 9)")),
      q(3, "The graph of y = x³ − 9x has one positive x-intercept. Factor the expression and plot that intercept on the coordinate grid.", "(3, 0)", "An x-intercept has y = 0; factor out x before using the difference of squares.", "The equation 0 = x(x² − 9) = x(x − 3)(x + 3) has roots 0, 3, and −3. The positive intercept is the point (3, 0), not (0, 3).", evidence("plot-factored-intercepts", "representation", "graph", "Plotting a root as a y-coordinate or dropping the common variable factor before solving."), grid()),
      q(4, "For y = 2x³ − 32x, plot the negative x-intercept on the grid after factoring completely.", "(-4, 0)", "Remove 2x, factor x² − 16, and select the negative root.", "Factoring gives 2x(x − 4)(x + 4). Its roots are 0, 4, and −4, so the requested negative x-intercept is (−4, 0).", evidence("plot-factored-intercepts", "representation", "graph", "Selecting the positive root or the zero root despite the requested intercept sign."), grid()),
      q(5, "A student solves x(x − 3)(x + 3) = 0 by dividing by x and reporting only x = −3 or 3. Which correction is needed?", "Include x = 0; division by x excluded a value that satisfies the original equation.", "Before canceling a variable factor, check the value that makes that factor zero.", "The original product is zero when x = 0, x = 3, or x = −3. Dividing by x assumes x ≠ 0, so that step loses the valid zero solution unless it is checked separately.", evidence("preserve-zero-factor-solutions", "reasoning", "symbolic", "Treating division by a potentially zero variable as an equivalence for all real inputs."), options("No correction; a factor x never creates a solution.", "Include x = 0; division by x excluded a value that satisfies the original equation.", "Remove x = −3 because negative inputs cannot solve products.", "Replace both answers with x = 9.")),
      q(6, "From x²(x − 2) = 0, a student divides by x² and concludes x = 2 is the only real solution. Which response is correct?", "The real solutions are 0 and 2; the canceled x² factor also vanishes at 0.", "A repeated variable factor still produces a real zero, even if that zero occurs more than once as a factor.", "The zero-product property gives x² = 0 or x − 2 = 0, hence x = 0 or x = 2. The repeated factor does not make zero disappear or create two different zero values.", evidence("preserve-zero-factor-solutions", "reasoning", "symbolic", "Losing a repeated zero root through division or counting it as two distinct real values."), options("The only real solution is 2 because squared factors are always positive.", "There are three distinct real solutions: 0, 0, and 2.", "The real solutions are 0 and 2; the canceled x² factor also vanishes at 0.", "There are no real solutions because division by zero is forbidden.")),
    ],
    remainingGaps: ["Factoring by grouping, nonmonic trinomials inside higher-degree expressions, and rational coefficients.", "Constructing complete polynomial graphs and interpreting repeated-root behavior at intercepts."],
  }),
  pack({
    lessonSlug: "g9-linear-vs-exponential",
    objectives: [
      { id: "recover-multiperiod-factor", description: "Recover a positive per-period exponential multiplier from observations separated by two equal time periods.", requiredDemands: ["procedure"] },
      { id: "match-uneven-time-data", description: "Choose a graph that matches all observations at unequally spaced times, accounting for the elapsed-time gaps.", requiredDemands: ["representation"] },
      { id: "locate-integer-model-crossover", description: "Compare linear and exponential predictions successively to find the first nonnegative integer input where the exponential model is larger.", requiredDemands: ["application"] },
    ],
    legacyObjectives: {},
    example: "An exponential quantity is 12 at time 0 and 48 at time 2. Its positive multiplier per time unit is 2.",
    exampleSteps: ["Write the model as y = 12r^t with r > 0.", "The time-2 observation gives 48 = 12r², so r² = 4.", "Take the positive square root: r = 2, since the multiplier is specified to be positive.", "Check the two separate steps: 12 → 24 → 48."],
    questions: [
      q(1, "A quantity follows y = 100r^t with positive constant multiplier r. It is 225 at t = 2. What is r, the multiplier for one time unit?", "1.5|3/2", "The total factor 225/100 covers two periods, so it equals r² rather than r.", "The observation gives 100r² = 225, so r² = 2.25. The positive root is r = 1.5; multiplying 100 by 1.5 twice gives 225.", evidence("recover-multiperiod-factor", "procedure", "symbolic", "Using a multi-period ratio as though it were the factor for one period.")),
      q(2, "An exponential quantity has value 80 at t = 0 and 45 at t = 2. Its multiplier per time unit is positive and constant. Find that multiplier.", "0.75|3/4", "Divide the later value by the initial value, then take the positive square root for two periods.", "The two-period factor is 45/80 = 9/16. Thus r² = 9/16 and r = 3/4 = 0.75. The sequence 80 → 60 → 45 confirms the result.", evidence("recover-multiperiod-factor", "procedure", "symbolic", "Subtracting a fixed amount for an exponential model or overlooking the two-period time gap.")),
      q(3, "Observations occur at t = 0, 1, and 3, with outputs 2, 4, and 16. Which displayed graph matches all three?", "Graph B", "The second observation is one period later, but the third is two more periods later.", "Graph B has outputs 2, 4, 8, 16 at times 0, 1, 2, 3. It matches the unequal-time observations with one constant factor of 2 per period; a straight line through the endpoints misses the middle observation.", evidence("match-uneven-time-data", "representation", "graph", "Treating unequal observation gaps as equal steps or matching only the two endpoints."), graph([
        { value: "Graph A", optionLabel: "Graph A", label: "A straight line through (0, 2) and (3, 16), with value about 6.67 at t = 1.", kind: "linear", a: 14 / 3, b: 2 },
        { value: "Graph B", optionLabel: "Graph B", label: "An increasing exponential curve through (0, 2), (1, 4), and (3, 16).", kind: "exponential", a: 2, b: 2 },
        { value: "Graph C", optionLabel: "Graph C", label: "An upward parabola with vertex (0, 2), passing through (1, 4) and (3, 20).", kind: "quadratic", a: 2, h: 0, k: 2 },
        { value: "Graph D", optionLabel: "Graph D", label: "An increasing exponential curve through (0, 2), (1, 6), and (2, 18).", kind: "exponential", a: 2, b: 3 },
      ], 0, 3, 0, 22)),
      q(4, "The observations are y = 16 at t = 0, y = 8 at t = 1, and y = 2 at t = 3. Which displayed graph matches all three values?", "Graph C", "The last recorded interval lasts two periods; a per-period factor of one half acts twice there.", "Graph C gives 16, 8, 4, 2 at times 0 through 3. Halving each period matches both unequal observation intervals; the other graphs disagree with at least one listed point.", evidence("match-uneven-time-data", "representation", "graph", "Halving only once across a two-period gap or replacing proportional decay with constant subtraction."), graph([
        { value: "Graph A", optionLabel: "Graph A", label: "A decreasing line through (0, 16) and (1, 8), reaching zero at t = 2.", kind: "linear", a: -8, b: 16 },
        { value: "Graph B", optionLabel: "Graph B", label: "An exponential decay curve through (0, 16), (1, 4), and (2, 1).", kind: "exponential", a: 16, b: 0.25 },
        { value: "Graph C", optionLabel: "Graph C", label: "An exponential decay curve through (0, 16), (1, 8), and (3, 2).", kind: "exponential", a: 16, b: 0.5 },
        { value: "Graph D", optionLabel: "Graph D", label: "An exponential decay curve through (0, 8), (1, 4), and (3, 1).", kind: "exponential", a: 8, b: 0.5 },
      ], 0, 3, 0, 18)),
      q(5, "Two models are A(t) = 100 + 20t and B(t) = 10 × 2^t for nonnegative integer t. What is the first integer t for which B(t) is strictly greater than A(t)?", "5", "Check successive integer times; exponential growth does not mean B is already larger at the start.", "For t = 0 through 4, B gives 10, 20, 40, 80, 160 while A gives 100, 120, 140, 160, 180, so B is still lower. At t = 5, B = 320 exceeds A = 200 for the first time.", evidence("locate-integer-model-crossover", "application", "symbolic", "Assuming the exponential model exceeds the linear model immediately despite a lower starting value.", 3)),
      q(6, "For nonnegative integer t, compare L(t) = 30 + 5t and E(t) = 2 × 3^t. Find the first integer time when E(t) > L(t).", "3", "Calculate both outputs at t = 0, 1, 2, and 3 and stop at the first strict crossing.", "The exponential values 2, 6, and 18 at t = 0, 1, and 2 remain below 30, 35, and 40. At t = 3, E = 54 and L = 45, so the first integer crossing is 3.", evidence("locate-integer-model-crossover", "application", "symbolic", "Comparing growth factors or slopes alone without evaluating totals at the relevant time.", 3)),
    ],
    remainingGaps: ["Estimating noninteger crossover times and proving eventual exponential dominance under stated assumptions.", "Fitting competing models to noisy observations and testing the constant-factor assumption."],
  }),
  pack({
    lessonSlug: "g9-correlation-residuals",
    objectives: [
      { id: "calculate-residual-squares", description: "Compute residuals from observed points and a model, then sum their squares without canceling signs.", requiredDemands: ["procedure"] },
      { id: "compare-residual-records", description: "Read recorded residuals for competing models and select the smallest sum of squared residuals.", requiredDemands: ["representation"] },
      { id: "interpret-zero-linear-correlation", description: "Explain why zero linear correlation can coexist with a deterministic nonlinear relationship in symmetric data.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "For the model y = x + 1 and observations (0, 2), (1, 4), (2, 5), the sum of squared residuals is 9.",
    exampleSteps: ["The model predicts 1, 2, and 3 at inputs 0, 1, and 2.", "Observed minus predicted gives residuals 1, 2, and 2.", "Square each residual: 1² = 1, 2² = 4, and 2² = 4.", "Add the squares: 1 + 4 + 4 = 9. Signed residuals should not cancel before squaring."],
    questions: [
      q(1, "For the model y = 2x + 1 and observed points (0, 2), (1, 2), and (2, 7), find the sum of squared residuals. A residual is observed minus predicted.", "6", "Compute all three predictions, then square each residual separately before adding.", "Predictions are 1, 3, and 5, giving residuals 1, −1, and 2. The sum of squares is 1² + (−1)² + 2² = 1 + 1 + 4 = 6.", evidence("calculate-residual-squares", "procedure", "symbolic", "Squaring the sum of residuals or letting positive and negative errors cancel before squaring.")),
      q(2, "Using the model y = −x + 5, calculate the sum of squared residuals for (0, 4), (1, 6), and (2, 1). Residual means observed minus predicted.", "9", "The decreasing model predicts 5, 4, and 3 at the listed inputs.", "The residuals are 4 − 5 = −1, 6 − 4 = 2, and 1 − 3 = −2. Their squared total is 1 + 4 + 4 = 9.", evidence("calculate-residual-squares", "procedure", "symbolic", "Keeping a negative sign on a squared negative residual.")),
      q(3, "Each row gives a candidate model's residuals on the same four observations. Which model has the smallest sum of squared residuals?", "Model C", "Square every entry before adding; a zero signed sum alone is not enough.", "The squared-error sums are A: 1 + 4 + 1 + 0 = 6, B: 4 + 0 + 4 + 1 = 9, C: 0 + 1 + 0 + 1 = 2, and D: 1 + 1 + 1 + 1 = 4. C is smallest under this criterion.", evidence("compare-residual-records", "representation", "table", "Selecting a zero signed residual sum instead of minimizing squared error."), table(["Model", "Residual 1", "Residual 2", "Residual 3", "Residual 4"], [["Model A", "A", "−1", "2", "−1", "0"], ["Model B", "B", "2", "0", "−2", "1"], ["Model C", "C", "0", "1", "0", "−1"], ["Model D", "D", "1", "1", "1", "1"]])),
      q(4, "These candidate models were evaluated on the same four records. Based only on the smallest sum of squared residuals, which fits those records best?", "Model B", "A single larger error may outweigh several small ones because errors are squared.", "A has squared total 4 + 0 + 4 + 0 = 8; B has 1 + 1 + 0 + 1 = 3; C has 0 + 0 + 0 + 4 = 4; D has 1 + 1 + 4 + 1 = 7. B is best by the specified measure despite C matching three records exactly.", evidence("compare-residual-records", "representation", "table", "Choosing the model with the most zero residuals while ignoring the magnitude of the remaining error."), table(["Model", "Residual 1", "Residual 2", "Residual 3", "Residual 4"], [["Model A", "A", "−2", "0", "2", "0"], ["Model B", "B", "1", "−1", "0", "1"], ["Model C", "C", "0", "0", "0", "2"], ["Model D", "D", "1", "−1", "2", "−1"]])),
      q(5, "For x = −2, −1, 0, 1, 2, the outputs are y = 4, 1, 0, 1, 4. These data have linear correlation r = 0. Which interpretation is correct?", "There is an exact nonlinear relationship y = x²; zero r only rules out a nonzero linear correlation here.", "Check the shape of the rule relating each input to its output instead of treating r as a measure of every kind of relationship.", "Every point satisfies y = x², so the outputs are completely determined by x in this data set. Symmetry gives zero linear correlation, but the U-shaped relationship remains exact and nonlinear.", evidence("interpret-zero-linear-correlation", "reasoning", "verbal", "Concluding that zero linear correlation means there is no relationship of any kind."), options("The variables have no relationship because r = 0.", "All y-values must be equal whenever r = 0.", "There is an exact nonlinear relationship y = x²; zero r only rules out a nonzero linear correlation here.", "The data must form a straight horizontal line.")),
      q(6, "At x = −2, −1, 0, 1, 2, the recorded outputs are 5, 8, 9, 8, 5. The linear correlation is zero. Which conclusion is supported?", "The points satisfy y = 9 − x², so zero linear correlation does not imply no relationship.", "Outputs on either side of zero match, and the middle output is largest; identify the curved rule.", "All points follow y = 9 − x² exactly. The symmetric curved pattern has zero linear correlation even though knowing x determines each recorded y, so a no-relationship claim would be incorrect.", evidence("interpret-zero-linear-correlation", "reasoning", "verbal", "Using a linear association statistic to dismiss an exact curved pattern."), options("The points satisfy y = 9 − x², so zero linear correlation does not imply no relationship.", "The five outputs are unrelated to their inputs.", "The output is constant because the linear correlation is zero.", "Zero correlation proves the outputs were selected randomly.")),
    ],
    remainingGaps: ["Interpreting actual residual and scatter plots, including influential observations.", "Comparing model complexity and predictive performance on observations excluded from fitting."],
  }),
];
