import { buildPracticeQuestion, type GraphChoicePlot, type QuestionInteractionConfig } from "./question-interactions.ts";
import type { CognitiveDemand, DepthQuestion, LessonDepthPack, QuestionEvidence } from "./curriculum-depth-types.ts";

const evidence = (objectiveId: string, demand: CognitiveDemand, representation: QuestionEvidence["representation"], difficulty: 1 | 2 | 3, misconception: string): QuestionEvidence => ({
  objectiveId, demand, representation, difficulty, misconception, variantFamily: `${objectiveId}-transfer-v1`,
});

type Response = { choices?: string[]; interactionConfig?: QuestionInteractionConfig };
const table = (columns: string[], rows: Array<[string, ...string[]]>): Response => ({
  choices: rows.map(([value]) => value),
  interactionConfig: { kind: "table-choice", columns, rows: rows.map(([value, ...cells]) => ({ value, cells })) },
});
const graph = (plots: GraphChoicePlot[], xMin: number, xMax: number, yMin: number, yMax: number): Response => ({
  choices: plots.map((plot) => plot.value), interactionConfig: { kind: "graph-choice", plots, xMin, xMax, yMin, yMax },
});
const grid = (min: number, max: number): Response => ({ interactionConfig: { kind: "coordinate-grid", xMin: min, xMax: max, yMin: min, yMax: max } });
const options = (...choices: string[]): Response => ({ choices });
const q = (number: number, prompt: string, answer: string, hint: string, explanation: string, questionEvidence: QuestionEvidence, response: Response = {}): DepthQuestion => ({
  ...buildPracticeQuestion({ id: `d1-q${number}`, prompt, answer, hint, ...response, interaction: response.interactionConfig?.kind }),
  evidence: questionEvidence, explanation,
});

// Prefix local objective names so evidence remains unambiguous across lessons.
const pack = (value: LessonDepthPack): LessonDepthPack => ({
  ...value,
  objectives: value.objectives.map((objective) => ({ ...objective, id: `${value.lessonSlug}:${objective.id}` })),
  legacyObjectives: Object.fromEntries(Object.entries(value.legacyObjectives).map(([id, objective]) => [id, `${value.lessonSlug}:${objective}`])),
  questions: value.questions.map((question) => ({ ...question, evidence: { ...question.evidence, objectiveId: `${value.lessonSlug}:${question.evidence.objectiveId}`, variantFamily: `${value.lessonSlug}:${question.evidence.variantFamily}` } })),
});

export const middleDepthPacks: LessonDepthPack[] = [
  pack({
    lessonSlug: "g7-proportional-tables",
    objectives: [
      { id: "complete-ratio", description: "Find a unit ratio and use it to complete a proportional relationship.", requiredDemands: ["procedure"] },
      { id: "read-ratio-table", description: "Distinguish constant ratios from constant differences in a numerical table.", requiredDemands: ["representation"] },
      { id: "test-proportional-model", description: "Decide whether a contextual rule is proportional, including the effect of a fixed fee.", requiredDemands: ["reasoning", "application"] },
    ],
    legacyObjectives: { q1: "complete-ratio", q3: "complete-ratio", q4: "complete-ratio", q5: "complete-ratio", q2: "read-ratio-table" },
    example: "A recipe uses 9 cups of water for 6 cups of rice. Keeping the recipe proportional, 10 cups of rice need 15 cups of water.",
    exampleSteps: ["Let x be cups of rice and y be cups of water; compute y/x = 9/6 = 1.5.", "Write the proportional rule y = 1.5x, with no fixed starting amount.", "For x = 10, calculate y = 1.5 × 10 = 15 cups.", "Check 15/10 = 1.5, which matches the original water-to-rice ratio."],
    questions: [
      q(1, "A proportional paint mixture uses 8 cups of blue paint for 12 cups of white. How many cups of blue are needed for 21 cups of white?", "14", "Keep blue/white in the same order: start with 8/12.", "The blue-to-white ratio is 8/12 = 2/3. Multiplying 21 by 2/3 gives 14 cups of blue.", evidence("complete-ratio", "procedure", "verbal", 2, "Reversing the ratio or adding the change in white to the blue amount.")),
      q(2, "Five identical notebooks cost $7.50 with no fee. At the same unit price, what is the cost of 8 notebooks in dollars?", "12", "First divide the cost by 5 to find dollars per notebook.", "The unit price is 7.50/5 = 1.50 dollars. Eight notebooks cost 8 × 1.50 = 12 dollars.", evidence("complete-ratio", "procedure", "verbal", 2, "Adding three dollars for three more notebooks instead of applying the unit price.")),
      q(3, "Each row lists y-values at x = 2, 4, and 6. Which row is proportional?", "Table C", "Divide each y-value by its column's x-value, rather than comparing differences alone.", "In Table C, 7/2 = 14/4 = 21/6 = 3.5. Every other row changes its y/x ratio.", evidence("read-ratio-table", "representation", "table", 2, "Treating a constant difference between outputs as sufficient for proportionality."), table(["Table", "y at x = 2", "y at x = 4", "y at x = 6"], [["Table A", "A", "7", "9", "11"], ["Table B", "B", "4", "8", "14"], ["Table C", "C", "7", "14", "21"], ["Table D", "D", "6", "10", "14"]])),
      q(4, "Each row lists distance y in kilometers at time x = 1, 3, and 5 hours. Which row has one constant ratio y/x?", "Route B", "The time gaps are 2 hours, but proportionality is checked with distance divided by time.", "Route B has 2.5/1 = 7.5/3 = 12.5/5 = 2.5 kilometers per hour. The other rows do not keep that ratio.", evidence("read-ratio-table", "representation", "table", 2, "Checking only equal time gaps or only the first two values."), table(["Route", "km at 1 h", "km at 3 h", "km at 5 h"], [["Route A", "A", "3", "7", "11"], ["Route B", "B", "2.5", "7.5", "12.5"], ["Route C", "C", "2", "6", "11"], ["Route D", "D", "5", "8", "11"]])),
      q(5, "A bike rental costs $4 to unlock plus $3 per hour. Is total cost proportional to hours? Choose the reason.", "No; the $4 fixed fee makes cost/hour vary.", "Compare the total cost for 1 hour and 2 hours; do not use the hourly charge alone.", "The costs are $7 and $10, so cost/hour is 7 and 5. The hourly increase is constant, but the total-cost ratio is not.", evidence("test-proportional-model", "reasoning", "verbal", 2, "Confusing a linear rule with a nonzero starting value with a proportional rule."), options("Yes; every extra hour adds $3.", "No; the $4 fixed fee makes cost/hour vary.", "Yes; all prices are positive.", "No; proportional quantities must have equal numerical values.")),
      q(6, "A delivery service charges $2 per kilometer plus a $6 fee. It removes the fee and keeps the per-kilometer price. Which statement describes the new cost rule?", "It is proportional: every cost/distance ratio is $2 per km.", "Write the rule after removing the fixed fee, then check its ratio for positive distances.", "The new rule is C = 2d. For any positive distance d, C/d = 2; at zero distance the rule gives zero cost.", evidence("test-proportional-model", "application", "verbal", 2, "Assuming a service with a previous fixed fee can never be proportional."), options("It is proportional only at 2 km.", "It is not proportional because the price changes with distance.", "It is proportional: every cost/distance ratio is $2 per km.", "It is proportional because cost always equals distance.")),
    ],
    remainingGaps: ["Graphs of proportional relationships with fractional and negative coordinates.", "Learner-designed proportional models with explicit limitations and measurement uncertainty."],
  }),
  pack({
    lessonSlug: "g7-equation-word-models",
    objectives: [
      { id: "solve-fee-model", description: "Translate and solve a fixed amount plus equal groups equation.", requiredDemands: ["procedure"] },
      { id: "read-budget-table", description: "Use a cost table to identify the greatest affordable whole-number quantity.", requiredDemands: ["representation"] },
      { id: "round-feasible-count", description: "Interpret fractional solutions under at-least and at-most whole-number constraints.", requiredDemands: ["reasoning", "application"] },
    ],
    legacyObjectives: { q1: "solve-fee-model", q3: "solve-fee-model", q4: "round-feasible-count" },
    example: "A climbing center charges $6 admission and $4 per climb. A $30 total pays for 6 climbs.",
    exampleSteps: ["Let c be the number of climbs. Admission is charged once, so 6 + 4c = 30.", "Subtract 6 from both sides to obtain 4c = 24.", "Divide both sides by 4 to obtain c = 6.", "Check the context: 6 + 4(6) = 30 dollars and 6 is a whole number of climbs."],
    questions: [
      q(1, "A museum charges a $9 booking fee plus $7 per ticket. The total is $58. How many tickets were bought?", "7", "Remove the one-time fee before dividing by the ticket price.", "Write 9 + 7t = 58. Then 7t = 49, so t = 7 tickets. Substitution gives 9 + 49 = 58.", evidence("solve-fee-model", "procedure", "verbal", 2, "Dividing the total by the ticket price before removing the fixed fee.")),
      q(2, "Four equal bags and 6 loose marbles contain 42 marbles altogether. How many marbles are in each bag?", "9", "The six loose marbles are outside the four equal groups.", "Let b be marbles per bag. From 4b + 6 = 42, subtract 6 to get 4b = 36, then divide by 4 to get b = 9.", evidence("solve-fee-model", "procedure", "verbal", 2, "Including the loose marbles in every bag instead of only once.")),
      q(3, "A game center charges $5 admission plus $3 per game. You can spend at most $22. Use the table to choose the greatest affordable number of games.", "5 games", "At most includes $22, but it excludes every total above $22.", "Five games cost 5 + 3(5) = $20. Six cost $23, exceeding the budget; therefore 5 is the greatest affordable count.", evidence("read-budget-table", "representation", "table", 2, "Rounding the budget quotient upward even though the spending limit is an upper bound."), table(["Games", "Total cost"], [["4 games", "4", "$17"], ["5 games", "5", "$20"], ["6 games", "6", "$23"], ["7 games", "7", "$26"]])),
      q(4, "A craft order has a $4 delivery fee and costs $2.50 per kit. With a budget of $17, select the greatest affordable kit count in the table.", "5 kits", "Calculate whether the row just above your candidate still fits the budget.", "Five kits cost 4 + 2.50(5) = $16.50. Six cost $19, so the maximum affordable whole-number count is 5.", evidence("read-budget-table", "representation", "table", 2, "Ignoring the delivery fee or treating a fractional kit as purchasable."), table(["Kits", "Total cost"], [["4 kits", "4", "$14.00"], ["5 kits", "5", "$16.50"], ["6 kits", "6", "$19.00"], ["7 kits", "7", "$21.50"]])),
      q(5, "You have 11 points and earn 6 points per completed round. You need at least 40. Why are 5 rounds required?", "4 rounds give 35 points, while 5 give 41.", "Test the whole numbers on either side of (40 − 11)/6.", "The inequality 11 + 6r ≥ 40 gives r ≥ 29/6. Four rounds are insufficient, but five reach 41 points.", evidence("round-feasible-count", "reasoning", "verbal", 2, "Rounding down a minimum whole-number requirement."), options("4 rounds give 35 points, while 5 give 41.", "Any fractional result is rounded to the nearest integer.", "40 divided by 6 is exactly 5.", "The initial 11 points must be earned again.")),
      q(6, "A taxi charges $7 to start and $4 per whole kilometer. With at most $30 available, what is the greatest whole number of kilometers you can pay for?", "5", "The inequality gives an upper bound; check the cost of both 5 km and 6 km.", "From 7 + 4k ≤ 30, k ≤ 23/4 = 5.75. Five whole kilometers cost $27; six cost $31 and exceed the limit.", evidence("round-feasible-count", "application", "verbal", 2, "Rounding 5.75 up despite an at-most budget constraint.")),
    ],
    remainingGaps: ["Multi-step models with variables on both sides and negative contextual quantities.", "Student-authored equations and critique of assumptions in an unfamiliar story."],
  }),
  pack({
    lessonSlug: "g7-surface-area",
    objectives: [
      { id: "sum-prism-faces", description: "Calculate the surface area of a closed rectangular prism from its dimensions.", requiredDemands: ["procedure"] },
      { id: "audit-face-table", description: "Match a face-area table to the dimensions of a rectangular prism.", requiredDemands: ["representation"] },
      { id: "remove-exposed-face", description: "Adjust a surface-area model when a box has no lid and explain which face is removed.", requiredDemands: ["reasoning", "application"] },
    ],
    legacyObjectives: { q1: "sum-prism-faces", q2: "sum-prism-faces" },
    example: "A closed box is 5 cm long, 3 cm wide, and 2 cm high. Its surface area is 62 cm².",
    exampleSteps: ["The top and bottom each have area 5 × 3 = 15 cm².", "The front and back each have area 5 × 2 = 10 cm²; the ends each have area 3 × 2 = 6 cm².", "Add each pair: 2(15) + 2(10) + 2(6) = 30 + 20 + 12 = 62 cm².", "For the same box without a lid, remove one 15 cm² face: 62 − 15 = 47 cm²."],
    questions: [
      q(1, "A closed rectangular box measures 6 cm by 4 cm by 3 cm. What is its total surface area in cm²?", "108", "There are two faces of each size: 6×4, 6×3, and 4×3.", "The three face areas are 24, 18, and 12 cm². The total is 2(24 + 18 + 12) = 108 cm².", evidence("sum-prism-faces", "procedure", "verbal", 2, "Using length × width × height, which measures volume rather than surface area.")),
      q(2, "A closed rectangular storage box measures 8 cm by 3 cm by 2 cm. Find its surface area in cm².", "92", "Calculate three different face areas before doubling their sum.", "The areas are 8×3 = 24, 8×2 = 16, and 3×2 = 6. Two of each give 2(24 + 16 + 6) = 92 cm².", evidence("sum-prism-faces", "procedure", "verbal", 2, "Counting only one face from each opposite pair.")),
      q(3, "A closed box is 5 cm long, 4 cm wide, and 2 cm high. Which face table lists the area of ONE face in each named pair correctly?", "Plan B", "The base uses length × width; the front uses length × height; an end uses width × height.", "One base is 5×4 = 20, one front is 5×2 = 10, and one end is 4×2 = 8 cm². Plan B matches all three.", evidence("audit-face-table", "representation", "table", 2, "Doubling an individual face area or confusing face area with an edge length."), table(["Plan", "One base (cm²)", "One front (cm²)", "One end (cm²)"], [["Plan A", "A", "20", "8", "10"], ["Plan B", "B", "20", "10", "8"], ["Plan C", "C", "40", "20", "16"], ["Plan D", "D", "9", "7", "6"]])),
      q(4, "A closed box is 7 cm long, 3 cm wide, and 4 cm high. Which table correctly lists the COMBINED area of each opposite pair?", "Plan D", "Each column asks for two faces, so double the relevant rectangle area.", "The base pair has 2(7×3) = 42 cm², the front pair 2(7×4) = 56 cm², and the end pair 2(3×4) = 24 cm².", evidence("audit-face-table", "representation", "table", 2, "Using areas of single faces when the table asks for opposite pairs."), table(["Plan", "Both bases (cm²)", "Front + back (cm²)", "Both ends (cm²)"], [["Plan A", "A", "21", "28", "12"], ["Plan B", "B", "42", "24", "56"], ["Plan C", "C", "20", "22", "14"], ["Plan D", "D", "42", "56", "24"]])),
      q(5, "A 6 cm by 4 cm box has height 2 cm and no lid. A learner uses 2(6×4 + 6×2 + 4×2) = 88 cm². Which correction gives the cardboard area, ignoring thickness and tabs?", "Subtract one 24 cm² lid, giving 64 cm².", "The box still has its base; only the lid is absent.", "The closed-box total is 88 cm². Remove one 6×4 = 24 cm² face, leaving 64 cm². Removing both horizontal faces would also remove the base.", evidence("remove-exposed-face", "reasoning", "verbal", 2, "Removing both opposite faces when only the lid is missing."), options("Subtract two 24 cm² faces, giving 40 cm².", "Subtract one 24 cm² lid, giving 64 cm².", "Subtract the 2 cm height, giving 86 cm².", "Keep 88 cm² because the dimensions did not change.")),
      q(6, "An open-top tray has base 8 cm by 5 cm and height 3 cm. How much cardboard in cm² is needed, ignoring thickness, overlaps, and tabs?", "118", "Add one base and four side faces, or remove one base-sized face from the closed-box total.", "One base contributes 8×5 = 40 cm². The sides contribute 2(8×3) + 2(5×3) = 48 + 30. Total: 40 + 48 + 30 = 118 cm².", evidence("remove-exposed-face", "application", "verbal", 2, "Applying the closed-box formula to a tray with no lid.")),
    ],
    remainingGaps: ["Triangular prisms and compound solids with hidden shared faces.", "Building and comparing actual nets, including tabs, waste, and unit conversions."],
  }),
  pack({
    lessonSlug: "g7-compare-distributions",
    objectives: [
      { id: "compute-mean-mad", description: "Calculate a mean and mean absolute deviation for a small data set.", requiredDemands: ["procedure"] },
      { id: "compare-data-table", description: "Use numerical data in a table to compare both typical value and variability.", requiredDemands: ["representation"] },
      { id: "qualify-group-claim", description: "Make a group comparison without assuming every individual follows the group center.", requiredDemands: ["reasoning", "application"] },
    ],
    legacyObjectives: {},
    example: "For A = {4, 6, 8}, mean = 6 and MAD = 4/3. For B = {7, 8, 9}, mean = 8 and MAD = 2/3. B has a higher center and less variability.",
    exampleSteps: ["Calculate the means: (4 + 6 + 8)/3 = 6 and (7 + 8 + 9)/3 = 8.", "For A, distances from its mean are 2, 0, and 2; MAD = (2 + 0 + 2)/3 = 4/3.", "For B, distances from its mean are 1, 0, and 1; MAD = (1 + 0 + 1)/3 = 2/3.", "Compare both measures: B's mean is 2 higher, but its MAD is smaller. This describes the groups, not every pair of individuals."],
    questions: [
      q(1, "The data are 2, 4, 6, and 8. Their mean is 5. What is their mean absolute deviation?", "2", "Use the positive distances from 5, then average those four distances.", "The distances are 3, 1, 1, and 3. Their mean is (3 + 1 + 1 + 3)/4 = 2.", evidence("compute-mean-mad", "procedure", "verbal", 2, "Averaging signed deviations, which cancel, instead of absolute deviations.")),
      q(2, "Find the mean absolute deviation of 5, 5, 9, and 9.", "2", "Find the mean first, then compute each distance from that mean.", "The mean is (5 + 5 + 9 + 9)/4 = 7. Every value is 2 away from 7, so the MAD is 2.", evidence("compute-mean-mad", "procedure", "verbal", 2, "Using the range or dividing deviations by the wrong number of values.")),
      q(3, "Each row shows two three-value data sets. Which row has Group B with a HIGHER mean and a SMALLER range than Group A?", "Pair C", "For each group, average its three values and subtract its minimum from its maximum.", "Pair C has A mean 6 and range 8, while B has mean 8 and range 2. Only this row makes B both higher in center and less spread out.", evidence("compare-data-table", "representation", "table", 2, "Comparing centers while ignoring whether the variability condition also holds."), table(["Pair", "Group A data", "Group B data"], [["Pair A", "A", "4, 5, 6", "5, 8, 11"], ["Pair B", "B", "5, 8, 11", "6, 8, 10"], ["Pair C", "C", "2, 6, 10", "7, 8, 9"], ["Pair D", "D", "7, 8, 9", "2, 6, 10"]])),
      q(4, "Each row compares delivery times in minutes. Which row has Service B with a LOWER mean and a SMALLER range than Service A?", "Pair B", "A quicker typical delivery needs the lower mean; more consistency needs the smaller range.", "In Pair B, A has mean 12 and range 12; B has mean 10 and range 2. Thus B is both quicker on average and less variable in these data.", evidence("compare-data-table", "representation", "table", 2, "Equating a lower average with more consistency without checking spread."), table(["Pair", "Service A minutes", "Service B minutes"], [["Pair A", "A", "9, 10, 11", "5, 9, 13"], ["Pair B", "B", "6, 12, 18", "9, 10, 11"], ["Pair C", "C", "6, 8, 10", "9, 10, 11"], ["Pair D", "D", "8, 10, 12", "7, 10, 13"]])),
      q(5, "Class A has median 80 and Class B has median 74. Why can we NOT conclude that every student in A scored above every student in B?", "Medians describe centers; the score ranges may overlap.", "A median locates a middle value and does not give the minimum and maximum.", "A higher median describes a higher typical score. It does not say that A's lowest score exceeds B's highest, so individual scores may overlap.", evidence("qualify-group-claim", "reasoning", "verbal", 2, "Turning a group-level center comparison into a claim about every individual."), options("Medians describe centers; the score ranges may overlap.", "A larger median always means a smaller sample.", "Medians are unrelated to scores.", "Every score in a group equals its median.")),
      q(6, "Two small trial samples give Route A a mean travel time of 20 minutes and MAD 6, and Route B a mean of 22 minutes and MAD 1. A traveler values consistency. Which conclusion is supported?", "B varies less in these samples, although its mean is 2 minutes longer.", "Compare the MADs for consistency and the means for typical time; keep the claim limited to the samples.", "B's MAD of 1 is smaller than A's 6, so its sampled times are more consistent. Its mean is 22 − 20 = 2 minutes longer; neither summary guarantees every future trip.", evidence("qualify-group-claim", "application", "verbal", 2, "Claiming the more consistent route is always faster or guarantees future arrival times."), options("A is always faster on every trip.", "B varies less in these samples, although its mean is 2 minutes longer.", "B guarantees arrival in exactly 22 minutes.", "The equal units imply equal variability.")),
    ],
    remainingGaps: ["Comparisons based on actual dot plots and box plots, including outliers and skew.", "Repeated-sample simulations and separation of group means measured in multiples of MAD."],
  }),
  pack({
    lessonSlug: "slope-rate",
    objectives: [
      { id: "calculate-signed-slope", description: "Calculate a signed rate from two points with a consistent subtraction order.", requiredDemands: ["procedure"] },
      { id: "match-slope-graph", description: "Match a numerical relationship to a line graph using both slope and intercept.", requiredDemands: ["representation"] },
      { id: "interpret-signed-rate", description: "Interpret a signed rate in context and distinguish rate from starting amount.", requiredDemands: ["reasoning", "application"] },
    ],
    legacyObjectives: { q1: "calculate-signed-slope", q2: "calculate-signed-slope", q3: "calculate-signed-slope", q5: "interpret-signed-rate" },
    example: "A tank contains 26 liters at 2 minutes and 14 liters at 6 minutes. Its constant rate is −3 liters per minute.",
    exampleSteps: ["Take the changes in the same order: volume change = 14 − 26 = −12 liters.", "The corresponding time change is 6 − 2 = 4 minutes.", "Divide: rate = −12/4 = −3 liters per minute; the negative sign means the water is decreasing.", "Check: four more minutes at −3 liters per minute changes 26 liters to 26 − 12 = 14 liters."],
    questions: [
      q(1, "Find the slope of the line through (−2, 7) and (4, −5).", "-2", "Use the same point order for the change in y and the change in x.", "The change in y is −5 − 7 = −12, and the change in x is 4 − (−2) = 6. Slope = −12/6 = −2.", evidence("calculate-signed-slope", "procedure", "symbolic", 2, "Reversing only one subtraction and losing the negative sign.")),
      q(2, "Find the slope through (−3, −4) and (5, 2).", "3/4|0.75", "The horizontal change crosses zero, so 5 − (−3) is 8.", "The vertical change is 2 − (−4) = 6 and the horizontal change is 5 − (−3) = 8. The slope is 6/8 = 3/4.", evidence("calculate-signed-slope", "procedure", "symbolic", 2, "Using rise or run alone, or mishandling subtraction of a negative coordinate.")),
      q(3, "A line contains the data pairs (0, 3), (2, 2), and (4, 1). Select its graph.", "Graph B", "The y-intercept is 3, and y decreases by 1 whenever x increases by 2.", "The slope is (2 − 3)/(2 − 0) = −1/2, so the rule is y = −0.5x + 3. Graph B has that intercept and decrease.", evidence("match-slope-graph", "representation", "graph", 2, "Choosing the correct slope sign while overlooking its magnitude or starting value."), graph([
        { value: "Graph A", optionLabel: "Graph A", label: "Line through (0, 3) and (4, 5)", kind: "linear", a: 0.5, b: 3 },
        { value: "Graph B", optionLabel: "Graph B", label: "Line through (0, 3) and (4, 1)", kind: "linear", a: -0.5, b: 3 },
        { value: "Graph C", optionLabel: "Graph C", label: "Line through (0, 1) and (4, -1)", kind: "linear", a: -0.5, b: 1 },
        { value: "Graph D", optionLabel: "Graph D", label: "Line through (0, 3) and (2, -1)", kind: "linear", a: -2, b: 3 },
      ], -2, 6, -4, 6)),
      q(4, "A line contains (0, −2), (2, 1), and (4, 4). Which graph matches all three points?", "Graph C", "Check the value at x = 0, then compare the rise of 3 with the run of 2.", "The intercept is −2 and the slope is 3/2. Thus y = 1.5x − 2, represented by Graph C.", evidence("match-slope-graph", "representation", "graph", 2, "Using run/rise instead of rise/run or changing the intercept sign."), graph([
        { value: "Graph A", optionLabel: "Graph A", label: "Line through (0, 2) and (2, 5)", kind: "linear", a: 1.5, b: 2 },
        { value: "Graph B", optionLabel: "Graph B", label: "Line through (0, -2) and (3, 0)", kind: "linear", a: 2 / 3, b: -2 },
        { value: "Graph C", optionLabel: "Graph C", label: "Line through (0, -2) and (4, 4)", kind: "linear", a: 1.5, b: -2 },
        { value: "Graph D", optionLabel: "Graph D", label: "Line through (0, -2) and (2, -5)", kind: "linear", a: -1.5, b: -2 },
      ], -2, 6, -6, 8)),
      q(5, "A tank's volume drops from 35 L at 1 minute to 23 L at 5 minutes. Which interpretation of its constant rate is correct?", "The volume decreases by 3 liters per minute.", "A decrease gives a negative rate, and the elapsed time is 5 − 1 minutes.", "Rate = (23 − 35)/(5 − 1) = −12/4 = −3 L/min. The tank loses 3 liters each minute during this constant-rate period.", evidence("interpret-signed-rate", "reasoning", "verbal", 2, "Interpreting the total change as the per-minute rate or dropping its sign."), options("The volume decreases by 12 liters per minute.", "The volume increases by 3 liters per minute.", "The volume decreases by 3 liters per minute.", "The tank initially contains −3 liters.")),
      q(6, "Plan A costs $12 plus $2 per visit. Plan B costs $5 plus $3 per visit. Which plan has the smaller rate of cost increase, and by how much per visit?", "Plan A, by $1 per visit.", "Compare the coefficients of visits, not the one-time starting fees.", "A increases by $2 per visit and B by $3 per visit. A's rate is 3 − 2 = $1 per visit smaller, even though A's starting fee is higher.", evidence("interpret-signed-rate", "application", "verbal", 2, "Confusing a smaller initial fee with a smaller slope."), options("Plan B, by $7 per visit.", "Plan A, by $1 per visit.", "Plan B, by $1 per visit.", "Plan A, by $7 per visit.")),
    ],
    remainingGaps: ["Estimating slopes from noisy observations and nonlinear intervals.", "Explaining slope invariance with similar triangles and handling vertical lines in contextual data."],
  }),
  pack({
    lessonSlug: "systems-graphing",
    objectives: [
      { id: "calculate-intersection", description: "Calculate and verify the common point of two nonparallel lines.", requiredDemands: ["procedure"] },
      { id: "plot-common-point", description: "Place a point satisfying two line equations on a coordinate grid.", requiredDemands: ["representation"] },
      { id: "explain-solution-count", description: "Use slopes and intercepts to justify no, one, or infinitely many solutions.", requiredDemands: ["reasoning", "application"] },
    ],
    legacyObjectives: { q1: "calculate-intersection", q2: "explain-solution-count", q3: "explain-solution-count", q5: "explain-solution-count" },
    example: "The lines y = 2x − 1 and y = −x + 5 meet at (2, 3).",
    exampleSteps: ["A shared point has equal y-values, so set 2x − 1 = −x + 5.", "Add x and add 1 to obtain 3x = 6, then divide by 3: x = 2.", "Substitute x = 2 into y = 2x − 1: y = 3.", "Check the other line: −2 + 5 = 3. Plot the common point (2, 3)."],
    questions: [
      q(1, "For y = 3x − 2 and y = −x + 6, what is the x-coordinate of the intersection?", "2", "At the intersection the two formulas for y are equal.", "Set 3x − 2 = −x + 6. Then 4x = 8, so x = 2. Both lines give y = 4.", evidence("calculate-intersection", "procedure", "symbolic", 2, "Finding a point on only one line rather than requiring both equations.")),
      q(2, "The lines y = 2x + 5 and y = −x − 1 intersect. What is the y-coordinate of the intersection?", "1", "Solve for x first, then substitute it into either equation.", "From 2x + 5 = −x − 1, 3x = −6 and x = −2. Substituting gives y = 2(−2) + 5 = 1; the second line also gives 1.", evidence("calculate-intersection", "procedure", "symbolic", 2, "Returning the solved x-coordinate when the question asks for y.")),
      q(3, "Plot the point shared by y = x + 2 and y = −x + 4.", "(1, 3)", "Set x + 2 equal to −x + 4, then plot x first and y second.", "The equality gives 2x = 2, so x = 1. Both equations give y = 3, making (1, 3) the common point.", evidence("plot-common-point", "representation", "graph", 2, "Swapping coordinates or plotting a line's intercept instead of the shared point."), grid(-5, 5)),
      q(4, "Plot the point shared by y = 2x + 1 and y = −x − 5.", "(-2, -3)", "The intersection is in the lower-left quadrant; verify both coordinates before plotting.", "Set 2x + 1 = −x − 5 to get 3x = −6, hence x = −2. Substitution gives y = −3 in both equations.", evidence("plot-common-point", "representation", "graph", 2, "Moving in the wrong direction for negative coordinates."), grid(-5, 5)),
      q(5, "Why do y = 4x + 1 and y = 4x − 3 have no shared point?", "They have equal slopes but different y-intercepts.", "Compare the slope and starting value of each line; also try equating their y-values.", "Both slopes are 4, while the intercepts differ. Equating gives 4x + 1 = 4x − 3, or 1 = −3, which is impossible.", evidence("explain-solution-count", "reasoning", "symbolic", 2, "Assuming equal slopes imply the equations represent the same line."), options("They have equal slopes but different y-intercepts.", "Their y-intercepts are both positive.", "Every line pair crosses once.", "They are the same line because both contain 4x.")),
      q(6, "Two sensors report temperature using y = 2x + 6 and 2y = 4x + 12. For how many x-values do their predictions agree?", "Every x-value; the equations describe the same line.", "Divide every term in the second equation by 2 before comparing it with the first.", "The second equation simplifies to y = 2x + 6, exactly the first rule. The predictions agree at every x-value in their shared model domain.", evidence("explain-solution-count", "application", "symbolic", 2, "Treating differently written but equivalent equations as different parallel lines."), options("None; the displayed coefficients differ.", "Exactly one x-value.", "Exactly two x-values.", "Every x-value; the equations describe the same line.")),
    ],
    remainingGaps: ["Reading approximate intersections of two simultaneously drawn graphs.", "Systems with rational intersection coordinates and graph-window limitations."],
  }),
  pack({
    lessonSlug: "dilations-similarity",
    objectives: [
      { id: "calculate-scale", description: "Find an image-to-original scale factor and calculate another corresponding length.", requiredDemands: ["procedure"] },
      { id: "plot-dilation", description: "Apply a dilation centered at the origin to a point on a coordinate grid.", requiredDemands: ["representation"] },
      { id: "test-similar-shapes", description: "Check whether corresponding lengths all share one scale factor in a contextual enlargement.", requiredDemands: ["reasoning", "application"] },
    ],
    legacyObjectives: { q1: "calculate-scale", q3: "calculate-scale", q5: "calculate-scale" },
    example: "A rectangle has sides 6 cm and 10 cm. A similar image has its shorter side 9 cm, so the scale factor is 1.5 and its longer side is 15 cm.",
    exampleSteps: ["Match corresponding sides: the original 6 cm side becomes the image's 9 cm side.", "Compute image/original = 9/6 = 1.5.", "Apply the same factor to the other side: 10 × 1.5 = 15 cm.", "Check the ratios: 9/6 = 15/10 = 1.5, so the rectangle's proportions are preserved."],
    questions: [
      q(1, "An original triangle side of 8 cm becomes 12 cm in a similar image. Another original side is 14 cm. Find its image length in cm.", "21", "Use image/original = 12/8, then multiply the 14 cm side by that factor.", "The scale factor is 12/8 = 1.5. The corresponding image side is 14 × 1.5 = 21 cm.", evidence("calculate-scale", "procedure", "verbal", 2, "Adding the same length increase instead of multiplying by the same factor.")),
      q(2, "A photograph's 15 cm width is reduced to 9 cm without distortion. Its original height is 20 cm. What is its new height in cm?", "12", "The reduction factor is the new width divided by the old width.", "The factor is 9/15 = 3/5. Apply it to the height: 20 × 3/5 = 12 cm.", evidence("calculate-scale", "procedure", "verbal", 2, "Reversing the reduction factor and enlarging the other dimension.")),
      q(3, "Dilate point P(−2, 1) by scale factor 2 about the origin. Plot P′.", "(-4, 2)", "Multiply both coordinates by 2; keep the signs of the original coordinates.", "A dilation about the origin sends (x, y) to (2x, 2y). Thus (−2, 1) becomes (−4, 2).", evidence("plot-dilation", "representation", "graph", 2, "Scaling just one coordinate or translating both coordinates by 2."), grid(-6, 6)),
      q(4, "Dilate Q(6, −4) by scale factor 1/2 about the origin. Plot Q′.", "(3, -2)", "A factor of one half places the point halfway from the origin along the same ray.", "Multiply each coordinate by 1/2: (6/2, −4/2) = (3, −2). The point stays in the same quadrant and moves closer to the origin.", evidence("plot-dilation", "representation", "graph", 2, "Subtracting one half or changing a coordinate's sign during a reduction."), grid(-6, 6)),
      q(5, "A triangle with sides 3, 4, 5 is compared with one whose corresponding sides are 6, 8, 11. Why are they not similar?", "The ratios are 2, 2, and 11/5, so there is no single scale factor.", "Check all three corresponding ratios, including the longest sides.", "The first two ratios are 6/3 = 2 and 8/4 = 2. The last is 11/5 = 2.2, so all corresponding lengths are not scaled equally.", evidence("test-similar-shapes", "reasoning", "verbal", 2, "Declaring triangles similar after checking only two corresponding side ratios."), options("All similar triangles must be the same size.", "The ratios are 2, 2, and 11/5, so there is no single scale factor.", "Every side grew, so the angles must grow too.", "A scale factor greater than 1 prevents similarity.")),
      q(6, "A 4 cm by 6 cm image must fit a frame exactly without cropping or distortion. Which frame preserves its proportions?", "10 cm by 15 cm", "Both dimensions must be multiplied by the same number.", "For 10 by 15, the width ratio is 10/4 = 2.5 and the height ratio is 15/6 = 2.5. The other frames use unequal factors.", evidence("test-similar-shapes", "application", "verbal", 2, "Preserving only one dimension or adding the same amount to both dimensions."), options("8 cm by 10 cm", "10 cm by 15 cm", "12 cm by 16 cm", "6 cm by 8 cm")),
    ],
    remainingGaps: ["Dilations about centers other than the origin and compositions with rigid motions.", "Constructing and justifying similarity transformations for complete figures."],
  }),
  pack({
    lessonSlug: "scatter-plots",
    objectives: [
      { id: "quantify-pattern-departure", description: "Calculate how far a plotted observation lies vertically from a stated linear pattern.", requiredDemands: ["procedure"] },
      { id: "read-coordinate-data", description: "Use actual paired coordinate data to identify direction and relative strength of association.", requiredDemands: ["representation"] },
      { id: "limit-association-claim", description: "Distinguish an observational association from a causal claim when another factor could affect both variables.", requiredDemands: ["reasoning", "application"] },
    ],
    legacyObjectives: {},
    example: "Most points follow y = 2x + 1. At x = 4 this pattern predicts 9; an observed point (4, 15) lies 6 units above it.",
    exampleSteps: ["Read the observation as x = 4 and y = 15; keep each input paired with its output.", "Use the stated pattern to predict y: 2(4) + 1 = 9.", "Subtract predicted from observed: 15 − 9 = 6, so the observation is 6 units above the pattern.", "Flag the departure for investigation; one unusual point alone does not explain its cause or justify deleting it."],
    questions: [
      q(1, "The main pattern in a data set is y = 3x + 2. An observation is (4, 20). How many y-units above the pattern is this point?", "6", "Predict y at the observation's x-value before comparing it with 20.", "At x = 4 the pattern predicts 3(4) + 2 = 14. The observed y is 20, so the point is 20 − 14 = 6 units above the pattern.", evidence("quantify-pattern-departure", "procedure", "symbolic", 2, "Comparing the observation with the intercept instead of the prediction at its x-value.")),
      q(2, "The main pattern is y = 2x + 5. A recorded point is (6, 11). How many y-units below the pattern is it?", "6", "Compute the expected height at x = 6 and compare it with the observed height.", "The predicted y is 2(6) + 5 = 17. The observed value 11 is 17 − 11 = 6 units below it.", evidence("quantify-pattern-departure", "procedure", "symbolic", 2, "Reporting the observed height or a horizontal difference instead of vertical departure.")),
      q(3, "Each table row gives y-values paired with x = 1, 2, 3, 4. Which data set has the strongest positive linear association?", "Set B", "Look for y increasing at an almost constant rate; a perfect decreasing line is negative association.", "Set B rises by 2 each step, so all four points lie on the increasing line y = 2x. Set C increases too, but its unequal changes make the linear pattern less exact.", evidence("read-coordinate-data", "representation", "table", 2, "Confusing strong negative association with positive association or overlooking scatter."), table(["Set", "y at x = 1", "y at x = 2", "y at x = 3", "y at x = 4"], [["Set A", "A", "8", "6", "4", "2"], ["Set B", "B", "2", "4", "6", "8"], ["Set C", "C", "2", "3", "7", "8"], ["Set D", "D", "5", "5", "5", "5"]])),
      q(4, "The columns pair x = 1, 2, 3, 4 with the listed y-values. Which row gives the strongest negative linear association?", "Set D", "A strong negative pattern falls consistently as x rises.", "Set D falls by 3 for every 1-unit increase in x, placing every point on y = 15 − 3x. Set B falls unevenly, and the other sets do not show a negative trend.", evidence("read-coordinate-data", "representation", "table", 2, "Treating any decreasing sequence as equally linear or confusing direction and strength."), table(["Set", "y at x = 1", "y at x = 2", "y at x = 3", "y at x = 4"], [["Set A", "A", "1", "4", "7", "10"], ["Set B", "B", "12", "10", "4", "3"], ["Set C", "C", "6", "6", "6", "6"], ["Set D", "D", "12", "9", "6", "3"]])),
      q(5, "Across several school grades, students carrying larger backpacks tend to be taller. Why does this observation NOT prove that larger backpacks make students grow taller?", "Age could affect both student height and backpack size.", "Consider a third factor that may differ across school grades and affect both measured quantities.", "Older students may be taller and may use larger backpacks. That common factor can produce an association without backpack size causing a change in height.", evidence("limit-association-claim", "reasoning", "verbal", 2, "Treating an observational trend as causal while overlooking a plausible common factor."), options("Age could affect both student height and backpack size.", "Positive association means the two quantities are always equal.", "An association can occur only when one variable causes the other.", "A larger sample would automatically prove the causal claim.")),
      q(6, "An observational study finds that towns with more ice-cream sales also have more swimming visits. Which conclusion is supported?", "The quantities are associated; hot weather could affect both.", "Ask whether the observations rule out a third factor affecting both quantities.", "The paired observations show association. Hot weather is a plausible common factor, so these observations alone cannot show that buying ice cream causes swimming visits.", evidence("limit-association-claim", "application", "verbal", 2, "Treating a positive association as proof that one measured variable causes the other."), options("Ice-cream purchases cause every swimming visit.", "Swimming visits prevent ice-cream purchases.", "The quantities are associated; hot weather could affect both.", "A positive association proves no other factor matters.")),
    ],
    remainingGaps: ["Direct reading and creation of actual scatter-plot graphics, including clusters and nonlinear form.", "Comparing line fits and outlier influence using larger realistic data sets."],
  }),
  pack({
    lessonSlug: "g9-graph-linear-inequalities",
    objectives: [
      { id: "calculate-feasible-y", description: "Substitute a fixed x-value and find the greatest integer y satisfying a linear inequality.", requiredDemands: ["procedure"] },
      { id: "match-boundary-graph", description: "Rearrange a two-variable inequality and identify its boundary line on a graph.", requiredDemands: ["representation"] },
      { id: "test-boundary-inclusion", description: "Test points in a half-plane and distinguish strict boundaries from included boundaries.", requiredDemands: ["reasoning", "application"] },
    ],
    legacyObjectives: { q3: "test-boundary-inclusion", q4: "test-boundary-inclusion", q5: "test-boundary-inclusion" },
    example: "For 2x + y ≤ 8, the boundary is y = −2x + 8. At x = 3, allowed y-values satisfy y ≤ 2.",
    exampleSteps: ["Subtract 2x to write y ≤ −2x + 8; the inequality direction stays the same.", "Draw the boundary through (0, 8) and (4, 0), using a solid line because equality is included.", "Test (0, 0): 0 ≤ 8 is true, so shade the half-plane containing the origin, below the boundary.", "At x = 3, solve 6 + y ≤ 8 to obtain y ≤ 2; the point (3, 2) is included on the boundary."],
    questions: [
      q(1, "For y < 2x + 1, let x = 3. What is the greatest integer y that is allowed?", "6", "The boundary value is excluded by the strict less-than sign.", "Substitute x = 3 to get y < 7. The greatest integer below 7 is 6; y = 7 is not allowed.", evidence("calculate-feasible-y", "procedure", "symbolic", 2, "Including the boundary value in a strict inequality.")),
      q(2, "For 3x + 2y ≤ 14, let x = 2. What is the greatest integer y allowed?", "4", "After substituting x, isolate 2y and remember that equality is allowed.", "Substitution gives 6 + 2y ≤ 14, so 2y ≤ 8 and y ≤ 4. Therefore 4 is the greatest allowed integer.", evidence("calculate-feasible-y", "procedure", "symbolic", 2, "Discarding a boundary point even though the inequality includes equality.")),
      q(3, "For 2x + y ≤ 4, choose the graph of its BOUNDARY LINE only. The options do not show the shaded region.", "Graph A", "Replace the inequality with equality and isolate y.", "The boundary equation is 2x + y = 4, or y = −2x + 4. Graph A passes through (0, 4) and (2, 0).", evidence("match-boundary-graph", "representation", "graph", 2, "Moving the x-term across the equality without changing its sign."), graph([
        { value: "Graph A", optionLabel: "Graph A", label: "Line through (0, 4) and (2, 0)", kind: "linear", a: -2, b: 4 },
        { value: "Graph B", optionLabel: "Graph B", label: "Line through (0, 4) and (-2, 0)", kind: "linear", a: 2, b: 4 },
        { value: "Graph C", optionLabel: "Graph C", label: "Line through (0, 2) and (4, 0)", kind: "linear", a: -0.5, b: 2 },
        { value: "Graph D", optionLabel: "Graph D", label: "Line through (0, -4) and (-2, 0)", kind: "linear", a: -2, b: -4 },
      ], -4, 5, -6, 8)),
      q(4, "For x − 2y > −4, select the graph of the BOUNDARY LINE only. Shading and boundary inclusion are not shown in these options.", "Graph D", "Solve x − 2y = −4 for y; divide both terms on the right by −2.", "The boundary satisfies −2y = −x − 4, hence y = 0.5x + 2. Graph D passes through (0, 2) and (4, 4).", evidence("match-boundary-graph", "representation", "graph", 2, "Losing the intercept sign or multiplying instead of dividing when isolating y."), graph([
        { value: "Graph A", optionLabel: "Graph A", label: "Line through (0, 2) and (4, 0)", kind: "linear", a: -0.5, b: 2 },
        { value: "Graph B", optionLabel: "Graph B", label: "Line through (0, -2) and (4, 0)", kind: "linear", a: 0.5, b: -2 },
        { value: "Graph C", optionLabel: "Graph C", label: "Line through (0, 2) and (2, 6)", kind: "linear", a: 2, b: 2 },
        { value: "Graph D", optionLabel: "Graph D", label: "Line through (0, 2) and (4, 4)", kind: "linear", a: 0.5, b: 2 },
      ], -5, 5, -5, 7)),
      q(5, "For y > −x + 2, select BOTH correct statements.", "(0, 3) is included. ; (1, 1) is excluded because equality is not allowed.", "Substitute each point into the original strict inequality, including points on its boundary.", "For (0, 3), 3 > 2 is true. For (1, 1), 1 > 1 is false, so the boundary point is excluded. The point (3, 0) is included because 0 > −1; (0, 0) is excluded because 0 > 2 is false.", evidence("test-boundary-inclusion", "reasoning", "symbolic", 2, "Using the wrong half-plane or including a strict boundary."), { choices: ["(0, 3) is included.", "(1, 1) is excluded because equality is not allowed.", "(3, 0) is excluded.", "(0, 0) is included."], interactionConfig: { kind: "multi-select", requiredSelections: 2 } }),
      q(6, "A budget allows 4x + 3y ≤ 24, where x and y are nonnegative whole-number item counts. Select BOTH correct statements.", "(3, 4) is allowed on the budget boundary. ; (2, 3) is allowed below the budget.", "Compute the total for each pair; spending exactly 24 is allowed.", "At (3, 4), cost is 12 + 12 = 24, so the boundary point is allowed. At (2, 3), cost is 8 + 9 = 17. The pair (5, 2) costs 26 and is excluded; (0, 8) costs exactly 24 and is included.", evidence("test-boundary-inclusion", "application", "verbal", 2, "Excluding exact-budget choices or accepting a point based on only one item cost."), { choices: ["(5, 2) is allowed.", "(3, 4) is allowed on the budget boundary.", "(0, 8) is excluded because it costs exactly 24.", "(2, 3) is allowed below the budget."], interactionConfig: { kind: "multi-select", requiredSelections: 2 } }),
    ],
    remainingGaps: ["Direct construction of dashed or solid boundaries and shaded half-planes.", "Vertical boundaries, compound constraints, and optimization over feasible regions."],
  }),
  pack({
    lessonSlug: "g9-build-quadratic-models",
    objectives: [
      { id: "calculate-quadratic-scale", description: "Use two zeros and another point to determine the coefficient of a quadratic model.", requiredDemands: ["procedure"] },
      { id: "match-vertex-model", description: "Use a vertex and another point to identify the correctly scaled parabola graph.", requiredDemands: ["representation"] },
      { id: "interpret-physical-parabola", description: "Interpret zeros and a maximum within the physically relevant domain of a quadratic model.", requiredDemands: ["reasoning", "application"] },
    ],
    legacyObjectives: { q3: "calculate-quadratic-scale", q6: "interpret-physical-parabola" },
    example: "A bridge arch has zeros at x = 1 and x = 7 and passes through (4, 18). Its model is y = −2(x − 1)(x − 7).",
    exampleSteps: ["Use the zeros to write y = a(x − 1)(x − 7).", "Substitute the known point: 18 = a(4 − 1)(4 − 7) = −9a.", "Divide by −9 to obtain a = −2, so y = −2(x − 1)(x − 7).", "The arch's physical span is 1 ≤ x ≤ 7; its symmetry axis is x = 4 and its maximum height is 18."],
    questions: [
      q(1, "A quadratic has zeros −1 and 3 and passes through (1, 8). In y = a(x + 1)(x − 3), find a.", "-2", "Substitute x = 1 and y = 8; keep the negative factor from 1 − 3.", "The point gives 8 = a(2)(−2) = −4a, so a = −2. The negative coefficient makes the parabola open downward.", evidence("calculate-quadratic-scale", "procedure", "symbolic", 2, "Setting a equal to the point's y-value or losing the sign of a factor.")),
      q(2, "A quadratic has zeros −2 and 4 and passes through (0, −16). In y = a(x + 2)(x − 4), find a.", "2", "Use both factors evaluated at x = 0 before solving for a.", "Substitution gives −16 = a(2)(−4) = −8a. Dividing by −8 gives a = 2.", evidence("calculate-quadratic-scale", "procedure", "symbolic", 2, "Assuming a negative y-value means the parabola must open downward.")),
      q(3, "A parabola has vertex (2, 9) and passes through (0, 1). Choose its graph.", "Graph C", "Write y = a(x − 2)² + 9 and use (0, 1) to find a.", "The point gives 1 = 4a + 9, hence a = −2. Graph C represents y = −2(x − 2)² + 9 and passes through both specified features.", evidence("match-vertex-model", "representation", "graph", 2, "Using the correct vertex but an arbitrary width or opening direction."), graph([
        { value: "Graph A", optionLabel: "Graph A", label: "Downward parabola with vertex (2, 9), passing through (0, 5)", kind: "quadratic", a: -1, h: 2, k: 9 },
        { value: "Graph B", optionLabel: "Graph B", label: "Upward parabola with vertex (2, 9), passing through (0, 17)", kind: "quadratic", a: 2, h: 2, k: 9 },
        { value: "Graph C", optionLabel: "Graph C", label: "Downward parabola with vertex (2, 9), passing through (0, 1)", kind: "quadratic", a: -2, h: 2, k: 9 },
        { value: "Graph D", optionLabel: "Graph D", label: "Downward parabola with vertex (-2, 9), passing through (0, 1)", kind: "quadratic", a: -2, h: -2, k: 9 },
      ], -4, 6, -8, 18)),
      q(4, "A parabola has vertex (−1, −4) and passes through (1, 4). Which graph fits both facts?", "Graph B", "In y = a(x + 1)² − 4, substituting (1, 4) gives 4 = 4a − 4.", "Solving gives 8 = 4a and a = 2. Graph B is y = 2(x + 1)² − 4, with the required vertex and point.", evidence("match-vertex-model", "representation", "graph", 2, "Writing x − 1 for a vertex whose x-coordinate is −1."), graph([
        { value: "Graph A", optionLabel: "Graph A", label: "Upward parabola with vertex (1, -4), passing through (-1, 4)", kind: "quadratic", a: 2, h: 1, k: -4 },
        { value: "Graph B", optionLabel: "Graph B", label: "Upward parabola with vertex (-1, -4), passing through (1, 4)", kind: "quadratic", a: 2, h: -1, k: -4 },
        { value: "Graph C", optionLabel: "Graph C", label: "Upward parabola with vertex (-1, -4), passing through (1, 0)", kind: "quadratic", a: 1, h: -1, k: -4 },
        { value: "Graph D", optionLabel: "Graph D", label: "Downward parabola with vertex (-1, -4), passing through (1, -12)", kind: "quadratic", a: -2, h: -1, k: -4 },
      ], -5, 4, -14, 12)),
      q(5, "A ball's height is h(t) = −t² + 6t meters, from launch until it next reaches the ground. Which statement correctly gives its physical time interval and maximum?", "0 ≤ t ≤ 6; maximum 9 m at t = 3 s.", "Factor for the ground times, then use the midpoint of the zeros for the maximum.", "The zeros of −t(t − 6) are 0 and 6 seconds. The vertex is at t = 3, where h(3) = −9 + 18 = 9 meters. The flight interval is 0 ≤ t ≤ 6.", evidence("interpret-physical-parabola", "reasoning", "verbal", 2, "Using the algebraic domain of all real numbers as the physical flight interval."), options("All real t; maximum 6 m at t = 0 s.", "0 ≤ t ≤ 3; maximum 9 m at t = 6 s.", "0 ≤ t ≤ 6; maximum 9 m at t = 3 s.", "0 ≤ t ≤ 9; maximum 3 m at t = 6 s.")),
      q(6, "An arch above a level deck is modeled by y = −2(x − 3)² + 18 meters. What are its deck-to-deck span and maximum height?", "Span 6 m; maximum height 18 m.", "Set y = 0 to find both deck contacts, and read the height at the vertex.", "At y = 0, (x − 3)² = 9, so x = 0 or 6. The physical span is 6 − 0 = 6 meters. The vertex at (3, 18) gives the maximum height of 18 meters.", evidence("interpret-physical-parabola", "application", "verbal", 2, "Confusing the symmetry-axis coordinate with the total width of the arch."), options("Span 3 m; maximum height 18 m.", "Span 6 m; maximum height 18 m.", "Span 18 m; maximum height 6 m.", "Span 9 m; maximum height 3 m.")),
    ],
    remainingGaps: ["Fitting a quadratic to three arbitrary observations and comparing model errors.", "Deriving area, revenue, and projectile models from contextual relationships rather than supplied features."],
  }),
  pack({
    lessonSlug: "g9-system-models",
    objectives: [
      { id: "solve-count-resource", description: "Use a count condition and a weighted total to solve for two contextual quantities.", requiredDemands: ["procedure"] },
      { id: "translate-two-conditions", description: "Match a contextual count and weighted total to two equations in a structured table.", requiredDemands: ["representation"] },
      { id: "check-contextual-feasibility", description: "Check that a system's solution meets both totals and the whole-number restrictions of the context.", requiredDemands: ["reasoning", "application"] },
    ],
    legacyObjectives: { q1: "solve-count-resource", q4: "solve-count-resource", q6: "translate-two-conditions" },
    example: "There are 18 adult and child tickets. Adult tickets cost $9, child tickets $5, and the total is $122. There are 8 adults and 10 children.",
    exampleSteps: ["Let a count adults and c count children. Write a + c = 18 and 9a + 5c = 122.", "Multiply the count equation by 5: 5a + 5c = 90.", "Subtract it from the price equation: 4a = 32, so a = 8.", "Then c = 18 − 8 = 10. Check 9(8) + 5(10) = 122 and 8 + 10 = 18."],
    questions: [
      q(1, "Forty tickets cost $380 altogether. Adult tickets cost $12 and child tickets $7. How many adult tickets were sold?", "20", "Compare the total with the cost if all 40 tickets had the child price.", "All-child cost would be 40×7 = $280. The extra $100 comes from adult tickets adding $5 each, so there are 100/5 = 20 adults and 20 children.", evidence("solve-count-resource", "procedure", "verbal", 2, "Dividing total revenue by one ticket price while ignoring the mixed prices.")),
      q(2, "A farm has 18 chickens and rabbits altogether, with 50 legs. Chickens have 2 legs and rabbits 4. How many rabbits are there?", "7", "Start with 18 two-legged animals and account for the extra legs.", "If all 18 were chickens there would be 36 legs. The extra 14 legs require 14/2 = 7 rabbits. The remaining 11 chickens give 7×4 + 11×2 = 50 legs.", evidence("solve-count-resource", "procedure", "verbal", 2, "Counting each rabbit as four extra legs instead of two extra legs beyond a chicken.")),
      q(3, "A shop sells 15 pens and notebooks altogether. Pens cost $2, notebooks $5, and total revenue is $48. With p pens and n notebooks, which table row models both conditions?", "Model D", "One equation counts items; the other multiplies each item count by its own price.", "The item count is p + n = 15 and the price total is 2p + 5n = 48. Model D keeps the count and money units separate.", evidence("translate-two-conditions", "representation", "table", 2, "Swapping the item total and the monetary total or pairing prices with the wrong variables."), table(["Model", "Item-count equation", "Revenue equation"], [["Model A", "A", "p + n = 48", "2p + 5n = 15"], ["Model B", "B", "p + n = 15", "5p + 2n = 48"], ["Model C", "C", "2p + 5n = 15", "p + n = 48"], ["Model D", "D", "p + n = 15", "2p + 5n = 48"]])),
      q(4, "A jar has 12 coins, all quarters and dimes, worth $2.10. Let q count quarters and d count dimes. Which row is correct when money is measured in cents?", "Model B", "Convert $2.10 to cents before combining it with the 25-cent and 10-cent coin values.", "The count is q + d = 12. In cents, the value equation is 25q + 10d = 210. Model B uses consistent money units.", evidence("translate-two-conditions", "representation", "table", 2, "Combining dollar totals with cent-valued coefficients or reversing coin values."), table(["Model", "Coin-count equation", "Value equation in cents"], [["Model A", "A", "q + d = 12", "25q + 10d = 2.10"], ["Model B", "B", "q + d = 12", "25q + 10d = 210"], ["Model C", "C", "q + d = 210", "25q + 10d = 12"], ["Model D", "D", "q + d = 12", "10q + 25d = 210"]])),
      q(5, "A report says exactly 5 tickets, priced at $4 or $7 each, brought in $24. Why is the report impossible?", "It would require 4/3 of the $7 tickets, which is not a whole number.", "If all five tickets were $4, each replacement by a $7 ticket would add exactly $3.", "Five $4 tickets total $20. Reaching $24 would need $4 extra, or 4/3 upgrades of $3 each. Ticket counts must be whole numbers, so no valid mix gives $24.", evidence("check-contextual-feasibility", "reasoning", "verbal", 2, "Accepting a fractional algebraic solution for indivisible counted objects."), options("It would require 4/3 of the $7 tickets, which is not a whole number.", "Five tickets must all have the same price.", "Every system with two equations has no solution.", "The total must always be $35.")),
      q(6, "A workshop has 10 bicycles and four-wheeled carts, with 34 wheels altogether. Which inventory meets both conditions?", "3 bicycles and 7 carts", "Check both the number of vehicles and the weighted wheel count for each choice.", "Three bicycles and seven carts give 3 + 7 = 10 vehicles and 2(3) + 4(7) = 34 wheels. The other inventories fail the wheel total or vehicle total.", evidence("check-contextual-feasibility", "application", "verbal", 2, "Checking only the total number of objects and ignoring the weighted resource total."), options("7 bicycles and 3 carts", "3 bicycles and 7 carts", "5 bicycles and 5 carts", "1 bicycle and 8 carts")),
    ],
    remainingGaps: ["Mixture and rate models with rational quantities, and three-variable systems.", "Dependent or inconsistent contextual constraints and student selection of an efficient solution method."],
  }),
  pack({
    lessonSlug: "g9-interpret-linear-models",
    objectives: [
      { id: "calculate-prediction-residual", description: "Calculate a model prediction and its signed residual as observed minus predicted.", requiredDemands: ["procedure"] },
      { id: "match-model-table", description: "Match a linear model to a table of predictions, keeping slope and intercept distinct.", requiredDemands: ["representation"] },
      { id: "bound-data-claims", description: "Distinguish interpolation from extrapolation and association from causation in an observational model.", requiredDemands: ["reasoning", "application"] },
    ],
    legacyObjectives: { q4: "bound-data-claims", q5: "bound-data-claims" },
    example: "A model predicts score y = 4x + 50 from practice hours x. At 3 hours, an observed score of 65 has residual 65 − 62 = 3 points.",
    exampleSteps: ["Identify the units: x is hours and y is score points, so the slope is 4 score points per hour.", "At x = 3, the prediction is 4(3) + 50 = 62 points.", "Residual means observed minus predicted: 65 − 62 = 3 points, so the observation is above the fitted line.", "A prediction at 3 hours is within an observed 1–5 hour range, but association in observational data alone does not establish causation."],
    questions: [
      q(1, "A delivery-time model is y = 2.5x + 10 minutes, where x is distance in km. A 4 km delivery actually takes 23 minutes. Find its residual in minutes: observed minus predicted.", "3", "First evaluate the model at 4 km, then subtract that prediction from the actual time.", "Predicted time is 2.5(4) + 10 = 20 minutes. The residual is 23 − 20 = 3 minutes, meaning the delivery took longer than predicted.", evidence("calculate-prediction-residual", "procedure", "verbal", 2, "Reversing predicted and observed values in the residual calculation.")),
      q(2, "A cooling model predicts y = −1.5x + 40 degrees after x minutes. At 8 minutes the observed temperature is 25 degrees. Find the residual: observed minus predicted.", "-3", "Keep the negative slope when predicting, and use observed minus predicted afterward.", "The prediction is −1.5(8) + 40 = 28 degrees. The residual is 25 − 28 = −3 degrees, so the observation is below the fitted line.", evidence("calculate-prediction-residual", "procedure", "verbal", 2, "Reporting an absolute difference and losing whether the observation is above or below the model.")),
      q(3, "The fitted model is y = 3x + 2. Which row contains its predictions at x = 0, 2, and 4?", "Forecast A", "The first prediction equals the intercept; each 2-unit x-step changes y by 6.", "Substitute the inputs: y(0) = 2, y(2) = 8, and y(4) = 14. Forecast A matches all three values.", evidence("match-model-table", "representation", "table", 2, "Treating the slope as the starting value or omitting the intercept."), table(["Forecast", "y at x = 0", "y at x = 2", "y at x = 4"], [["Forecast A", "A", "2", "8", "14"], ["Forecast B", "B", "3", "7", "11"], ["Forecast C", "C", "0", "6", "12"], ["Forecast D", "D", "2", "5", "8"]])),
      q(4, "A model predicts remaining water y = −2x + 18 liters after x minutes. Which prediction row is correct?", "Forecast C", "As time increases by 2 minutes, the predicted water amount drops by 4 liters.", "At x = 1, 3, and 5, the predictions are 16, 12, and 8 liters. Forecast C matches the negative slope and the starting amount.", evidence("match-model-table", "representation", "table", 2, "Adding the magnitude of a negative slope or reading the intercept as the first listed observation."), table(["Forecast", "liters at 1 min", "liters at 3 min", "liters at 5 min"], [["Forecast A", "A", "20", "24", "28"], ["Forecast B", "B", "18", "14", "10"], ["Forecast C", "C", "16", "12", "8"], ["Forecast D", "D", "16", "14", "12"]])),
      q(5, "An observational model links practice hours to scores, using students with 1–5 hours of practice. Select BOTH supported statements.", "Predicting at 3 hours is interpolation. ; The association alone does not prove practice caused the score difference.", "Check whether the proposed input lies inside the observed range, then consider what observational data can establish.", "Three hours lies within 1–5, so it is interpolation. Ten hours is extrapolation. Because the study is observational, factors such as prior preparation could also explain score differences.", evidence("bound-data-claims", "reasoning", "verbal", 2, "Assuming an in-range prediction is certain or that a fitted slope establishes causation."), { choices: ["Predicting at 3 hours is interpolation.", "Predicting at 10 hours is interpolation.", "The association alone does not prove practice caused the score difference.", "The line guarantees every student's exact score."], interactionConfig: { kind: "multi-select", requiredSelections: 2 } }),
      q(6, "A shop's observational data link outdoor temperature, from 18°C to 30°C, to daily sales. Select BOTH justified statements about using its fitted line.", "A prediction at 24°C is within the observed range. ; The data alone do not rule out other causes of sales changes.", "Locate 24°C and 40°C relative to the observed interval, then distinguish association from a controlled experiment.", "The value 24°C is inside 18–30°C, while 40°C is outside and requires extrapolation. Other factors, such as holidays, might also affect sales, so the fitted relationship alone is not a causal result.", evidence("bound-data-claims", "application", "verbal", 2, "Treating an extrapolated forecast or a causal explanation as guaranteed by an observational trend."), { choices: ["A forecast at 40°C is supported as strongly as an in-range prediction.", "A prediction at 24°C is within the observed range.", "The data alone do not rule out other causes of sales changes.", "Temperature must be the only cause of sales changes."], interactionConfig: { kind: "multi-select", requiredSelections: 2 } }),
    ],
    remainingGaps: ["Reading actual residual plots and comparing competing fitted models.", "Calculating correlation from data and explaining uncertainty rather than treating predictions as exact."],
  }),
];
