import type { CognitiveDemand, DepthQuestion, LessonDepthPack, QuestionEvidence } from "./curriculum-depth-types.ts";

function evidence(objectiveId: string, demand: CognitiveDemand, representation: QuestionEvidence["representation"], misconception: string): QuestionEvidence {
  return { objectiveId, demand, representation, difficulty: 2, misconception, variantFamily: `${objectiveId}-variants` };
}
function choice(n: number, objective: string, demand: CognitiveDemand, prompt: string, choices: string[], answer: string, hint: string, explanation: string, misconception: string): DepthQuestion {
  return { id: `d3-q${n}`, prompt, choices, answer, hint, explanation, interaction: "four-choice", evidence: evidence(objective, demand, demand === "procedure" ? "symbolic" : "verbal", misconception) };
}
function table(n: number, objective: string, prompt: string, columns: string[], cells: string[][], correct: number, hint: string, explanation: string, misconception: string): DepthQuestion {
  const rows = cells.map((row, i) => ({ value: String.fromCharCode(65 + i), cells: row }));
  return { id: `d3-q${n}`, prompt, answer: rows[correct].value, choices: rows.map((row) => row.value), hint, explanation, interaction: "table-choice", interactionConfig: { kind: "table-choice", columns, rows }, evidence: evidence(objective, "representation", "table", misconception) };
}

export const round3AdvancedDepthPacks: LessonDepthPack[] = [
  {
    lessonSlug: "g10-triangle-congruence",
    objectives: [
      { id: "congruence-corresponding-equation", description: "Use the vertex order of a congruence statement to solve a corresponding-side equation.", requiredDemands: ["procedure"] },
      { id: "congruence-sas-measurements", description: "Compare side-and-included-angle measurement records to identify an SAS-congruent triangle.", requiredDemands: ["representation"] },
      { id: "congruence-aaa-counterexample", description: "Use scaled side lengths to explain why equal corresponding angles do not ensure congruence.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "If △ABC≅△DEF, AB=2x+1 and DE=19, then x=9 because AB corresponds to DE.",
    exampleSteps: ["Match vertices in order: A↔D, B↔E, and C↔F.", "Corresponding sides AB and DE are equal, so 2x+1=19.", "Subtract 1 and divide by 2: 2x=18, hence x=9.", "Substitute back: AB=2·9+1=19=DE. The side length is 19, while the variable is 9."],
    questions: [
      choice(1, "congruence-corresponding-equation", "procedure", "△ABC≅△DEF. AB=3x−2 and DE=13. Find x.", ["3", "5", "11", "13"], "5", "The first two vertices correspond, so AB=DE.", "3x−2=13 gives 3x=15 and x=5. Both corresponding sides then measure 13.", "Confusing the unknown variable with its corresponding side length."),
      choice(2, "congruence-corresponding-equation", "procedure", "△PQR≅△STU. QR=2x+5 and TU=19. What is x?", ["7", "12", "14", "19"], "7", "Q↔T and R↔U, so QR and TU are matching sides.", "The equality 2x+5=19 gives 2x=14, so x=7.", "Matching sides by their visual placement instead of the stated vertex order."),
      table(3, "congruence-sas-measurements", "Triangle ABC has AB=5, AC=7, and included angle A=60°. Which candidate triangle DEF is congruent to it by SAS with A↔D?", ["DE", "DF", "Included angle D"], [["5", "7", "60°"], ["5", "7", "40°"], ["10", "14", "60°"], ["5", "8", "60°"]], 0, "Both corresponding sides and the angle between them must match.", "The first record matches sides 5 and 7 and their included angle 60°. The doubled sides in the third row describe a similar but larger triangle.", "Accepting proportional sides as sufficient for congruence."),
      table(4, "congruence-sas-measurements", "Triangle PQR has QP=6, QR=9, and included angle Q=50°. Which triangle TUV matches by SAS with Q↔U?", ["UT", "UV", "Included angle U"], [["6", "9", "70°"], ["12", "18", "50°"], ["6", "9", "50°"], ["6", "8", "50°"]], 2, "Use the angle where the two listed sides meet.", "UT=6, UV=9, and angle U=50° match all three SAS measurements. The other records alter a side, the included angle, or both side lengths.", "Checking the included angle without checking both side lengths."),
      choice(5, "congruence-aaa-counterexample", "reasoning", "One triangle has sides 3,4,5; another has sides 6,8,10. Their corresponding angles are equal. Why does this not prove congruence?", ["AAA proves every pair of triangles congruent.", "The scale factor is 2, so corresponding sides differ even though the triangles are similar.", "The second set cannot form a triangle.", "Equal angles force all sides within each triangle to be equal."], "The scale factor is 2, so corresponding sides differ even though the triangles are similar.", "Congruence requires equal size as well as equal shape.", "All second-triangle sides are twice the first triangle's sides. Scaling preserves angles but changes lengths, giving a counterexample to AAA as a congruence test.", "Treating equal shape as equal shape and size."),
      choice(6, "congruence-aaa-counterexample", "reasoning", "Triangles with sides 5,5,6 and 10,10,12 have equal corresponding angles. Which conclusion is correct?", ["They are congruent because both are isosceles.", "They cannot be similar because their lengths differ.", "They are similar with scale factor 2, but they are not congruent.", "The shared angle measures imply a scale factor of 1."], "They are similar with scale factor 2, but they are not congruent.", "Compare each corresponding side ratio and distinguish similarity from congruence.", "The ratios 10/5,10/5,12/6 all equal 2. The triangles have the same shape but different side lengths, so they are not congruent.", "Assuming the same special-triangle classification determines size."),
    ],
    remainingGaps: ["Building ASA/AAS/HL proofs from diagrams, analyzing SSA ambiguity, and student-authored congruence arguments.", "Using triangle congruence to derive new quadrilateral or circle properties."],
  },
  {
    lessonSlug: "g10-coordinate-proofs",
    objectives: [
      { id: "coordinate-fourth-vertex", description: "Calculate the fourth consecutive vertex of a parallelogram using matching displacements.", requiredDemands: ["procedure"] },
      { id: "coordinate-perpendicular-records", description: "Use run-and-rise records to identify perpendicular adjacent sides of a parallelogram.", requiredDemands: ["representation"] },
      { id: "coordinate-diagonal-counterexample", description: "Check coordinate evidence showing that equal diagonals alone do not prove a rectangle.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "For consecutive parallelogram vertices A=(0,1), B=(4,2), C=(6,5), the fourth vertex is D=A+C−B=(2,4).",
    exampleSteps: ["The displacement from B to C is (6−4,5−2)=(2,3).", "Opposite sides of a parallelogram have matching displacements, so D=A+(2,3).", "Add coordinates to get D=(2,4).", "Check the other pair: C−D=(4,1)=B−A, establishing both pairs of parallel equal sides."],
    questions: [
      choice(1, "coordinate-fourth-vertex", "procedure", "A=(1,2), B=(5,3), and C=(7,7) are consecutive vertices of parallelogram ABCD. Find D.", ["(3,6)", "(11,8)", "(4,4)", "(−1,−2)"], "(3,6)", "Move from A by the same displacement as B to C.", "C−B=(2,4), so D=(1,2)+(2,4)=(3,6). Equivalently D=A+C−B.", "Adding consecutive edge vectors to the wrong starting vertex."),
      choice(2, "coordinate-fourth-vertex", "procedure", "For consecutive parallelogram vertices A=(−2,1), B=(3,2), C=(4,6), determine D.", ["(5,10)", "(−1,5)", "(1,7)", "(−3,−3)"], "(−1,5)", "The displacement B→C is (1,4). Apply it at A.", "D=A+(C−B)=(−2,1)+(1,4)=(−1,5). The opposite displacement D→C=(5,1) matches A→B.", "Using C−A rather than the matching opposite-side displacement."),
      table(3, "coordinate-perpendicular-records", "Each row lists adjacent side displacements of a nondegenerate parallelogram. Which record proves the parallelogram is a rectangle?", ["Run AB", "Rise AB", "Run BC", "Rise BC"], [["2", "1", "1", "3"], ["2", "1", "−2", "4"], ["2", "1", "3", "−1"], ["2", "1", "−1", "1"]], 1, "Find both slopes as rise/run and check whether their product is −1.", "In the second row, the slopes are 1/2 and 4/(−2)=−2. Their product is −1, giving a right angle; a parallelogram with one right angle is a rectangle.", "Using equal slopes to claim a right angle."),
      table(4, "coordinate-perpendicular-records", "Which adjacent-side record establishes a right angle and therefore makes the stated parallelogram a rectangle?", ["First run", "First rise", "Second run", "Second rise"], [["3", "−2", "1", "3"], ["3", "−2", "−2", "3"], ["3", "−2", "2", "−3"], ["3", "−2", "2", "3"]], 3, "The first slope is −2/3, so its negative reciprocal is 3/2.", "The last row supplies second slope 3/2. Multiplying by −2/3 gives −1, which proves adjacent sides are perpendicular.", "Changing a slope's sign without also taking its reciprocal."),
      choice(5, "coordinate-diagonal-counterexample", "reasoning", "Quadrilateral ABCD has A=(−3,0), B=(3,0), C=(2,2), D=(−2,2). Both diagonals have squared length 29. Does that alone make it a rectangle?", ["Yes, every quadrilateral with equal diagonals is a rectangle.", "No: the nonparallel side slopes are BC=−2 and AD=2, so this is a counterexample.", "Yes, because all four sides have length 6.", "No, because a rectangle cannot have diagonal squared length 29."], "No: the nonparallel side slopes are BC=−2 and AD=2, so this is a counterexample.", "Check the second pair of opposite sides, not just the diagonals.", "AC and BD have squared lengths 5²+2²=29. But BC has slope −2 while AD has slope 2, so they are not parallel. This is an isosceles trapezoid, showing that equal diagonals alone are insufficient.", "Applying a rectangle theorem without its parallelogram hypothesis."),
      choice(6, "coordinate-diagonal-counterexample", "reasoning", "A=(−4,0), B=(4,0), C=(2,3), D=(−2,3). Both diagonals have squared length 45. Which evaluation of a proposed rectangle proof is correct?", ["The proof is complete because the diagonals are equal.", "The proof is complete because AB and CD are horizontal.", "The proof fails: BC has slope −3/2 and AD has slope 3/2, so BC is not parallel to AD and the quadrilateral is not a parallelogram.", "The proof fails only because the coordinates contain negative numbers."], "The proof fails: BC has slope −3/2 and AD has slope 3/2, so BC is not parallel to AD and the quadrilateral is not a parallelogram.", "A rectangle must have two pairs of parallel opposite sides.", "The equal diagonals both have squared length 6²+3²=45, but the legs' slopes differ. The quadrilateral is not a parallelogram and therefore cannot be a rectangle.", "Treating one parallel side pair plus equal diagonals as sufficient for a rectangle."),
    ],
    remainingGaps: ["General coordinate proofs with variables, vertical-side slope cases, and sufficient conditions for squares and rhombi.", "Choosing coordinates strategically to simplify a proof."],
  },
  {
    lessonSlug: "g10-circle-theorem-proofs",
    objectives: [
      { id: "circle-tangent-length", description: "Use the radius–tangent right angle to calculate an external tangent length.", requiredDemands: ["procedure"] },
      { id: "circle-angle-records", description: "Compare central and inscribed angle records that intercept the same minor arc.", requiredDemands: ["representation"] },
      { id: "circle-equal-tangents-proof", description: "Complete an equal-tangents proof using radii, a shared hypotenuse, and HL congruence.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "A circle has center O and radius 8. From an external point P with OP=17, tangent PT has length 15.",
    exampleSteps: ["OT joins the center to the point of tangency, so OT is perpendicular to PT.", "Triangle OTP is right, with hypotenuse OP=17 and leg OT=8.", "Pythagoras gives PT²=17²−8²=289−64=225.", "The length is positive, so PT=15. Substituting 8²+15²=17² verifies the result."],
    questions: [
      choice(1, "circle-tangent-length", "procedure", "PT is tangent to a circle at T. The center O satisfies OT=5 and OP=13. Find PT.", ["8", "12", "18", "144"], "12", "The radius is perpendicular to the tangent, making OP the hypotenuse.", "PT²=13²−5²=169−25=144, so PT=12.", "Subtracting lengths directly or forgetting to take the square root."),
      choice(2, "circle-tangent-length", "procedure", "A tangent QT meets a circle at T. With center O, OT=7 and OQ=25. What is QT?", ["18", "24", "32", "576"], "24", "Use the right triangle whose hypotenuse joins the external point to the center.", "QT²=25²−7²=625−49=576. The tangent length is √576=24.", "Treating the radius rather than the center-to-external distance as the hypotenuse."),
      table(3, "circle-angle-records", "In each candidate record, a central angle and an inscribed angle intercept the same minor arc. Which record is geometrically possible?", ["Central angle", "Inscribed angle"], [["110°", "55°"], ["120°", "120°"], ["80°", "160°"], ["60°", "45°"]], 0, "The inscribed angle is half the central angle for the same intercepted arc.", "Only 55° is half of its listed central angle 110°. The other pairs violate the central–inscribed angle relationship.", "Equating central and inscribed angles subtending the same arc."),
      table(4, "circle-angle-records", "Which central/inscribed angle record can intercept the same minor arc of one circle?", ["Central angle", "Inscribed angle"], [["70°", "40°"], ["90°", "50°"], ["140°", "70°"], ["120°", "80°"]], 2, "Double each inscribed angle and compare it with the central angle.", "The third row satisfies 2·70°=140°. All remaining records have an inscribed angle different from half the central angle.", "Confusing the full intercepted arc with the angle measured at the circumference."),
      choice(5, "circle-equal-tangents-proof", "reasoning", "PA and PB are tangents from external P to a circle centered at O. OA⊥PA, OB⊥PB, and OA=OB. Which step proves PA=PB without assuming it?", ["Assume PA=PB and then use SSS.", "Use OP=OP as a shared hypotenuse, prove the right triangles congruent by HL, then match PA and PB.", "Use only the fact that both tangent lines pass through P.", "Conclude the tangent lengths equal the radius."], "Use OP=OP as a shared hypotenuse, prove the right triangles congruent by HL, then match PA and PB.", "The triangles OAP and OBP are right; identify the common side opposite their right angles.", "The right triangles share hypotenuse OP and have equal radius legs OA and OB. HL proves congruence, after which corresponding tangent sides PA and PB are equal.", "Using the desired equal-tangent conclusion as a premise."),
      choice(6, "circle-equal-tangents-proof", "reasoning", "External Q has tangents QT and QU to a circle with center C. CT=CU and the tangent-radius angles are right. What completes a valid proof that QT=QU?", ["CQ is common, so HL establishes △CTQ≅△CUQ and corresponding tangent sides are equal.", "CT=CU alone proves every side of both triangles is equal.", "The two tangent lines are parallel, so their lengths are equal.", "The conclusion follows because Q lies on the circle."], "CQ is common, so HL establishes △CTQ≅△CUQ and corresponding tangent sides are equal.", "Find the common hypotenuse of the two right triangles.", "CQ is the hypotenuse in both right triangles. Together with CT=CU, this gives HL congruence; corresponding sides QT and QU are therefore equal.", "Mistaking an external common point for a point on the circle or treating tangents as parallel."),
    ],
    remainingGaps: ["Proving the inscribed-angle theorem itself, intersecting chord/secant relationships, and cyclic quadrilateral proofs.", "Diagram construction and choosing auxiliary radii in unfamiliar configurations."],
  },
  {
    lessonSlug: "g10-modeling-with-geometry",
    objectives: [
      { id: "geometry-composite-volume", description: "Calculate a cylinder-plus-hemisphere volume without counting the shared interface twice.", requiredDemands: ["procedure"] },
      { id: "geometry-capacity-records", description: "Convert internal rectangular-container dimensions from cubic centimeters to liters.", requiredDemands: ["representation"] },
      { id: "geometry-radius-sensitivity", description: "Explain the squared effect of a radius change on cylindrical volume when height stays fixed.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "Model a capsule as a cylinder of radius 3 and height 2, topped by one hemisphere of radius 3. The volume is 18π+18π=36π cubic units.",
    exampleSteps: ["The cylinder contributes πr²h=π·3²·2=18π.", "A hemisphere contributes half a sphere: (2/3)πr³=(2/3)π·27=18π.", "The two interiors do not overlap; add the volumes to get 36π cubic units.", "The model uses one hemisphere and the cylinder's own height; it does not treat the cap as a whole sphere or extend the cylinder through it."],
    questions: [
      choice(1, "geometry-composite-volume", "procedure", "A model joins a cylinder of radius 3 and height 4 to one hemisphere of radius 3. Their interiors do not overlap. What is the total volume?", ["36π", "54π", "72π", "90π"], "54π", "Add the cylinder volume to half of the sphere volume.", "The cylinder volume is π·9·4=36π and the hemisphere volume is (2/3)π·27=18π. Total volume is 54π cubic units.", "Counting a full sphere instead of one hemisphere."),
      choice(2, "geometry-composite-volume", "procedure", "A cylinder has radius 6 and height 2, with one radius-6 hemisphere attached without overlapping interiors. Find the volume.", ["72π", "144π", "216π", "288π"], "216π", "The hemisphere formula is (2/3)πr³, while the cylinder uses πr²h.", "Cylinder volume is 72π. Hemisphere volume is (2/3)π·216=144π, so the total is 216π cubic units.", "Applying a squared-radius formula to the spherical cap."),
      table(3, "geometry-capacity-records", "All listed dimensions are internal centimeters. Ignoring wall thickness, which rectangular container holds exactly 3 liters? Use 1 liter=1000 cm³.", ["Length", "Width", "Height"], [["10", "10", "20"], ["20", "10", "20"], ["20", "15", "10"], ["15", "10", "10"]], 2, "Multiply the three dimensions before converting cubic centimeters to liters.", "The capacities are 2000,4000,3000,1500 cm³, or 2,4,3,1.5 liters. Only the third row gives exactly 3 liters.", "Adding dimensions or converting linear centimeters as though they were volume units."),
      table(4, "geometry-capacity-records", "Which container has an internal capacity of exactly 6 liters? All three dimensions are in centimeters; use 1000 cm³ per liter.", ["Length", "Width", "Height"], [["20", "20", "15"], ["30", "10", "10"], ["25", "20", "10"], ["20", "20", "20"]], 0, "Compute each product and compare it with 6000 cm³.", "The first product is 20·20·15=6000 cm³=6 liters. The other rows hold 3,5, and 8 liters respectively.", "Comparing a dimension total to a target capacity."),
      choice(5, "geometry-radius-sensitivity", "reasoning", "A cylindrical model keeps its height fixed while increasing its radius by 10%. Which volume prediction is correct?", ["Volume increases by 10% because one measurement changes.", "Volume increases by 20% exactly because there are two radius factors.", "Volume increases by 21% because its factor is 1.10²=1.21.", "Volume increases by 33.1% because its factor is 1.10³."], "Volume increases by 21% because its factor is 1.10²=1.21.", "In πr²h only r changes, and its multiplier is squared.", "Vnew/Vold=(1.10r)²/r²=1.21 with height unchanged. The increase is 1.21−1=0.21, or 21%.", "Applying linear or full three-dimensional scaling when only radius changes."),
      choice(6, "geometry-radius-sensitivity", "reasoning", "A tank model uses a radius 20% larger than before and the same height. How does its modeled cylindrical volume change?", ["It increases by 20%.", "It increases by 40% exactly.", "It increases by 72.8%.", "It increases by 44%, since 1.20²=1.44."], "It increases by 44%, since 1.20²=1.44.", "Square the radius multiplier 1.20, then subtract 1 to find the proportional increase.", "The fixed height cancels in the volume ratio, leaving 1.2²=1.44. Thus the model's volume is 44% larger.", "Doubling a percentage change instead of squaring its scale factor."),
    ],
    remainingGaps: ["Surface-area/material estimates, packing inefficiency, measurement uncertainty, and selecting a model from real images.", "Geometric optimization under cost or capacity constraints."],
  },
  {
    lessonSlug: "g11-polynomial-roots",
    objectives: [
      { id: "polynomial-root-parameter", description: "Use a specified zero to determine an unknown coefficient by substitution.", requiredDemands: ["procedure"] },
      { id: "polynomial-factor-records", description: "Match factored-polynomial records to required root signs and multiplicities.", requiredDemands: ["representation"] },
      { id: "polynomial-conjugate-factor", description: "Derive the real quadratic factor forced by a nonreal zero of a real-coefficient polynomial.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "If 3 is a zero of P(x)=x³+kx−9, then 27+3k−9=0, so k=−6.",
    exampleSteps: ["A zero at x=3 means P(3)=0.", "Substitute: 3³+3k−9=0, giving 18+3k=0.", "Solve 3k=−18 to obtain k=−6.", "Check P(3)=27−18−9=0; by the factor theorem, x−3 is a factor."],
    questions: [
      choice(1, "polynomial-root-parameter", "procedure", "The polynomial P(x)=x³+kx−6 has zero x=2. Find k.", ["−7", "−1", "1", "7"], "−1", "Set P(2)=0 before solving for the coefficient.", "8+2k−6=0 gives 2+2k=0, so k=−1. Substitution confirms 8−2−6=0.", "Setting the input equal to the coefficient instead of setting the polynomial's value to zero."),
      choice(2, "polynomial-root-parameter", "procedure", "Q(x)=x³+kx+10 has zero x=−2. Determine k.", ["−9", "−1", "1", "9"], "1", "Preserve the sign of (−2)³ and of k(−2).", "Q(−2)=−8−2k+10=0, so 2−2k=0 and k=1.", "Losing the negative sign when substituting a negative zero."),
      table(3, "polynomial-factor-records", "Each candidate is the product of the two listed factors. Which polynomial has root −2 of multiplicity 2 and root 5 of multiplicity 1?", ["First factor", "Second factor"], [["(x−2)²", "(x+5)"], ["(x+2)", "(x−5)²"], ["(x+2)²", "(x−5)"], ["(x+2)²", "(x+5)"]], 2, "A root r contributes factor x−r; the exponent records its multiplicity.", "The required factors are (x−(−2))²=(x+2)² and x−5. Only the third row matches both signs and exponents.", "Reading the sign inside a factor as the sign of its zero."),
      table(4, "polynomial-factor-records", "Select the factor record with zero 3 twice and zero −1 once, and no other zeros.", ["First factor", "Second factor"], [["(x−3)²", "(x+1)"], ["(x+3)²", "(x−1)"], ["(x−3)", "(x+1)²"], ["(x−3)²", "(x−1)"]], 0, "A double zero at 3 requires (x−3)², while the simple zero −1 requires x+1.", "The first record has degree 3 with two factors vanishing at 3 and one at −1. The other records reverse a sign or a multiplicity.", "Confusing the number of distinct zeros with the sum of multiplicities."),
      choice(5, "polynomial-conjugate-factor", "reasoning", "A polynomial has real coefficients and zero 1+2i. Which real quadratic factor must divide it?", ["x²−2x+5", "x²−2x−3", "x²+2x+5", "x²−4x+1"], "x²−2x+5", "The conjugate 1−2i is also a zero; multiply the two corresponding linear factors.", "The pair contributes (x−1−2i)(x−1+2i)=(x−1)²+4=x²−2x+5. Real coefficients are essential to the conjugate-root conclusion.", "Using i²=1 instead of −1 or omitting the conjugate root."),
      choice(6, "polynomial-conjugate-factor", "reasoning", "A real-coefficient polynomial has zero 3−i. What real quadratic factor is forced by this information?", ["x²−6x+8", "x²+6x+10", "x²−3x+1", "x²−6x+10"], "x²−6x+10", "Include the conjugate zero 3+i, then multiply the factors as a difference of squares.", "(x−3+i)(x−3−i)=(x−3)²+1=x²−6x+10, which must be a factor of the polynomial.", "Forgetting that the imaginary parts contribute a positive constant after multiplication."),
    ],
    remainingGaps: ["Rational-root candidates, synthetic division, graph crossing/touching behavior, and numerical root location.", "Higher-degree root counts with nonreal roots and repeated factors."],
  },
  {
    lessonSlug: "g11-infinite-geometric-series",
    objectives: [
      { id: "geometric-signed-sum", description: "Identify a geometric ratio, including a negative one, and calculate the convergent infinite sum.", requiredDemands: ["procedure"] },
      { id: "geometric-parameter-records", description: "Compare first-term and ratio records against both convergence and a target sum.", requiredDemands: ["representation"] },
      { id: "geometric-bounce-distance", description: "Model an ideal infinite bounce distance with one initial drop and paired rebound journeys.", requiredDemands: ["application"] },
    ],
    legacyObjectives: { q1: "geometric-signed-sum", q3: "geometric-signed-sum", q5: "geometric-signed-sum" },
    example: "The series 9+9/4+9/16+… has ratio 1/4 and sum 9/(1−1/4)=12.",
    exampleSteps: ["Divide a term by its predecessor: (9/4)/9=1/4.", "The ratio has magnitude below 1, so the infinite geometric sum exists.", "Use S=a/(1−r)=9/(3/4)=12.", "The sum exceeds the first positive term 9, while the successive terms shrink toward zero."],
    questions: [
      choice(1, "geometric-signed-sum", "procedure", "Find the infinite sum 12−6+3−1.5+… .", ["6", "8", "18", "24"], "8", "The ratio is −1/2, so the denominator 1−r is 1+1/2.", "The series converges because the ratio magnitude is 1/2<1. Its sum is 12/(1−(−1/2))=12/(3/2)=8.", "Ignoring the sign of the common ratio in the sum formula."),
      choice(2, "geometric-signed-sum", "procedure", "Evaluate 15+5+5/3+5/9+… as an infinite geometric sum.", ["20", "22.5", "30", "45"], "22.5", "The first term is 15 and the ratio is 1/3.", "The ratio 1/3 gives convergence. S=15/(1−1/3)=15/(2/3)=22.5.", "Using the second term as the first term or dividing by the ratio rather than 1 minus the ratio."),
      table(3, "geometric-parameter-records", "Which first-term/ratio record defines a convergent geometric series with sum exactly 4?", ["First term a", "Common ratio r"], [["6", "−0.5"], ["4", "2"], ["2", "0.25"], ["3", "0.5"]], 0, "First reject ratio magnitudes at least 1, then evaluate a/(1−r).", "The first row gives 6/1.5=4. The second diverges, while the third and fourth sum to 8/3 and 6.", "Applying the sum formula to a divergent ratio."),
      table(4, "geometric-parameter-records", "Which record gives a convergent infinite geometric sum of 10?", ["First term", "Ratio"], [["5", "0.2"], ["10", "1"], ["2", "0.5"], ["8", "0.2"]], 3, "A ratio of 1 does not converge for a nonzero first term.", "The last row gives 8/(1−0.2)=8/0.8=10. The other finite sums are 6.25 and 4; the ratio-1 series diverges.", "Assuming a first term equal to the target automatically gives that infinite sum."),
      choice(5, "geometric-bounce-distance", "application", "In an ideal model, a ball drops 10 meters and rebounds to half its previous height forever. Count the initial drop and every upward/downward bounce. What is the total distance?", ["20 meters", "25 meters", "30 meters", "40 meters"], "30 meters", "The 10-meter initial drop occurs once; every later rebound height is traveled both up and down.", "The rebound heights sum to 5/(1−1/2)=10 meters. Total travel is 10+2·10=30 meters.", "Counting each rebound only once or doubling the initial drop."),
      choice(6, "geometric-bounce-distance", "application", "A ball initially falls 12 meters and then rebounds to one quarter of each previous height, indefinitely in the ideal model. Find its total travel distance.", ["16 meters", "20 meters", "24 meters", "32 meters"], "20 meters", "The first rebound is 3 meters, and all rebound heights form a ratio-1/4 series.", "The rebound-height sum is 3/(1−1/4)=4 meters. Adding two journeys for each rebound gives 12+2·4=20 meters.", "Using the initial height as a rebound that should be counted twice."),
    ],
    remainingGaps: ["Finite partial sums and error targets, repeating-decimal conversions, and models with nonconstant ratios.", "Explaining how finite observations support or fail to support an infinite-process model."],
  },
  {
    lessonSlug: "g11-radians-unit-circle",
    objectives: [
      { id: "radians-arc-length", description: "Calculate arc length from radius and a radian angle.", requiredDemands: ["procedure"] },
      { id: "radians-coordinate-records", description: "Match a radian angle to its signed unit-circle coordinate record.", requiredDemands: ["representation"] },
      { id: "radians-coterminal-justification", description: "Reduce positive or negative angles by complete turns while preserving their unit-circle point.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "On a radius-5 circle, an angle of 2π/3 radians cuts an arc of length 5·2π/3=10π/3.",
    exampleSteps: ["The angle is already measured in radians, so the arc-length formula is s=rθ.", "Substitute r=5 and θ=2π/3.", "Multiply to obtain s=10π/3 length units.", "The angle is one third of a full turn, and the arc is one third of circumference 10π, confirming the result."],
    questions: [
      choice(1, "radians-arc-length", "procedure", "A circle has radius 6. Find the arc length cut by an angle of 5π/6 radians.", ["5π", "6π", "10π", "30π"], "5π", "Multiply radius by radian measure; no degree conversion is needed.", "s=rθ=6·5π/6=5π length units.", "Using a degree-based proportion without recognizing that the angle is already in radians."),
      choice(2, "radians-arc-length", "procedure", "For radius 8 and central angle 3π/4 radians, calculate the corresponding arc length.", ["3π", "4π", "6π", "24π"], "6π", "Use s=8·3π/4 and cancel the factor 4.", "The arc length is 8·3π/4=6π, which is 3/8 of the full circumference 16π.", "Confusing the angle fraction of π with its fraction of a complete 2π turn."),
      table(3, "radians-coordinate-records", "Which unit-circle coordinate record corresponds to θ=5π/6?", ["x=cosθ", "y=sinθ"], [["√3/2", "1/2"], ["−√3/2", "1/2"], ["−√3/2", "−1/2"], ["1/2", "√3/2"]], 1, "5π/6 lies in quadrant II with reference angle π/6.", "The reference coordinates have cosine magnitude √3/2 and sine magnitude 1/2. Quadrant II makes x negative and y positive, giving (−√3/2,1/2).", "Swapping sine and cosine coordinates or missing the quadrant sign."),
      table(4, "radians-coordinate-records", "Select the unit-circle point at θ=7π/4.", ["Cosine coordinate", "Sine coordinate"], [["√2/2", "√2/2"], ["−√2/2", "√2/2"], ["−√2/2", "−√2/2"], ["√2/2", "−√2/2"]], 3, "The reference angle is π/4 and the point lies in quadrant IV.", "Both coordinate magnitudes are √2/2. Quadrant IV has positive cosine and negative sine, so the last row is correct.", "Using the reference-angle point without placing it in the correct quadrant."),
      choice(5, "radians-coterminal-justification", "reasoning", "Which reduction of 13π/6 preserves its unit-circle point and produces an angle in [0,2π)?", ["Subtract π to obtain 7π/6, because a half turn preserves the point.", "Subtract 2π to obtain π/6, because a full turn preserves the point.", "Divide by 2 to obtain 13π/12, because angles are periodic under halving.", "Subtract 13π/6 to obtain 0, because every positive angle starts at 0."], "Subtract 2π to obtain π/6, because a full turn preserves the point.", "A complete rotation is 2π radians, not π.", "13π/6−12π/6=π/6. Subtracting a full turn leaves the terminal ray unchanged; subtracting only π would move to the opposite point.", "Confusing half-turn symmetry with coterminal angles."),
      choice(6, "radians-coterminal-justification", "reasoning", "Find the coterminal representative of −5π/4 in [0,2π) and choose its justification.", ["5π/4, by removing the minus sign.", "π/4, by adding π.", "3π/4, by adding one full turn 2π.", "7π/4, because all negative angles lie in quadrant IV."], "3π/4, by adding one full turn 2π.", "Add 8π/4 to the negative angle.", "−5π/4+8π/4=3π/4, which lies in the required interval and has the same terminal ray. Simply changing the sign changes the point.", "Interpreting a negative angle as a permanently fourth-quadrant angle."),
    ],
    remainingGaps: ["Angular and linear speed, sector areas, arbitrary-angle coordinates, and dynamic rotation interaction.", "Linking coterminal angles to graph periodicity and inverse-trigonometric principal ranges."],
  },
  {
    lessonSlug: "g11-matrix-systems",
    objectives: [
      { id: "matrix-system-solve-pair", description: "Solve both coordinates of a nonsingular two-equation linear system.", requiredDemands: ["procedure"] },
      { id: "matrix-system-augmented-records", description: "Translate equations into ordered coefficient-and-constant row records.", requiredDemands: ["representation"] },
      { id: "matrix-system-singular-classification", description: "Use augmented-row elimination to distinguish inconsistent and infinitely-many-solution singular systems.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: { q1: "matrix-system-solve-pair", q2: "matrix-system-solve-pair" },
    example: "The system x+y=8 and x−y=2 has solution (x,y)=(5,3). Adding the two coefficient rows eliminates y.",
    exampleSteps: ["Write the augmented rows [1,1,8] and [1,−1,2] in variable order x,y.", "Add the equations: 2x=10, so x=5.", "Substitute into x+y=8 to obtain y=3.", "Check both original equations: 5+3=8 and 5−3=2."],
    questions: [
      choice(1, "matrix-system-solve-pair", "procedure", "Solve 2x+y=11 and x−y=1. Give (x,y).", ["(3,4)", "(4,3)", "(5,1)", "(6,−1)"], "(4,3)", "Add the equations to eliminate y.", "Adding gives 3x=12, so x=4. From x−y=1, y=3. Both equations hold for (4,3).", "Finding one variable but interchanging the final coordinate order."),
      choice(2, "matrix-system-solve-pair", "procedure", "Find (x,y) satisfying 3x−y=7 and x+y=5.", ["(2,3)", "(4,1)", "(3,2)", "(1,4)"], "(3,2)", "Adding cancels the opposite y coefficients.", "The sum is 4x=12, giving x=3; then y=5−3=2. Substitution gives 9−2=7.", "Adding the constants correctly but failing to add both x coefficients."),
      table(3, "matrix-system-augmented-records", "Represent 2x−3y=7 followed by 4x+y=5. Each row record is [x coefficient,y coefficient,constant]. Which candidate preserves that equation order?", ["First equation row", "Second equation row"], [["[2,−3,7]", "[4,1,5]"], ["[2,3,7]", "[4,1,5]"], ["[2,−3,5]", "[4,1,7]"], ["[−3,2,7]", "[1,4,5]"]], 0, "Keep variable order x,y and retain the negative coefficient of y.", "The first equation gives [2,−3,7] and the second [4,1,5]. The other candidates change a sign, swap constants, or change the variable-column order.", "Treating the augmented constant column as another variable coefficient."),
      table(4, "matrix-system-augmented-records", "For 3x+2y=8 followed by −x+5y=4, choose the augmented-row representation in x,y order.", ["First equation row", "Second equation row"], [["[3,2,4]", "[−1,5,8]"], ["[3,2,8]", "[1,5,4]"], ["[2,3,8]", "[5,−1,4]"], ["[3,2,8]", "[−1,5,4]"]], 3, "The implicit coefficient in −x is −1.", "The rows are [3,2,8] and [−1,5,4]. Each final entry is its own equation's right-hand side.", "Dropping the implicit negative coefficient of a lone variable."),
      choice(5, "matrix-system-singular-classification", "reasoning", "The system is 2x+4y=6 and x+2y=3. Its coefficient determinant is zero. What does elimination show?", ["Exactly one solution, because there are two equations.", "No solution, because every zero determinant means inconsistency.", "Infinitely many solutions: subtracting twice the second equation from the first gives 0=0.", "Only x=y=0, because the eliminated row is zero."], "Infinitely many solutions: subtracting twice the second equation from the first gives 0=0.", "Compare the right-hand sides as well as the proportional coefficient rows.", "Both equations describe x+2y=3. Elimination gives the identity 0=0, leaving one independent equation in two unknowns and infinitely many solutions.", "Assuming a singular coefficient matrix always means no solution."),
      choice(6, "matrix-system-singular-classification", "reasoning", "Consider 2x+4y=8 and x+2y=3. The coefficient determinant is zero. Which conclusion follows from subtracting twice the second equation from the first?", ["No solution, because the resulting statement is 0=2.", "Infinitely many solutions, because both coefficient rows are proportional.", "One solution (2,1), because it satisfies the first equation.", "One solution (1,1), because it satisfies the second equation."], "No solution, because the resulting statement is 0=2.", "The left sides cancel, but check whether the constants cancel too.", "The elimination gives 0=8−2·3=2, an impossible equality. Thus no pair satisfies both equations despite proportional coefficient rows.", "Ignoring the augmented constants when classifying a singular system."),
    ],
    remainingGaps: ["Inverse-matrix and row-reduction methods, three-variable systems, and rank-based classifications.", "Building matrix systems from constraints and analyzing sensitivity to coefficient changes."],
  },
  {
    lessonSlug: "g12-limit-from-table-graph",
    objectives: [
      { id: "limit-nearby-output", description: "Evaluate a punctured function at nearby inputs to build numerical limit evidence.", requiredDemands: ["procedure"] },
      { id: "limit-two-sided-records", description: "Compare nearby-output records from both sides to select a supported finite-limit estimate.", requiredDemands: ["representation"] },
      { id: "limit-isolated-value", description: "Distinguish exact nearby behavior from an isolated function value when determining a limit.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "For f(x)=(x²−16)/(x−4), x≠4, f(3.9)=7.9 and f(4.1)=8.1. The nearby rule f(x)=x+4 proves the limit at 4 is 8 even though f(4) is undefined.",
    exampleSteps: ["Factor x²−16=(x−4)(x+4).", "For x≠4, cancel the common factor to obtain the nearby rule f(x)=x+4.", "Evaluate the nearby inputs: f(3.9)=7.9 and f(4.1)=8.1.", "The rule x+4 approaches 8 as x approaches 4. The rule proves the limit; the finite numerical samples provide supporting evidence."],
    questions: [
      choice(1, "limit-nearby-output", "procedure", "To build a limit table, evaluate f(x)=(x²−4)/(x−2) at x=1.9. Give the exact decimal value.", ["−0.1", "0", "3.9", "4.1"], "3.9", "For this allowed input, factor the numerator and simplify to x+2.", "Since 1.9≠2, the quotient equals x+2. Therefore f(1.9)=3.9; the original expression is defined at this nearby input.", "Using the excluded central input instead of the requested nearby input."),
      choice(2, "limit-nearby-output", "procedure", "For g(x)=(x²−9)/(x−3), calculate g(2.99) to supply a nearby-output table.", ["−0.01", "0", "5.99", "6.01"], "5.99", "Cancel x−3 for x≠3, giving the nearby rule x+3.", "At x=2.99 the denominator is nonzero, so g(2.99)=2.99+3=5.99.", "Mistaking a quotient near a removable hole for a value of zero."),
      table(3, "limit-two-sided-records", "Each row is a different function's nearby-output record. Which record supports estimating a two-sided limit of 5 as x approaches a?", ["f(a−0.1)", "f(a−0.01)", "f(a+0.01)", "f(a+0.1)"], [["4.9", "4.99", "5.01", "5.1"], ["2.9", "2.99", "5.01", "5.1"], ["9", "99", "99", "9"], ["0.1", "0.01", "0.01", "0.1"]], 0, "Compare the nearest values from both sides with 5; neither side may be ignored.", "The first row has outputs close to 5 on both sides, with smaller deviations at nearer inputs. The other rows suggest unequal one-sided behavior, unbounded growth, or a limit near 0. Finite samples support an estimate but do not alone prove a limit.", "Inferring a two-sided limit from one side or treating finite samples as a proof."),
      table(4, "limit-two-sided-records", "Which nearby-output record supports an estimated two-sided limit of −2 at x=b?", ["g(b−0.1)", "g(b−0.01)", "g(b+0.01)", "g(b+0.1)"], [["0.9", "0.99", "−1.98", "−1.8"], ["−2.2", "−2.02", "−1.98", "−1.8"], ["2.2", "2.02", "1.98", "1.8"], ["−10", "−100", "100", "10"]], 1, "Outputs should approach the same negative value from the left and right.", "The second record gets closer to −2 from both directions. The other records suggest a jump, a positive limit near 2, or opposite unbounded behavior. The conclusion remains an estimate from the displayed samples.", "Ignoring signs when comparing negative nearby values."),
      choice(5, "limit-isolated-value", "reasoning", "f(x)=x+4 whenever 0<abs(x−1)<1, but f(1)=20. A student claims the limit as x→1 is 20. Which correction is valid?", ["The limit is 20 because a filled point always gives the limit.", "The limit is 5 because the nearby rule approaches 5; the isolated value 20 does not change it.", "The limit is 0 because the point value is different.", "No limit can exist if f(1) differs from nearby values."], "The limit is 5 because the nearby rule approaches 5; the isolated value 20 does not change it.", "A limit uses x near 1 while excluding x=1 itself.", "Every sufficiently near input other than 1 follows x+4, which approaches 5. Redefining f at the single point changes continuity there but not the limit.", "Replacing nearby behavior with the isolated function value."),
      choice(6, "limit-isolated-value", "reasoning", "g(x)=2x−1 for 0<abs(x−2)<0.5, and g(2)=−7. What determines the limit at 2?", ["g(2)=−7 forces the limit to be −7.", "The limit cannot exist because the point is redefined.", "The nearby rule gives limit 3, independently of the isolated value −7.", "The average of 3 and −7 gives the limit −2."], "The nearby rule gives limit 3, independently of the isolated value −7.", "Use 2x−1 at inputs arbitrarily close to 2, not the separately defined point value.", "As x approaches 2 through nearby inputs, 2x−1 approaches 3. The value g(2)=−7 does not affect that limiting behavior.", "Averaging a nearby limit and the point value instead of applying the limit definition."),
    ],
    remainingGaps: ["Actual graph features with open/closed points, unbounded and oscillating limits, and asymmetric one-sided approaches.", "Choosing enough numerical evidence to avoid misleading finite-table extrapolation."],
  },
  {
    lessonSlug: "g12-optimization",
    objectives: [
      { id: "optimization-three-side-fence", description: "Maximize a rectangle's area using a fixed fence length on three sides.", requiredDemands: ["procedure"] },
      { id: "optimization-candidate-table", description: "Compare a complete endpoint-and-critical-point table to locate an absolute extremum.", requiredDemands: ["representation"] },
      { id: "optimization-open-box", description: "Optimize an open box's cut size while respecting its geometric domain.", requiredDemands: ["application"] },
    ],
    legacyObjectives: {},
    example: "With 40 meters of fencing for three sides against a wall, width w and length l satisfy 2w+l=40. Maximum area is 200 m² at w=10 and l=20.",
    exampleSteps: ["Use the fence constraint to write l=40−2w, with 0<w<20.", "Area is A(w)=w(40−2w)=40w−2w².", "Differentiate: A′(w)=40−4w=0 gives w=10 and l=20.", "A″=−4<0 and the endpoint areas are 0, so this interior point gives the maximum 10·20=200 m²."],
    questions: [
      choice(1, "optimization-three-side-fence", "procedure", "A wall forms one side of a rectangle; 48 meters of fence cover the other three. What is the maximum area?", ["144 m²", "288 m²", "576 m²", "1152 m²"], "288 m²", "If w is perpendicular to the wall, the other fenced side is 48−2w.", "A(w)=48w−2w² has derivative 48−4w. Its maximum occurs at w=12 and l=24, giving area 288 m².", "Using a four-sided perimeter formula for a three-sided fence."),
      choice(2, "optimization-three-side-fence", "procedure", "Using a straight wall as the fourth side, enclose a rectangular pen with 80 meters of fence. Find its largest possible area.", ["400 m²", "800 m²", "1600 m²", "3200 m²"], "800 m²", "The two widths consume 2w meters, leaving 80−2w for the parallel side.", "A=80w−2w², so A′=80−4w=0 at w=20. Then l=40 and A=800 m²; the concave-down quadratic confirms the maximum.", "Assuming the optimal three-fenced-side rectangle must be a square."),
      table(3, "optimization-candidate-table", "For f(x)=x³−3x on [−2,3], the table contains both endpoints and all interior critical points. Which candidate is the absolute maximum?", ["x", "f′(x)", "f(x)"], [["−2", "9", "−2"], ["−1", "0", "2"], ["1", "0", "−2"], ["3", "24", "18"]], 3, "Compare function values at every listed candidate, including endpoints whose derivative is not zero.", "The largest listed value is 18 at x=3. Since the function is continuous and the candidate list is complete, this endpoint is the absolute maximum.", "Rejecting an endpoint because its derivative is nonzero."),
      table(4, "optimization-candidate-table", "The complete endpoint/critical-point table for g(x)=x³−12x on [−3,4] is below. Which candidate gives the absolute minimum?", ["x", "g′(x)", "g(x)"], [["−3", "15", "9"], ["−2", "0", "16"], ["2", "0", "−16"], ["4", "36", "16"]], 2, "Use the smallest function value, not the smallest input or derivative.", "The least candidate value is −16 at x=2. Both endpoints and both roots of g′=3x²−12 have been checked, so this is the absolute minimum.", "Selecting the leftmost input instead of minimizing the function's output."),
      choice(5, "optimization-open-box", "application", "Cut equal squares of side x from the corners of a 12-by-12 cm sheet and fold an open box. Its volume is V=x(12−2x)² for 0<x<6. Which cut maximizes volume?", ["x=2 cm, giving 128 cm³", "x=3 cm, giving 108 cm³", "x=6 cm, giving 0 cm³", "x=4 cm, giving 64 cm³"], "x=2 cm, giving 128 cm³", "Factor the derivative as V′=(12−2x)(12−6x) and retain a feasible interior critical point.", "The interior root is x=2; x=6 is a degenerate boundary. The volume rises before 2 and falls afterward within the domain, yielding V(2)=2·8²=128 cm³.", "Accepting a degenerate boundary cut or assuming half the side should be removed."),
      choice(6, "optimization-open-box", "application", "An 18-by-18 cm sheet makes an open box after corner squares of side x are removed. For V=x(18−2x)² and 0<x<9, choose the maximizing cut and volume.", ["x=4.5 cm, giving 364.5 cm³", "x=6 cm, giving 216 cm³", "x=9 cm, giving 0 cm³", "x=3 cm, giving 432 cm³"], "x=3 cm, giving 432 cm³", "The derivative factors as (18−2x)(18−6x).", "The only interior critical point is x=3, with V=3·12²=432 cm³. The derivative changes from positive to negative there, while volumes tend to 0 at both domain ends.", "Comparing a few plausible cuts without checking the derivative and feasible domain."),
    ],
    remainingGaps: ["Optimization with nonpolynomial objectives, multiple constraints, and discrete design choices.", "Sensitivity of an optimum to uncertain measurements and costs."],
  },
  {
    lessonSlug: "g12-fundamental-theorem",
    objectives: [
      { id: "ftc-variable-upper-bound", description: "Differentiate an accumulation function with a composite upper bound using FTC and the chain rule.", requiredDemands: ["procedure"] },
      { id: "ftc-endpoint-records", description: "Use antiderivative endpoint-value records to identify a definite integral.", requiredDemands: ["representation"] },
      { id: "ftc-integrand-sign-extremum", description: "Use a continuous integrand's sign change to justify a local extremum of its accumulation function.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "For F(x)=∫ from 0 to 2x of (t²+1) dt, F′(x)=((2x)²+1)·2, so F′(1)=10.",
    exampleSteps: ["The continuous integrand is t²+1 and the upper endpoint is u(x)=2x.", "FTC gives the integrand evaluated at the upper endpoint: (2x)²+1.", "The chain rule also multiplies by u′(x)=2.", "At x=1, F′(1)=(4+1)·2=10."],
    questions: [
      choice(1, "ftc-variable-upper-bound", "procedure", "F(x)=∫ from 0 to x² of (t³+1) dt. Calculate F′(2).", ["65", "130", "260", "1028"], "260", "Evaluate the integrand at x² and multiply by the derivative 2x.", "F′(x)=((x²)³+1)·2x=(x⁶+1)2x. At x=2, (64+1)·4=260.", "Forgetting the upper bound's derivative or substituting x directly for t."),
      choice(2, "ftc-variable-upper-bound", "procedure", "G(x)=∫ from 1 to 3x of (t²−2) dt. Find G′(1).", ["3", "7", "21", "27"], "21", "The constant lower bound contributes no derivative; the upper bound contributes a factor 3.", "G′(x)=((3x)²−2)·3. At x=1 this is (9−2)·3=21.", "Subtracting the integrand at the constant lower bound when differentiating the integral."),
      table(3, "ftc-endpoint-records", "Each row is a separate situation with F′=f. Which record gives ∫ from a to b of f(x) dx=6?", ["a", "b", "F(a)", "F(b)"], [["0", "2", "1", "7"], ["1", "3", "7", "1"], ["2", "4", "2", "10"], ["0", "4", "−1", "4"]], 0, "Use F(b)−F(a); do not divide by the interval width.", "The first row yields 7−1=6. The other differences are −6,8, and 5, respectively.", "Confusing a definite integral with its average value or reversing the endpoint order."),
      table(4, "ftc-endpoint-records", "In each separate record, H′=h. Which row implies ∫ from a to b of h(x) dx=−5?", ["a", "b", "H(a)", "H(b)"], [["0", "1", "3", "8"], ["1", "4", "8", "3"], ["2", "5", "−2", "3"], ["0", "2", "1", "−3"]], 1, "Subtract the antiderivative's starting value from its ending value, preserving the sign.", "The second row gives 3−8=−5. The other rows give 5,5, and −4, so only that row matches the target.", "Taking an absolute value of the antiderivative difference."),
      choice(5, "ftc-integrand-sign-extremum", "reasoning", "f is continuous, positive on (1,2), and negative on (2,3). For A(x)=∫₀ˣ f(t)dt, what follows at x=2?", ["A has a strict local maximum because A′=f changes from positive to negative.", "A has a local minimum because f decreases through zero.", "A(2)=0 because f(2)=0.", "A has its absolute maximum over all real numbers at 2."], "A has a strict local maximum because A′=f changes from positive to negative.", "FTC identifies f as the derivative of A, so use the first-derivative sign test.", "A increases to x=2 and decreases immediately afterward, giving a strict local maximum. The sign information does not determine A(2) or establish a global maximum outside this neighborhood.", "Confusing the integrand's zero with the accumulated integral's value."),
      choice(6, "ftc-integrand-sign-extremum", "reasoning", "A continuous g is negative on (3,4) and positive on (4,5). Let B(x)=∫₀ˣ g(t)dt. Which conclusion is justified?", ["B(4) must equal 0.", "B has a strict local maximum at 4.", "B has a strict local minimum at 4 because B′=g changes from negative to positive.", "B is decreasing on both sides of 4."], "B has a strict local minimum at 4 because B′=g changes from negative to positive.", "Translate the sign of g into decreasing/increasing behavior of B.", "FTC gives B′=g. Hence B decreases before 4 and increases after 4, so it has a strict local minimum there, regardless of the value accumulated before 3.", "Using the sign of the accumulation instead of the sign of its derivative."),
    ],
    remainingGaps: ["Both bounds varying, accumulation from graph areas, and differentiability hypotheses at discontinuous integrands.", "Global extrema and concavity of accumulation functions from integrand graphs."],
  },
  {
    lessonSlug: "g12-study-design",
    objectives: [
      { id: "study-block-allocation", description: "Calculate whole-number treatment allocations within blocks at a specified random-assignment ratio.", requiredDemands: ["procedure"] },
      { id: "study-protocol-comparison", description: "Compare concrete recruitment and assignment protocols for population and causal inference.", requiredDemands: ["representation"] },
      { id: "study-confounding-repair", description: "Identify a treatment-confounded factor and repair the design through randomized assignment within blocks.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "A study blocks 12 novices and 18 experienced participants, then randomly assigns half within each block to treatment. Treatment receives 6 novices and 9 experienced participants.",
    exampleSteps: ["Retain the two experience blocks so treatment comparisons occur within similar experience groups.", "A 1:1 treatment/control ratio sends half of each block to treatment.", "Calculate 12/2=6 novices and 18/2=9 experienced participants for treatment.", "Randomly select those participants within each block; control receives the remaining 6 and 9. Counts alone do not replace random assignment."],
    questions: [
      choice(1, "study-block-allocation", "procedure", "There are 18 novices and 30 experienced participants. Random assignment uses a treatment:control ratio of 2:1 within each block. How many novices and experienced participants go to treatment?", ["9 novices; 15 experienced", "12 novices; 20 experienced", "6 novices; 10 experienced", "18 novices; 30 experienced"], "12 novices; 20 experienced", "A 2:1 ratio puts 2 of every 3 participants in treatment within each block.", "Treatment receives (2/3)·18=12 novices and (2/3)·30=20 experienced participants. The remaining 6 and 10 are controls.", "Reading a 2:1 ratio as one half or allocating the ratio only across the pooled sample."),
      choice(2, "study-block-allocation", "procedure", "A study has blocks of 24 younger and 36 older volunteers. The randomized treatment:control ratio is 1:2 within each block. Find the treatment counts.", ["12 younger; 18 older", "16 younger; 24 older", "8 younger; 12 older", "24 younger; 36 older"], "8 younger; 12 older", "Treatment is one of three total ratio parts.", "One third of each block goes to treatment: 24/3=8 younger and 36/3=12 older volunteers. Control receives 16 and 24.", "Confusing treatment:control=1:2 with treatment receiving half of everyone."),
      table(3, "study-protocol-comparison", "A city wants to estimate whether a reminder causes higher recycling participation among city households. Assuming full participation and reliable measurement, which protocol supports both a city-population claim and a causal comparison?", ["Recruitment", "Reminder allocation"], [["Randomly sample from a complete city household list", "Randomly assign reminder or no reminder"], ["Use households that volunteer on a website", "Randomly assign reminder or no reminder"], ["Randomly sample from a complete city household list", "Let households choose whether to receive reminders"], ["Recruit only one neighborhood's volunteers", "Compare existing reminder users with nonusers"]], 0, "Population generalization needs random sampling; the causal comparison needs randomized treatment allocation.", "The first protocol randomly samples the target households and independently randomizes the reminder. The other protocols lose random population selection, random treatment allocation, or both.", "Expecting random assignment alone to make a volunteer sample representative."),
      table(4, "study-protocol-comparison", "A university wants a causal comparison of two study tools that also applies to its enrolled students. Assume everyone selected participates and outcomes are measured equally. Choose the protocol supporting both goals.", ["How students enter the study", "How tools are assigned"], [["Volunteers from a study-tool fan club", "Random allocation to the tools"], ["Random sample of all enrolled student IDs", "Students choose a preferred tool"], ["Students from one instructor's class", "Tools follow existing class sections"], ["Random sample of all enrolled student IDs", "Random allocation to the tools"]], 3, "Check recruitment and treatment assignment separately against the two intended claims.", "The last row combines random sampling of the intended student population with randomized tool allocation. This supports generalization and causal comparison under the stated participation and measurement assumptions.", "Treating a random sample as if it also randomly assigned a treatment."),
      choice(5, "study-confounding-repair", "reasoning", "A fertilizer experiment gives A to all sunny plots and B to all shaded plots. Which repair best separates fertilizer effects from sunlight?", ["Keep the assignment and use more sunny plots.", "Use sunlight level as blocks, then randomly assign A or B within each block.", "Measure plant height more precisely without changing assignment.", "Give A to larger plots and B to smaller plots as well."], "Use sunlight level as blocks, then randomly assign A or B within each block.", "The original fertilizer label is inseparable from sunlight exposure.", "Blocking by sunlight and randomizing fertilizer within each block lets both fertilizers be compared under the same exposure. More observations or finer measurement would not remove the original treatment–sunlight confounding.", "Assuming sample size or measurement precision can repair confounded assignment."),
      choice(6, "study-confounding-repair", "reasoning", "A teaching study gives a new method only to morning classes and the old method only to afternoon classes. Which redesign addresses time-of-day confounding?", ["Collect more students under the same method-by-time arrangement.", "Compare raw totals rather than average scores.", "Randomly assign new or old methods among comparable classes within each time-of-day block.", "Use the new method only for students with higher previous grades."], "Randomly assign new or old methods among comparable classes within each time-of-day block.", "Both teaching methods need to occur in each time block for a fair within-time comparison.", "Within-time randomized assignment separates method from time of day. The original design cannot tell whether a difference came from the method, the time block, or related class differences.", "Changing the outcome summary while leaving a confounded treatment assignment untouched."),
    ],
    remainingGaps: ["Cluster/stratified/systematic sampling, nonresponse, blinding/placebos, and the unit of randomization.", "Writing investigative questions, ethical constraints, and assessing interaction effects across blocks."],
  },
];
