import type { CognitiveDemand, DepthQuestion, LessonDepthPack, QuestionEvidence } from "./curriculum-depth-types.ts";

function evidence(objectiveId: string, demand: CognitiveDemand, representation: QuestionEvidence["representation"], misconception: string): QuestionEvidence {
  return { objectiveId, demand, representation, difficulty: 2, misconception, variantFamily: `${objectiveId}-variants` };
}

function choice(n: number, objective: string, demand: CognitiveDemand, prompt: string, choices: string[], answer: string, hint: string, explanation: string, misconception: string): DepthQuestion {
  return { id: `d1-q${n}`, prompt, choices, answer, hint, explanation, interaction: "four-choice", evidence: evidence(objective, demand, demand === "procedure" ? "symbolic" : "verbal", misconception) };
}

function table(n: number, objective: string, prompt: string, columns: string[], rows: string[][], correctRow: number, hint: string, explanation: string, misconception: string): DepthQuestion {
  const options = rows.map((cells, i) => ({ value: String.fromCharCode(65 + i), cells }));
  return { id: `d1-q${n}`, prompt, choices: options.map((row) => row.value), answer: options[correctRow].value, hint, explanation, interaction: "table-choice", interactionConfig: { kind: "table-choice", columns, rows: options }, evidence: evidence(objective, "representation", "table", misconception) };
}

export const advancedDepthPacks: LessonDepthPack[] = [
  {
    lessonSlug: "g10-geometric-constructions",
    objectives: [
      { id: "construction-arc-distance", description: "Calculate where equal-radius construction arcs intersect using half the segment and a right triangle.", requiredDemands: ["procedure"] },
      { id: "construction-coordinate-bisector", description: "Read coordinate construction data to identify the midpoint and perpendicular-bisector line.", requiredDemands: ["representation"] },
      { id: "construction-angle-justification", description: "Justify an angle-bisector construction using three congruent side pairs.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "Segment AB is 8 units long. Equal-radius arcs of radius 5 centered at A and B intersect at P above AB. P is 3 units above the midpoint M.",
    exampleSteps: ["Equal radii give AP=BP=5, so P lies on the perpendicular bisector of AB.", "The bisector meets AB at its midpoint M, so AM=8/2=4 and angle AMP is 90°.", "Use the right triangle: MP²=AP²−AM²=25−16=9.", "Take the nonnegative distance MP=3. The other arc intersection lies 3 units below AB."],
    questions: [
      choice(1, "construction-arc-distance", "procedure", "AB is 8 units long. Equal arcs of radius 5 from A and B intersect at P. How far is P from the midpoint of AB?", ["1", "3", "4", "9"], "3", "The midpoint splits AB into lengths 4 and 4; use a right triangle with hypotenuse 5.", "The perpendicular-bisector construction gives a right triangle with legs 4 and h. Thus h²=5²−4²=9 and h=3.", "Subtracting lengths instead of squared lengths, or reporting a squared distance."),
      choice(2, "construction-arc-distance", "procedure", "CD is 12 units long. Equal arcs of radius 10 from C and D meet at Q. What is the perpendicular distance from Q to CD?", ["4", "6", "8", "64"], "8", "Use half of CD, not the full length, as the horizontal leg.", "The half-segment is 6. The height satisfies h²+6²=10², so h²=64 and h=8.", "Using the full segment as a leg or forgetting the square root."),
      table(3, "construction-coordinate-bisector", "A=(−4,0), B=(4,0). Radius-5 arcs meet at P=(0,3) and Q=(0,−3). Which row correctly describes the constructed line PQ?", ["Midpoint of AB", "Line PQ", "Angle with AB"], [["(0,0)", "x=0", "90°"], ["(0,0)", "y=0", "0°"], ["(4,0)", "x=4", "90°"], ["(0,3)", "y=3", "0°"]], 0, "Read the coordinate shared by P and Q, then compare their line with the horizontal segment AB.", "A and B average to (0,0). Both arc intersections have x=0, so PQ is vertical and perpendicular to the horizontal AB.", "Confusing a vertical line x=constant with a horizontal line y=constant."),
      table(4, "construction-coordinate-bisector", "C=(0,−3), D=(0,3). Radius-5 arcs meet at R=(4,0) and S=(−4,0). Which row correctly describes the constructed line RS?", ["Midpoint of CD", "Line RS", "Angle with CD"], [["(0,3)", "y=3", "90°"], ["(0,0)", "x=0", "0°"], ["(0,0)", "y=0", "90°"], ["(4,0)", "x=4", "0°"]], 2, "R and S share a y-coordinate; CD is vertical.", "The midpoint of C and D is (0,0). R and S lie on y=0, a horizontal line, so RS crosses the vertical CD at 90°.", "Reading the perpendicular bisector as the original segment's line."),
      choice(5, "construction-angle-justification", "reasoning", "An arc centered at O meets two rays at A and B, so OA=OB. Equal arcs from A and B meet at P inside the angle, so AP=BP. Why does OP bisect angle AOB?", ["OA=OB alone makes every ray from O a bisector.", "Triangles AOP and BOP are congruent by SSS using their shared OP.", "AP=BP proves angle AOB is 90°.", "The diagram looks symmetric, so no proof is needed."], "Triangles AOP and BOP are congruent by SSS using their shared OP.", "List the two given equal side pairs and the side shared by both triangles.", "OA=OB, AP=BP, and OP=OP establish SSS congruence. Corresponding angles AOP and BOP are equal, which is exactly the angle-bisector claim.", "Treating appearance or one equal side pair as a proof of equal angles."),
      choice(6, "construction-angle-justification", "reasoning", "An arc from V gives VX=VY. Equal arcs from X and Y meet at T inside angle XVY, with XT=YT. Which argument proves VT bisects the angle?", ["XT=YT means VT is parallel to XY.", "VX=VY means angle XVY must be 60°.", "VT=VT and the two given side pairs imply SSS, then equal angles at V.", "VT crosses XY somewhere, so the angles at V are equal."], "VT=VT and the two given side pairs imply SSS, then equal angles at V.", "Compare triangles XVT and YVT and include their common side.", "VX=VY, XT=YT, and VT=VT make triangles XVT and YVT congruent by SSS. Therefore angle XVT equals angle YVT, so VT bisects angle XVY.", "Inferring a special angle or parallelism from equal construction radii."),
    ],
    remainingGaps: ["Executing compass-and-straightedge constructions interactively and checking the resulting geometry.", "Copying angles, constructing parallels and perpendiculars from external points, and constructing regular polygons."],
  },
  {
    lessonSlug: "g10-proof-structure",
    objectives: [
      { id: "proof-given-equation", description: "Translate a midpoint given into an equation and solve for the unknown.", requiredDemands: ["procedure"] },
      { id: "proof-chain-table", description: "Select a complete statement-and-reason chain establishing segment congruence.", requiredDemands: ["representation"] },
      { id: "proof-circular-argument", description: "Identify circular reasoning and replace it with a valid congruence argument.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "M is the midpoint of AB, AM=3x−2, and MB=x+6. A justified proof gives x=4 and AB=20.",
    exampleSteps: ["Use the definition of midpoint to state AM=MB.", "Substitute the expressions: 3x−2=x+6.", "Subtract x and add 2 to obtain 2x=8, hence x=4.", "Then AM=MB=10, and segment addition gives AB=10+10=20."],
    questions: [
      choice(1, "proof-given-equation", "procedure", "M is the midpoint of AB. AM=3x−2 and MB=x+6. What value of x follows from the midpoint definition?", ["2", "4", "8", "10"], "4", "A midpoint makes the two segment lengths equal; it does not make either length equal to x.", "AM=MB gives 3x−2=x+6. Subtract x and add 2: 2x=8, so x=4.", "Confusing the variable value with a segment's length."),
      choice(2, "proof-given-equation", "procedure", "N is the midpoint of CD. CN=5x−3 and ND=2x+15. Solve for x using the given.", ["3", "6", "9", "27"], "6", "Set 5x−3 equal to 2x+15 and collect the x terms.", "The midpoint definition gives 5x−3=2x+15. Thus 3x=18 and x=6; both segments then measure 27.", "Using segment addition before establishing equality of the two halves."),
      table(3, "proof-chain-table", "Given M is midpoint of AB and N is midpoint of CD, with AB=CD. Which row is a valid chain proving AM=CN?", ["First statement", "Substitution", "Conclusion and reason"], [["AM=AB and CN=CD", "AB=CD", "AM=CN, transitive"], ["AM=AB/2 and CN=CD/2", "AB/2=CD/2", "AM=CN, substitution"], ["AM=CN", "AB=CD", "AM=CN, given"], ["AM+CN=AB", "AB=CD", "AM=CN, addition"]], 1, "Write each half-segment as half of its own whole segment before using AB=CD.", "The midpoint definitions give AM=AB/2 and CN=CD/2. Dividing AB=CD by 2 gives equal halves, so substituting proves AM=CN.", "Assuming the claim or treating a midpoint half as the whole segment."),
      table(4, "proof-chain-table", "P is midpoint of EF, Q is midpoint of GH, and EF=GH. Which statement-and-reason chain proves PF=QH?", ["Midpoint consequences", "Equality operation", "Final substitution"], [["PF=EF/2; QH=GH/2", "EF/2=GH/2", "PF=QH"], ["PF=EF; QH=GH", "EF=GH", "PF=QH"], ["PF=QH", "PF+QH=EF", "PF=QH"], ["PF=EF/2; QH=GH/2", "EF/2=2GH", "PF=QH"]], 0, "A valid chain must establish both half-lengths and apply the same operation to EF and GH.", "PF and QH are halves of EF and GH respectively. Equal whole lengths remain equal after division by 2, establishing PF=QH by substitution.", "Applying different operations to opposite sides of an equality."),
      choice(5, "proof-circular-argument", "reasoning", "In triangle ABC, AB=AC and D is midpoint of BC. A student tries to prove angle BAD=angle DAC by saying 'AD is an angle bisector.' Which repair avoids assuming the conclusion?", ["Use AB=AC, BD=DC, and AD=AD to prove the triangles congruent by SSS.", "Repeat that AD is an angle bisector as a second statement.", "Say the drawing looks like two equal triangles.", "Assume angle BAD=angle DAC first and then conclude it again."], "Use AB=AC, BD=DC, and AD=AD to prove the triangles congruent by SSS.", "Use the side information already given, together with a shared side.", "D being a midpoint supplies BD=DC. Together with AB=AC and AD=AD, SSS proves triangles ABD and ACD congruent; corresponding angles at A are equal.", "Using the desired angle-bisector conclusion as its own reason."),
      choice(6, "proof-circular-argument", "reasoning", "In triangle PQR, PQ=PR and M is midpoint of QR. The goal is angle QPM=angle MPR. A draft starts 'PM bisects angle QPR.' What independent justification should replace that start?", ["Every midpoint segment bisects every angle.", "Triangles PQM and PRM share PM and have PQ=PR and QM=MR, so use SSS.", "The two angles are equal because the goal says so.", "PM must be parallel to QR because M is a midpoint."], "Triangles PQM and PRM share PM and have PQ=PR and QM=MR, so use SSS.", "Translate the midpoint given into a side equality and inspect the two triangles.", "The givens imply PQ=PR and QM=MR; PM is shared. SSS establishes triangle congruence, after which equality of the corresponding angles follows without assuming it.", "Assuming an angle is bisected merely because a segment reaches a midpoint."),
    ],
    remainingGaps: ["Student-authored multi-step proofs with feedback on each reason.", "Proofs involving parallel lines, quadrilaterals, contradiction, and counterexamples."],
  },
  {
    lessonSlug: "g10-sets-and-venn-diagrams",
    objectives: [
      { id: "venn-inclusion-exclusion", description: "Calculate union and neither counts without counting the overlap twice.", requiredDemands: ["procedure"] },
      { id: "venn-region-table", description: "Translate set totals and an intersection into all four disjoint Venn regions.", requiredDemands: ["representation"] },
      { id: "venn-conditional-denominator", description: "Use the correct set as the denominator in a conditional probability.", requiredDemands: ["application"] },
    ],
    legacyObjectives: { q3: "venn-inclusion-exclusion" },
    example: "Of 40 students, 22 take Art, 18 take Band, and 8 take both. The four regions are Art only 14, both 8, Band only 10, and neither 8.",
    exampleSteps: ["Place the overlap count 8 in the intersection first.", "Subtract the overlap from each set: Art only=22−8=14 and Band only=18−8=10.", "Add the three inside regions: 14+8+10=32 take at least one subject.", "Subtract from all 40 students: neither=40−32=8. Check 14+8+10+8=40."],
    questions: [
      choice(1, "venn-inclusion-exclusion", "procedure", "In a group of 40, |A|=22, |B|=18, and |A∩B|=8. How many belong to neither A nor B?", ["0", "8", "16", "32"], "8", "First find the union with 22+18−8, then subtract that count from 40.", "The union has 22+18−8=32 members. Its complement contains 40−32=8 members.", "Adding set totals without subtracting their shared members."),
      choice(2, "venn-inclusion-exclusion", "procedure", "Of 60 people, 35 cycle, 28 swim, and 15 do both. How many do neither activity?", ["3", "12", "15", "48"], "12", "People who do both are included in both activity totals.", "At least one activity includes 35+28−15=48 people. Therefore 60−48=12 do neither.", "Subtracting the overlap twice or reporting the union instead of its complement."),
      table(3, "venn-region-table", "A survey of 50 people gives |A|=26, |B|=21, and |A∩B|=9. Choose the complete Venn-region table.", ["A only", "Both", "B only", "Neither"], [["26", "9", "21", "3"], ["17", "9", "12", "12"], ["17", "9", "21", "3"], ["26", "0", "21", "3"]], 1, "Remove the overlap from each total, then check that all four entries sum to 50.", "A only=26−9=17 and B only=21−9=12. The union is 38, so neither=12; 17+9+12+12=50.", "Putting entire set totals into the exclusive regions."),
      table(4, "venn-region-table", "There are 80 members: 44 are in C, 36 are in D, and 20 are in both. Select the correct four-region table.", ["C only", "Both", "D only", "Neither"], [["44", "20", "36", "0"], ["24", "20", "16", "0"], ["24", "20", "16", "20"], ["24", "0", "16", "40"]], 2, "The intersection is included in both 44 and 36; the four regions must total 80.", "C only is 24 and D only is 16. The three included regions total 24+20+16=60, leaving 20 outside both sets.", "Forgetting to account for members outside the union."),
      choice(5, "venn-conditional-denominator", "application", "A club has 12 members in both Art and Band and 30 Band members in total. Given that a randomly selected member is in Band, what is P(Art | Band)?", ["12/42", "12/30", "30/42", "30/12"], "12/30", "The phrase 'given Band' restricts the possible members to the 30 in Band.", "The conditional sample space contains 30 Band members, of whom 12 also take Art. Thus P(Art | Band)=12/30=0.4.", "Using the union or reversing the condition as the denominator."),
      choice(6, "venn-conditional-denominator", "application", "Of 45 cyclists, 18 also swim. If a person is selected at random from the cyclists, what is the probability that the person swims?", ["18/63", "45/18", "27/45", "18/45"], "18/45", "Count swimmers within the group that was actually sampled.", "Selection is restricted to 45 cyclists. The favorable subset has 18 members, giving 18/45=0.4.", "Using people who do only the conditioning activity as the favorable count."),
    ],
    remainingGaps: ["Three-set inclusion–exclusion, De Morgan's laws, and direct diagram shading.", "Comparing independence with disjointness from Venn-region data."],
  },
  {
    lessonSlug: "g10-cross-sections-and-rotations",
    objectives: [
      { id: "solid-rotation-volume", description: "Calculate a solid's volume by relating the rotation axis to its radius and height.", requiredDemands: ["procedure"] },
      { id: "solid-sphere-slice-table", description: "Read cross-section data using r²=R²−d² for a spherical slice.", requiredDemands: ["representation"] },
      { id: "solid-axis-comparison", description: "Compare volumes formed by rotating a rectangle about different sides.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "A 3-by-5 rectangle rotates around its 5-unit side. It creates a cylinder of radius 3, height 5, and volume 45π cubic units.",
    exampleSteps: ["Mark the 5-unit side as the axis; its length becomes the cylinder's height.", "The opposite edge lies 3 units from the axis, so the radius is 3, not 5.", "Calculate V=πr²h=π·3²·5=45π cubic units.", "If the axis switches to the 3-unit side, the radius is 5 and the volume is π·5²·3=75π."],
    questions: [
      choice(1, "solid-rotation-volume", "procedure", "A rectangle has sides 4 and 7 units. Rotate its filled region about the 7-unit side. What is the resulting cylinder's volume?", ["28π", "112π", "196π", "448π"], "112π", "The rotation axis gives the height; the perpendicular side gives the radius.", "The cylinder has radius 4 and height 7. Therefore V=π·4²·7=112π cubic units.", "Swapping the height and radius or treating the perpendicular side as a diameter."),
      choice(2, "solid-rotation-volume", "procedure", "A 5-by-9 rectangle rotates about its 9-unit side. Find the volume of the solid swept out.", ["45π", "81π", "225π", "405π"], "225π", "The far edge is 5 units from the axis, so use r=5.", "The solid is a cylinder with r=5 and h=9. Its volume is π·25·9=225π cubic units.", "Failing to square the radius in a volume formula."),
      table(3, "solid-sphere-slice-table", "A sphere has radius 5. A slicing plane is distance d from the center. Which row correctly gives the circular slice's radius r and area?", ["d", "r", "Area"], [["3", "2", "4π"], ["3", "4", "16π"], ["3", "5", "25π"], ["3", "8", "64π"]], 1, "The sphere radius, distance to the plane, and slice radius form a right triangle.", "r²+d²=R² gives r²=25−9=16, so r=4 and the cross-sectional area is 16π.", "Subtracting the offset directly from the sphere's radius."),
      table(4, "solid-sphere-slice-table", "A sphere has radius 13. The slicing plane is 5 units from its center. Select the correct slice measurements.", ["Center-to-plane distance", "Slice radius", "Slice area"], [["5", "8", "64π"], ["5", "13", "169π"], ["5", "12", "144π"], ["5", "18", "324π"]], 2, "Use r²=13²−5², then take a square root before naming the radius.", "The slice radius is √(169−25)=√144=12. Its area is π·12²=144π square units.", "Confusing the sphere radius with the smaller radius of an off-center slice."),
      choice(5, "solid-axis-comparison", "reasoning", "A 2-by-6 rectangle rotates first about its 2-unit side, then about its 6-unit side. What is V(first)/V(second)?", ["1/3", "1", "3", "9"], "3", "Calculate each radius and height separately; the radius is squared.", "The first volume is π·6²·2=72π. The second is π·2²·6=24π, so the ratio is 3.", "Assuming the same rectangle gives the same volume regardless of the rotation axis."),
      choice(6, "solid-axis-comparison", "reasoning", "A 3-by-12 rectangle rotates about its 3-unit side and then its 12-unit side. How many times as large is the first solid's volume?", ["1/4", "2", "4", "16"], "4", "The first solid has radius 12 and height 3; the second has radius 3 and height 12.", "The volumes are 432π and 108π respectively. Their quotient is 4, because the longer dimension acts as a squared radius in the first rotation.", "Squaring the final side-length ratio without also accounting for the swapped height."),
    ],
    remainingGaps: ["Oblique cross-sections, noncentral cuts of cones and pyramids, and rotating regions around external axes.", "Manipulating a 3D model to trace a plane or an axis of rotation."],
  },
  {
    lessonSlug: "g11-matrix-operations",
    objectives: [
      { id: "matrix-row-column-product", description: "Compute every entry of a 2-by-2 matrix product using row-by-column multiplication.", requiredDemands: ["procedure"] },
      { id: "matrix-model-table", description: "Translate a quantity matrix and price vector into a table of total costs.", requiredDemands: ["representation"] },
      { id: "matrix-order-reasoning", description: "Use computed products to explain why matrix multiplication depends on order.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "For A=[[1,2],[3,4]] and B=[[2,0],[−1,3]], AB=[[0,6],[2,12]].",
    exampleSteps: ["The inner dimensions match, so a 2-by-2 product is defined.", "Dot row 1 of A with the columns of B: 1·2+2·(−1)=0 and 1·0+2·3=6.", "Dot row 2 of A with the columns of B: 3·2+4·(−1)=2 and 3·0+4·3=12.", "Place these results in their row and column positions to get [[0,6],[2,12]]."],
    questions: [
      choice(1, "matrix-row-column-product", "procedure", "Calculate AB for A=[[1,2],[3,4]] and B=[[2,0],[−1,3]].", ["[[2,0],[−3,12]]", "[[0,6],[2,12]]", "[[2,4],[8,10]]", "[[0,2],[6,12]]"], "[[0,6],[2,12]]", "Each product entry is a row of A dotted with a column of B.", "The four dot products are 2−2=0, 0+6=6, 6−4=2, and 0+12=12, giving [[0,6],[2,12]].", "Multiplying corresponding entries or transposing the output."),
      choice(2, "matrix-row-column-product", "procedure", "Find AB when A=[[2,−1],[0,3]] and B=[[1,4],[2,−2]].", ["[[2,−4],[0,−6]]", "[[0,6],[10,−6]]", "[[0,10],[6,−6]]", "[[2,11],[4,−8]]"], "[[0,10],[6,−6]]", "Watch the double negative in the first row, second column: (−1)(−2).", "The entries are 2·1−1·2=0, 2·4+(−1)(−2)=10, 0·1+3·2=6, and 0·4+3·(−2)=−6.", "Losing the sign of a negative product or using entrywise multiplication."),
      table(3, "matrix-model-table", "Each row of Q=[[2,1],[1,3]] lists notebooks and pens for one order. Prices are $4 per notebook and $5 per pen. Which cost table equals Q times the price column [4,5]?", ["Order 1 total", "Order 2 total"], [["$8", "$15"], ["$13", "$19"], ["$14", "$17"], ["$12", "$20"]], 1, "Use each entire order row, multiplying its quantities by the matching prices.", "Order 1 costs 2·4+1·5=$13. Order 2 costs 1·4+3·5=$19. Matrix multiplication preserves the row order of the two orders.", "Using a column of quantities as an order or ignoring one item."),
      table(4, "matrix-model-table", "Q=[[1,4],[3,2]] lists boxes and envelopes in two orders. One box costs $6 and one envelope $2. Choose the cost table for Q[6,2].", ["Order 1 total", "Order 2 total"], [["$10", "$24"], ["$6", "$4"], ["$18", "$8"], ["$14", "$22"]], 3, "Multiply [1,4] and [3,2] separately by the price column [6,2].", "The first total is 1·6+4·2=$14. The second total is 3·6+2·2=$22; the output has one entry per order.", "Pairing the correct quantities with the wrong item prices."),
      choice(5, "matrix-order-reasoning", "reasoning", "A=[[2,0],[0,1]] and B=[[1,1],[0,1]]. Which calculation correctly shows why AB cannot be replaced by BA?", ["AB=BA=[[2,1],[0,1]].", "AB=[[2,2],[0,1]] but BA=[[2,1],[0,1]].", "AB is undefined because both matrices are square.", "AB and BA must differ in every entry."], "AB=[[2,2],[0,1]] but BA=[[2,1],[0,1]].", "Compare just the first-row, second-column entries of the two products.", "In AB the (1,2) entry is 2·1+0·1=2; in BA it is 1·0+1·1=1. The other entries agree, but one unequal entry is enough to prove AB≠BA.", "Assuming matrix multiplication is commutative because scalar multiplication is."),
      choice(6, "matrix-order-reasoning", "reasoning", "C=[[1,0],[0,3]] and D=[[1,0],[1,1]]. Which statement correctly checks multiplication order?", ["CD=DC because both products are 2-by-2.", "CD=[[1,0],[1,3]] and DC=[[1,0],[3,3]].", "CD=[[1,0],[3,3]] and DC=[[1,0],[1,3]], so order matters.", "Neither product exists because C has a zero entry."], "CD=[[1,0],[3,3]] and DC=[[1,0],[1,3]], so order matters.", "Compute the second-row, first-column entry in each order.", "For CD this entry is 0·1+3·1=3. For DC it is 1·1+1·0=1. Thus the products have the same dimensions but different values.", "Mistaking equal output dimensions for equal matrix entries."),
    ],
    remainingGaps: ["Products of nonsquare numerical matrices and multistep transformation compositions.", "Connecting products to inverse matrices and solving larger systems."],
  },
  {
    lessonSlug: "g11-trig-identities-equations",
    objectives: [
      { id: "trig-all-interval-solutions", description: "Solve a scaled sine or cosine equation and retain all solutions in [0,2π).", requiredDemands: ["procedure"] },
      { id: "trig-signed-ratio-table", description: "Reconstruct a complete signed trigonometric-ratio row from one ratio and a quadrant.", requiredDemands: ["representation"] },
      { id: "trig-identity-domain", description: "Simplify a trigonometric quotient while retaining its original domain restrictions.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: { q3: "trig-all-interval-solutions", q4: "trig-all-interval-solutions" },
    example: "Solve 2sinθ=1 on [0,2π): θ=π/6 or 5π/6.",
    exampleSteps: ["Divide by 2 to obtain sinθ=1/2.", "The reference angle with sine 1/2 is π/6.", "Sine is positive in quadrants I and II, giving π/6 and π−π/6=5π/6.", "Both angles lie in [0,2π), and substitution gives 2·(1/2)=1 for each."],
    questions: [
      choice(1, "trig-all-interval-solutions", "procedure", "Solve 2sinθ=1 for all θ in [0,2π).", ["{π/6}", "{π/6,5π/6}", "{π/6,7π/6}", "{π/3,2π/3}"], "{π/6,5π/6}", "After dividing by 2, locate both quadrants where sine is positive.", "sinθ=1/2 has reference angle π/6. The positive-sine quadrants give θ=π/6 and θ=5π/6, with no other solutions in one full turn.", "Keeping only the principal inverse-sine value."),
      choice(2, "trig-all-interval-solutions", "procedure", "Find every solution of 2cosθ=−1 on [0,2π).", ["{2π/3}", "{π/3,5π/3}", "{2π/3,4π/3}", "{π/6,5π/6}"], "{2π/3,4π/3}", "Cosine is negative in quadrants II and III; use reference angle π/3.", "cosθ=−1/2. Subtract π/3 from π and add π/3 to π to obtain 2π/3 and 4π/3. Both satisfy the interval and equation.", "Choosing the quadrants for positive rather than negative cosine."),
      table(3, "trig-signed-ratio-table", "sinθ=−3/5 and θ is in quadrant III. Which row gives all three ratios?", ["sinθ", "cosθ", "tanθ"], [["−3/5", "4/5", "−3/4"], ["−3/5", "−4/5", "3/4"], ["−3/5", "−2/5", "3/2"], ["−3/5", "−4/5", "−3/4"]], 1, "Use sin²θ+cos²θ=1, then choose the cosine sign from quadrant III.", "cos²θ=1−9/25=16/25. In quadrant III cosine is negative, so cosθ=−4/5. The quotient sinθ/cosθ is positive 3/4.", "Taking only the positive square root or losing the sign when dividing."),
      table(4, "trig-signed-ratio-table", "cosθ=−5/13 and θ lies in quadrant II. Select the correct signed ratio table.", ["cosθ", "sinθ", "tanθ"], [["−5/13", "−12/13", "12/5"], ["−5/13", "8/13", "−8/5"], ["−5/13", "12/13", "−12/5"], ["−5/13", "12/13", "12/5"]], 2, "Find sin²θ first; sine is positive and tangent negative in quadrant II.", "sin²θ=1−25/169=144/169, so sinθ=12/13 in quadrant II. Therefore tanθ=(12/13)/(−5/13)=−12/5.", "Subtracting numerators without squaring or overlooking the quadrant sign."),
      choice(5, "trig-identity-domain", "reasoning", "A student simplifies (1−cos²θ)/sinθ to sinθ. Which statement preserves the original expression's domain?", ["The equality holds for every real θ without restriction.", "The equality holds only when cosθ=0.", "The equality holds when sinθ≠0; the original quotient is undefined when sinθ=0.", "The equality is never valid because a denominator cannot be canceled."], "The equality holds when sinθ≠0; the original quotient is undefined when sinθ=0.", "Replace the numerator with sin²θ and check when division by sinθ is allowed.", "The identity changes the quotient to sin²θ/sinθ. Cancellation gives sinθ only for sinθ≠0; simplification does not fill the original expression's undefined points.", "Erasing excluded inputs during cancellation."),
      choice(6, "trig-identity-domain", "reasoning", "For (1−sin²θ)/cosθ, which simplification and restriction are both correct?", ["cosθ for all θ, including cosθ=0", "sinθ when cosθ≠0", "1/cosθ when sinθ≠0", "cosθ when cosθ≠0"], "cosθ when cosθ≠0", "The numerator equals cos²θ, but the original denominator must stay nonzero.", "Use 1−sin²θ=cos²θ, then divide by cosθ to obtain cosθ. The quotient still requires cosθ≠0, excluding π/2+kπ.", "Confusing a function's simplified formula with its original domain."),
    ],
    remainingGaps: ["Double-angle and sum/difference identities, equations with multiple frequencies, and extraneous roots introduced by squaring.", "Graph-based comparison of identities and numerical roots."],
  },
  {
    lessonSlug: "g11-rational-function-models",
    objectives: [
      { id: "rational-average-cost", description: "Evaluate average cost as fixed cost per item plus variable cost per item.", requiredDemands: ["procedure"] },
      { id: "rational-rate-table", description: "Identify a table satisfying a fixed-distance reciprocal speed–time model.", requiredDemands: ["representation"] },
      { id: "rational-target-domain", description: "Solve a rational-model target inequality within a positive integer domain.", requiredDemands: ["application"] },
    ],
    legacyObjectives: {},
    example: "A print run has a $180 setup fee and costs $4 per poster. Average cost is C(n)=180/n+4 for positive integers n; at n=30 it is $10 per poster.",
    exampleSteps: ["Total cost is 180+4n dollars, where n is a positive whole-number count.", "Divide by the number of posters: C(n)=(180+4n)/n=180/n+4.", "For 30 posters, calculate 180/30+4=6+4=$10 per poster.", "To reach at most $7 per poster, solve 180/n+4≤7. Because n>0, this gives n≥60."],
    questions: [
      choice(1, "rational-average-cost", "procedure", "A print run costs $180 to set up plus $4 per poster. What is the average cost per poster when 30 posters are printed?", ["$6", "$10", "$184", "$300"], "$10", "Add the variable cost per item to the setup fee divided among 30 items.", "The total is 180+4·30=$300. Dividing by 30 gives $10 per poster, equivalently 180/30+4.", "Reporting the fixed cost per item or total cost instead of average cost."),
      choice(2, "rational-average-cost", "procedure", "A batch costs a fixed $240 plus $3 per item. For 40 items, find the average cost per item.", ["$3", "$6", "$9", "$360"], "$9", "Spread the fixed $240 over 40 items, then include the $3 item cost.", "The fixed cost contributes 240/40=$6 per item. Adding $3 gives an average of $9; total cost is $360.", "Omitting the variable cost from the average."),
      table(3, "rational-rate-table", "A trip covers exactly 180 km at constant speed v, so time t=180/v. Which row correctly gives the travel times at the three speeds?", ["t at 30 km/h", "t at 60 km/h", "t at 90 km/h"], [["6 h", "3 h", "2 h"], ["6 h", "12 h", "18 h"], ["3 h", "2 h", "1 h"], ["150 h", "120 h", "90 h"]], 0, "For each column, divide the fixed distance by that column's speed.", "The times are 180/30=6, 180/60=3, and 180/90=2 hours. Every speed–time product equals the same 180 km.", "Treating time as directly proportional to speed."),
      table(4, "rational-rate-table", "For a 240 km trip, choose the row consistent with t=240/v, where v is in km/h and t is in hours.", ["t at 40 km/h", "t at 60 km/h", "t at 80 km/h"], [["6 h", "9 h", "12 h"], ["4 h", "3 h", "2 h"], ["6 h", "4 h", "3 h"], ["200 h", "180 h", "160 h"]], 2, "Check that multiplying each time by its speed gives 240.", "The required times are 240/40=6, 240/60=4, and 240/80=3 hours; their decreasing values reflect a fixed-distance reciprocal model.", "Using equal time decreases for equal speed increases."),
      choice(5, "rational-target-domain", "application", "For a positive integer number n of posters, average cost is C(n)=180/n+4 dollars. What is the smallest n that makes C(n) at most $7?", ["26", "45", "59", "60"], "60", "Subtract 4 first. Since n is positive, multiplying the inequality by n keeps its direction.", "180/n+4≤7 gives 180≤3n, hence n≥60. The smallest allowed integer is 60, where the average is exactly $7.", "Solving for total cost instead of average cost or dropping the integer restriction."),
      choice(6, "rational-target-domain", "application", "A positive integer batch size n has average cost C(n)=250/n+3 dollars. Find the smallest n with average cost at most $9.", ["41", "42", "28", "250"], "42", "Solve n≥250/6 and round upward because the target must be met.", "250/n≤6 implies n≥41.666…. The smallest integer is 42; 41 items cost about $9.10 each, while 42 cost about $8.95 each.", "Rounding a minimum required quantity downward."),
    ],
    remainingGaps: ["Rational graphs with holes, multiple asymptotes, sign changes, and constrained input intervals.", "Building models from empirical data and checking model error."],
  },
  {
    lessonSlug: "g11-confidence-intervals",
    objectives: [
      { id: "ci-estimate-critical-se", description: "Calculate an interval from an estimate, supplied critical multiplier, and standard error.", requiredDemands: ["procedure"] },
      { id: "ci-endpoint-table", description: "Recover an interval's midpoint and margin of error from its endpoints.", requiredDemands: ["representation"] },
      { id: "ci-sample-size-planning", description: "Use inverse-square-root scaling to plan sample sizes at fixed confidence and variability.", requiredDemands: ["application"] },
    ],
    legacyObjectives: { q4: "ci-endpoint-table", q5: "ci-endpoint-table" },
    example: "An estimate is 50 with standard error 2. Using critical multiplier 1.96, the confidence interval is 50±3.92=[46.08,53.92].",
    exampleSteps: ["Identify the estimate 50, standard error 2, and supplied critical multiplier 1.96.", "Multiply to get the margin of error: 1.96·2=3.92.", "Subtract and add the margin: 50−3.92=46.08 and 50+3.92=53.92.", "The endpoints are reported to two decimal places. They describe uncertainty in the population parameter under the method's conditions."],
    questions: [
      choice(1, "ci-estimate-critical-se", "procedure", "An estimate is 50 and its standard error is 2. Use the supplied critical multiplier 1.96. Which confidence interval results? Give endpoints to two decimals.", ["[48.00,52.00]", "[46.08,53.92]", "[49.02,50.98]", "[3.92,50.00]"], "[46.08,53.92]", "The margin is the multiplier times the standard error, not the standard error alone.", "The margin is 1.96·2=3.92. The endpoints are 50−3.92=46.08 and 50+3.92=53.92.", "Using one standard error as the margin when a critical multiplier is supplied."),
      choice(2, "ci-estimate-critical-se", "procedure", "The estimated population mean is 120, SE=4, and the supplied critical multiplier is 1.645. Select the interval with endpoints rounded to two decimals.", ["[116.00,124.00]", "[118.36,121.65]", "[113.42,126.58]", "[106.84,133.16]"], "[113.42,126.58]", "Compute 1.645×4 before subtracting and adding the margin.", "The margin is 1.645·4=6.58. The endpoints are 120−6.58=113.42 and 120+6.58=126.58.", "Rounding the margin early or forgetting to multiply by the standard error."),
      table(3, "ci-endpoint-table", "A reported interval is [38,50]. Which row correctly expresses it as estimate ± margin of error?", ["Estimate", "Margin of error"], [["38", "12"], ["44", "12"], ["44", "6"], ["50", "6"]], 2, "The estimate is halfway between endpoints; the margin is half the interval's width.", "The midpoint is (38+50)/2=44. The margin is (50−38)/2=6, so the same interval is 44±6.", "Using the full width as the margin of error."),
      table(4, "ci-endpoint-table", "A mean interval is [112,128]. Choose the row that reconstructs these endpoints.", ["Estimate", "Margin of error"], [["120", "8"], ["120", "16"], ["112", "8"], ["128", "16"]], 0, "Check that subtracting and adding the proposed margin returns both original endpoints.", "The midpoint is (112+128)/2=120, and each endpoint is 8 units away. Thus 120±8 reproduces [112,128].", "Confusing an endpoint with the point estimate."),
      choice(5, "ci-sample-size-planning", "application", "For planning, assume margin of error is proportional to 1/√n, with confidence and variability fixed. A sample of 100 gives margin 6. What sample size gives margin 3?", ["50", "200", "300", "400"], "400", "Halving the margin requires doubling √n, so square the size factor.", "The margin ratio is 3/6=1/2, so √(100/n)=1/2. Squaring gives 100/n=1/4 and n=400.", "Assuming doubling sample size halves the margin."),
      choice(6, "ci-sample-size-planning", "application", "Keep confidence and variability fixed and use margin ∝1/√n. With n=225 the margin is 4. What n is required for margin 2?", ["450", "675", "900", "1125"], "900", "The desired margin is half as large, requiring four times the sample size.", "(4/2)²=4 is the sample-size multiplier. Therefore the planned size is 225·4=900.", "Applying a linear rather than square relationship to sample-size planning."),
    ],
    remainingGaps: ["Long-run confidence interpretation, coverage simulations, and diagnosing invalid intervals from biased samples.", "Deriving critical values and standard errors rather than using supplied values.", "Reading original sample-data tables and full statistical-software output, beyond matching interval representations."],
  },
  {
    lessonSlug: "g12-inference-for-proportions",
    objectives: [
      { id: "proportion-null-z", description: "Calculate a one-proportion z statistic using the null proportion in the standard error.", requiredDemands: ["procedure"] },
      { id: "proportion-output-decision", description: "Translate a supplied test result into a coherent p-value, decision, and contextual conclusion.", requiredDemands: ["representation"] },
      { id: "proportion-difference-ci", description: "Construct and interpret a confidence interval for a difference of population proportions.", requiredDemands: ["application"] },
    ],
    legacyObjectives: {},
    example: "A random independent sample has 60 successes among 100 trials. For H₀:p=0.50, SE₀=√(0.5·0.5/100)=0.05 and z=(0.60−0.50)/0.05=2.",
    exampleSteps: ["The sample proportion is 60/100=0.60; the null proportion remains 0.50.", "Assume randomization and independence; the expected success and failure counts under H₀ are both 50, satisfying the large-count condition.", "Use the null standard error √(0.50·0.50/100)=0.05, then calculate z=2.", "For Hₐ:p>0.50, the supplied upper-tail probability is 0.0228. At α=0.05 reject H₀ and report evidence that the population proportion exceeds 0.50."],
    questions: [
      choice(1, "proportion-null-z", "procedure", "A random independent sample of n=100 has 60 successes. Test H₀:p=0.50; large-count conditions hold. Using SE₀=√(0.50·0.50/100)=0.05, compute z.", ["0.1", "1", "2", "12"], "2", "Subtract the null proportion from the sample proportion before dividing by SE₀.", "The sample proportion is 60/100=0.60. Thus z=(0.60−0.50)/0.05=0.10/0.05=2.", "Dividing the entire sample proportion by SE rather than its deviation from the null."),
      choice(2, "proportion-null-z", "procedure", "A random independent sample has 184 successes among 400 observations. For H₀:p=0.50, conditions hold and SE₀=√(0.50·0.50/400)=0.025. What is z?", ["−1.6", "−0.04", "1.6", "18.4"], "−1.6", "184/400=0.46, which is below the null proportion.", "The standardized difference is (0.46−0.50)/0.025=−0.04/0.025=−1.6. Its negative sign records that the sample proportion is below H₀'s value.", "Dropping the sign of the sample-minus-null difference."),
      table(3, "proportion-output-decision", "A valid one-proportion test of H₀:p=0.50 against Hₐ:p>0.50 gives z=2. A standard-normal table gives P(Z≥2)=0.0228. At α=0.05, choose the correct report.", ["p-value", "Decision", "Population conclusion"], [["0.0228", "Reject H₀", "Evidence that p>0.50"], ["0.0456", "Reject H₀", "Proof that p=1"], ["0.9772", "Do not reject H₀", "Evidence that p<0.50"], ["0.0228", "Do not reject H₀", "H₀ has a 2.28% chance of being true"]], 0, "The alternative is upper-tailed, so use the supplied upper-tail probability without doubling.", "The p-value is 0.0228, below 0.05. Rejecting H₀ supports p>0.50 for the population under the test's assumptions; the p-value is not the probability that H₀ is true.", "Using the wrong tail or interpreting a p-value as the probability of a hypothesis."),
      table(4, "proportion-output-decision", "A valid test of H₀:p=0.40 against Hₐ:p<0.40 gives z=−1.50. The supplied table gives P(Z≤−1.50)=0.0668. With α=0.05, which report is valid?", ["p-value", "Decision", "Population conclusion"], [["0.9332", "Reject H₀", "Evidence that p>0.40"], ["0.0668", "Reject H₀", "p is certainly less than 0.40"], ["0.0668", "Do not reject H₀", "Insufficient evidence that p<0.40"], ["0.0668", "Accept H₀ as proven", "p is exactly 0.40"]], 2, "Compare 0.0668 with 0.05; failing to reject does not prove equality.", "The lower-tail alternative uses p-value 0.0668. Because this exceeds α, do not reject H₀; the sample does not provide sufficient evidence that the population proportion is below 0.40.", "Treating failure to reject as proof of the null hypothesis."),
      choice(5, "proportion-difference-ci", "application", "Independent random samples satisfy two-proportion interval conditions. p̂A=0.60, p̂B=0.45, and the unpooled SE for p̂A−p̂B is 0.04. Use z*=1.96. Which interval and conclusion for pA−pB are correct? Report four decimals.", ["[0.0716,0.2284]; the interval supports pA>pB.", "[0.1100,0.1900]; use one SE as the margin.", "[−0.2284,−0.0716]; the interval supports pA<pB.", "[0.5216,0.6784]; this estimates pA−pB."], "[0.0716,0.2284]; the interval supports pA>pB.", "Center the interval at 0.60−0.45, not at either single sample proportion.", "The difference is 0.15 and the margin is 1.96·0.04=0.0784. The interval is [0.0716,0.2284], entirely positive, supporting a greater population proportion in A.", "Centering a difference interval at one sample's proportion."),
      choice(6, "proportion-difference-ci", "application", "Independent random samples meet the interval conditions. p̂C=0.48, p̂D=0.40, and the supplied unpooled SE of their difference is 0.05. With z*=1.96, choose the interval and supported conclusion for pC−pD. Report three decimals.", ["[0.030,0.130]; pC is larger.", "[−0.018,0.178]; the interval includes 0, so it does not establish a difference.", "[−0.178,0.018]; pD is certainly larger.", "[0.382,0.578]; pC and pD are exactly equal."], "[−0.018,0.178]; the interval includes 0, so it does not establish a difference.", "Calculate 0.08±1.96·0.05 and inspect whether zero lies between the endpoints.", "The center is 0.08 and margin is 0.098, giving [−0.018,0.178]. Both zero and positive differences remain plausible; this interval does not establish which population proportion is greater.", "Concluding a population difference solely because the sample difference is positive."),
    ],
    remainingGaps: ["Student-led verification of randomization, 10% and large-count conditions; one-proportion interval standard-error derivation.", "Two-proportion hypothesis tests with pooled standard errors, power, and Type I/II errors.", "Reading full statistical-software output and source-data tables rather than selecting structured report rows.", "Chi-square homogeneity and independence remain in AP Statistics 2026–27 and require separate coverage; goodness of fit and geometric distributions are extension/older-framework topics."],
  },
  {
    lessonSlug: "g12-inference-for-means",
    objectives: [
      { id: "mean-t-statistic", description: "Calculate a one-sample t statistic from a sample mean, sample SD, sample size, and null mean.", requiredDemands: ["procedure"] },
      { id: "mean-design-table", description: "Choose the inference unit and t-procedure from a study's paired or independent data structure.", requiredDemands: ["representation"] },
      { id: "mean-paired-interval", description: "Construct and interpret a paired t confidence interval for a defined mean difference.", requiredDemands: ["application"] },
    ],
    legacyObjectives: { q1: "mean-design-table" },
    example: "For n=16, x̄=52, s=4, and H₀:μ=50, SE=4/√16=1 and t=(52−50)/1=2 with 15 degrees of freedom.",
    exampleSteps: ["The parameter is the population mean μ; assume a random independent sample from an approximately normal population with no extreme outliers.", "Estimate the standard error using the sample SD: SE=s/√n=4/4=1.", "Standardize the mean difference: t=(52−50)/1=2.", "The one-sample reference distribution has n−1=15 degrees of freedom. A p-value additionally requires the alternative hypothesis and a t table or technology."],
    questions: [
      choice(1, "mean-t-statistic", "procedure", "A random independent sample of 16 from an approximately normal population has x̄=52 and s=4. For H₀:μ=50, calculate t=(x̄−μ₀)/(s/√n).", ["0.5", "2", "8", "15"], "2", "First compute the standard error 4/√16, then divide the mean difference by it.", "SE=4/4=1, so t=(52−50)/1=2. The sample size affects SE; it is not the numerator of t.", "Dividing by the sample SD without converting it to a standard error."),
      choice(2, "mean-t-statistic", "procedure", "For a random independent sample of n=25, x̄=97 and s=10. Normality conditions hold. Under H₀:μ=100, what is the one-sample t statistic?", ["−0.3", "−1.5", "1.5", "−7.5"], "−1.5", "The standard error is 10/5=2, and the sample mean is 3 below the null mean.", "SE=10/√25=2. Therefore t=(97−100)/2=−1.5, with 24 degrees of freedom.", "Losing the direction of the difference or dividing by n instead of √n."),
      table(3, "mean-design-table", "Twenty randomly selected adults have blood pressure measured before and after an exercise program. For the mean change, which analysis row matches this study?", ["Observation used in inference", "Procedure", "Sample size for inference"], [["All 40 readings as independent", "Two independent samples t", "40"], ["20 within-person after-minus-before differences", "One-sample t on paired differences", "20"], ["20 after readings only", "One-proportion z", "20"], ["One pooled before/after mean", "One-sample t", "1"]], 1, "Two readings from the same person are linked; form one difference per person.", "The analysis units are the 20 adults' changes. A paired t analysis is a one-sample t procedure on 20 differences; treating 40 linked readings as independent discards the pairing.", "Inflating the sample size by counting both members of each pair separately."),
      table(4, "mean-design-table", "A study independently samples 18 batteries from brand A and 22 different batteries from brand B. No batteries are matched. Which row fits inference about μA−μB?", ["Data units", "Procedure", "Group sample sizes"], [["Arbitrary paired battery differences", "Paired t", "18 pairs"], ["Pass/fail counts", "One-proportion z", "40"], ["Separate battery lifetimes in two independent groups", "Two-sample t", "18 and 22"], ["All lifetimes treated as one group", "One-sample t for μA−μB", "40"]], 2, "Pairing must come from the study design, not from arranging unrelated observations side by side.", "The batteries are different independent units in two groups, so a two-sample t procedure compares their population mean lifetimes. There is no basis for forming matched differences.", "Inventing a pairing for two unrelated samples."),
      choice(5, "mean-paired-interval", "application", "For 16 randomly sampled pairs, define d=after−before. The differences are approximately normal, with d̄=−4 and sd=4. Use supplied 95% t*=2.131 (df=15). Which interval for μd and interpretation are correct? Round to two decimals.", ["[−6.13,−1.87]; mean after-minus-before change is negative.", "[−12.52,4.52]; divide by the SD only.", "[1.87,6.13]; after values are larger on average.", "[−4.53,−3.47]; divide the SD by 16."], "[−6.13,−1.87]; mean after-minus-before change is negative.", "There are 16 differences, so SE=4/√16=1. Keep the direction after−before.", "The margin is 2.131·1=2.131, giving [−6.131,−1.869], rounded to [−6.13,−1.87]. Since the whole interval is negative, it supports a lower population mean after measurement, without by itself proving causation.", "Reversing the defined difference or treating paired observations as twice as many independent units."),
      choice(6, "mean-paired-interval", "application", "For 25 randomly sampled matched pairs, d=after−before has d̄=1 and sd=5; normality conditions hold. Use supplied 95% t*=2.064 (df=24). Choose the interval for μd and its interpretation, to two decimals.", ["[0.59,1.41]; the population mean change is positive.", "[−1.06,3.06]; zero remains plausible for the population mean change.", "[−3.06,1.06]; the mean change is certainly negative.", "[−9.32,11.32]; the margin uses sd without √n."], "[−1.06,3.06]; zero remains plausible for the population mean change.", "Use SE=5/√25=1 and compute 1±2.064.", "The unrounded interval is [−1.064,3.064], which rounds to [−1.06,3.06]. It includes zero, so the interval does not establish a nonzero population mean change.", "Inferring a definite population increase from a positive sample mean difference."),
    ],
    remainingGaps: ["One- and two-sample t intervals and hypothesis tests with student-derived conditions and p-values.", "Welch standard errors/degrees of freedom, outlier sensitivity, study design limitations, and power."],
  },
  {
    lessonSlug: "g12-infinite-series",
    objectives: [
      { id: "series-maclaurin-approximation", description: "Build and evaluate the degree-three Maclaurin polynomial for eˣ.", requiredDemands: ["procedure"] },
      { id: "series-geometric-interval-table", description: "Connect a shifted geometric power series to its radius, interval, and endpoint behavior.", requiredDemands: ["representation"] },
      { id: "series-alternating-error", description: "Justify an alternating-series approximation error using the first omitted term.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "Every derivative of eˣ equals 1 at x=0, so its degree-three Maclaurin polynomial is P₃(x)=1+x+x²/2+x³/6. Thus P₃(0.2)=1.2213 to four decimal places.",
    exampleSteps: ["Use the Taylor coefficient rule f⁽ᵏ⁾(0)/k!: the first four coefficients are 1, 1, 1/2, and 1/6.", "Write P₃(x)=1+x+x²/2+x³/6.", "Substitute x=0.2: 1+0.2+0.04/2+0.008/6=1.221333…. ", "Round the polynomial value to 1.2213. It approximates e⁰·²; a separate remainder estimate is needed to bound its error."],
    questions: [
      choice(1, "series-maclaurin-approximation", "procedure", "For f(x)=eˣ, f⁽ᵏ⁾(0)=1 for every k. Use P₃(x)=Σ from k=0 to 3 of f⁽ᵏ⁾(0)xᵏ/k!. What is P₃(0.2), rounded to four decimals?", ["1.2480", "1.2213", "1.2200", "0.2213"], "1.2213", "Include the constant term and divide the quadratic and cubic terms by 2! and 3!.", "P₃(x)=1+x+x²/2+x³/6. At 0.2 this is 1+0.2+0.02+0.001333…=1.221333…, which rounds to 1.2213.", "Omitting factorial denominators or the constant term in a Maclaurin polynomial."),
      choice(2, "series-maclaurin-approximation", "procedure", "All derivatives of eˣ at 0 equal 1. Build its degree-three Maclaurin polynomial using coefficient f⁽ᵏ⁾(0)/k!, and evaluate it at x=0.3 to four decimals.", ["1.3450", "1.4170", "1.3495", "0.3495"], "1.3495", "The cubic term is 0.3³/6, not 0.3³.", "The polynomial is 1+x+x²/2+x³/6. Substitution gives 1+0.3+0.045+0.0045=1.3495.", "Evaluating a geometric polynomial instead of a Taylor polynomial."),
      table(3, "series-geometric-interval-table", "Consider Σ from n=0 to ∞ of ((x−2)/3)ⁿ. Which row correctly gives its convergence radius, real interval of convergence, and endpoint behavior?", ["Radius", "Interval", "Behavior at endpoints"], [["3", "[−1,5]", "Both converge"], ["2", "(−2,2)", "Both diverge"], ["3", "(−1,5)", "Both diverge"], ["3", "(−3,3)", "Left endpoint converges"]], 2, "Apply |(x−2)/3|<1, then inspect the terms at x=−1 and x=5.", "The inequality gives |x−2|<3, hence −1<x<5 and radius 3. At x=−1 the terms are (−1)ⁿ, and at x=5 they are 1; neither tends to zero, so both endpoint series diverge.", "Using the center as the radius or automatically including endpoints."),
      table(4, "series-geometric-interval-table", "For Σ from n=0 to ∞ of ((x+1)/2)ⁿ, select the correct convergence information.", ["Radius", "Real interval", "Endpoint check"], [["2", "(−3,1)", "Terms fail to approach zero at both endpoints"], ["1", "(−1,1)", "Both endpoints converge"], ["2", "[−3,1]", "Alternating terms always imply convergence"], ["2", "(−2,2)", "Only x=2 diverges"]], 0, "The center is −1. Translate the condition |x+1|<2 into an interval.", "Solving −2<x+1<2 gives −3<x<1. At x=−3 the terms alternate between ±1; at x=1 they equal 1. Since the terms do not tend to zero, neither endpoint is included.", "Confusing alternation with convergence when term magnitudes do not decrease to zero."),
      choice(5, "series-alternating-error", "reasoning", "Approximate S=1−1/2+1/3−1/4+… using its first 4 terms. The term magnitudes decrease to 0. Which is the first-omitted-term bound supplied directly by the alternating-series error theorem?", ["abs(S−S₄)≤1/4", "abs(S−S₄)≤1/5", "abs(S−S₄)=0", "abs(S−S₄)≤1/6"], "abs(S−S₄)≤1/5", "The theorem uses the first term that was omitted, here the fifth term.", "The decreasing positive magnitudes 1/n approach zero, so the theorem applies. The first omitted magnitude is 1/5, giving abs(S−S₄)≤1/5. A smaller bound such as 1/6 does not follow from this theorem alone.", "Using the last included or second omitted term instead of the first omitted term."),
      choice(6, "series-alternating-error", "reasoning", "For the alternating harmonic series S=Σ from n=1 to ∞ of (−1)ⁿ⁺¹/n, use the first 9 terms. Which bound is the first-omitted-term bound supplied directly by the alternating-series error theorem?", ["abs(S−S₉)≤1/9", "abs(S−S₉)≤1/11", "abs(S−S₉)≤1/10", "abs(S−S₉)=0"], "abs(S−S₉)≤1/10", "After n=9, the next magnitude is 1/10. Check that 1/n decreases to zero.", "Because 1/n decreases to zero and signs alternate, the error after nine terms is at most the tenth term's magnitude, 1/10.", "Thinking any smaller omitted term provides the theorem's guaranteed bound."),
    ],
    remainingGaps: ["The AP Calculus BC series unit has 15 topics; six questions do not establish full unit coverage.", "Integral, direct/limit comparison, ratio, p-series, and absolute-versus-conditional convergence tests.", "General Taylor centers and functions, Lagrange remainder bounds, power-series differentiation/integration, and nongeometric endpoint tests.", "Choosing among competing convergence tests and writing a complete free-response justification."],
  },
  {
    lessonSlug: "g12-differential-equations",
    objectives: [
      { id: "differential-exponential-ivp", description: "Solve a separable exponential differential equation and apply its initial condition.", requiredDemands: ["procedure"] },
      { id: "differential-slope-table", description: "Evaluate a slope rule across coordinate data to identify a valid slope table.", requiredDemands: ["representation"] },
      { id: "differential-euler-steps", description: "Apply two Euler steps using updated coordinates and slopes (BC extension).", requiredDemands: ["application"] },
    ],
    legacyObjectives: {},
    example: "Solve dy/dx=2y with y(0)=3: separating gives ln|y|=2x+C, so the initial condition selects y=3e²ˣ.",
    exampleSteps: ["The nonzero initial value allows a nonzero solution branch; separate as dy/y=2dx.", "Integrate to obtain ln|y|=2x+C and write the exponential family y=Ae²ˣ.", "Apply y(0)=3: A·e⁰=A=3, so y=3e²ˣ.", "Differentiate: y′=6e²ˣ=2(3e²ˣ)=2y, and check y(0)=3."],
    questions: [
      choice(1, "differential-exponential-ivp", "procedure", "Solve dy/dx=2y subject to y(0)=3.", ["y=2e³ˣ", "y=3e²ˣ", "y=2x+3", "y=e²ˣ+2"], "y=3e²ˣ", "Separate dy/y=2dx, then use the initial value to find the exponential multiplier.", "Integration yields ln|y|=2x+C, so y=Ae²ˣ. Setting x=0 gives A=3; differentiating 3e²ˣ returns 2y.", "Putting the initial value into the exponent or adding it after exponentiation."),
      choice(2, "differential-exponential-ivp", "procedure", "Find the solution of dy/dx=−3y with y(0)=5.", ["y=−3e⁵ˣ", "y=5e³ˣ", "y=−3x+5", "y=5e⁻³ˣ"], "y=5e⁻³ˣ", "The negative rate constant gives an exponential with exponent −3x.", "Separating and integrating gives y=Ae⁻³ˣ. The initial condition requires A=5, and its derivative −15e⁻³ˣ equals −3y.", "Replacing exponential decay with a linear function or ignoring the negative rate."),
      table(3, "differential-slope-table", "The differential equation is y′=x−y. Which table row gives the slopes at all three listed points?", ["Slope at (0,1)", "Slope at (1,1)", "Slope at (2,1)"], [["1", "0", "−1"], ["−1", "0", "1"], ["0", "1", "2"], ["−1", "−1", "−1"]], 1, "Substitute both coordinates into x−y at every point.", "The slopes are 0−1=−1, 1−1=0, and 2−1=1. They describe falling, horizontal, and rising local solution segments respectively.", "Reversing x−y or assuming a fixed y means a fixed slope."),
      table(4, "differential-slope-table", "For y′=2x+y, choose the correct slope row for the three points shown.", ["Slope at (0,−1)", "Slope at (1,−1)", "Slope at (2,−1)"], [["1", "3", "5"], ["−1", "0", "1"], ["−1", "1", "3"], ["0", "2", "4"]], 2, "Include the negative y-coordinate when evaluating 2x+y.", "The evaluations are 2·0−1=−1, 2·1−1=1, and 2·2−1=3. Each slope belongs to the specified coordinate point.", "Ignoring y or forgetting the factor 2 on x."),
      choice(5, "differential-euler-steps", "application", "Use Euler's method for y′=x+y, y(0)=1, with step size h=0.5. After two steps, what is the approximation to y(1)?", ["2", "2.5", "3", "1.5"], "2.5", "After reaching (0.5,1.5), recompute the slope instead of reusing the initial slope.", "First slope=0+1=1, so y₁=1+0.5·1=1.5 at x=0.5. The new slope is 0.5+1.5=2, giving y₂=1.5+0.5·2=2.5 at x=1.", "Using the initial slope for every step or treating an approximation as the exact solution."),
      choice(6, "differential-euler-steps", "application", "Approximate y(1) with two Euler steps for y′=x−y, y(0)=2, and h=0.5.", ["0", "0.5", "0.75", "1"], "0.75", "The first step reaches (0.5,1); evaluate x−y there for the second step.", "At (0,2), slope=−2, so y₁=2+0.5·(−2)=1. At (0.5,1), slope=−0.5, so y₂=1+0.5·(−0.5)=0.75.", "Failing to update both x and y when calculating the next slope."),
    ],
    remainingGaps: ["Actual graphical slope fields and matching entire solution curves rather than local numerical slopes.", "Nonlinear separable equations, solution-domain restrictions, equilibrium solutions, and logistic models.", "Justifying whether Euler approximations overestimate or underestimate from concavity."],
  },
];
