import type { CognitiveDemand, DepthQuestion, LessonDepthPack, QuestionEvidence } from "./curriculum-depth-types.ts";
import type { GraphChoicePlot } from "./question-interactions.ts";

function ev(objectiveId: string, demand: CognitiveDemand, representation: QuestionEvidence["representation"], misconception: string): QuestionEvidence {
  return { objectiveId, demand, representation, difficulty: 2, misconception, variantFamily: `${objectiveId}-variants` };
}
function choice(n: number, objective: string, demand: CognitiveDemand, prompt: string, choices: string[], answer: string, hint: string, explanation: string, misconception: string): DepthQuestion {
  return { id: `d2-q${n}`, prompt, choices, answer, hint, explanation, interaction: "four-choice", evidence: ev(objective, demand, demand === "procedure" ? "symbolic" : "verbal", misconception) };
}
function table(n: number, objective: string, prompt: string, columns: string[], cells: string[][], correct: number, hint: string, explanation: string, misconception: string): DepthQuestion {
  const rows = cells.map((row, i) => ({ value: String.fromCharCode(65 + i), cells: row }));
  return { id: `d2-q${n}`, prompt, answer: rows[correct].value, choices: rows.map((r) => r.value), hint, explanation, interaction: "table-choice", interactionConfig: { kind: "table-choice", columns, rows }, evidence: ev(objective, "representation", "table", misconception) };
}
function graph(n: number, objective: string, prompt: string, plots: GraphChoicePlot[], correct: number, hint: string, explanation: string, misconception: string): DepthQuestion {
  return { id: `d2-q${n}`, prompt, answer: plots[correct].value, choices: plots.map((p) => p.value), hint, explanation, interaction: "graph-choice", interactionConfig: { kind: "graph-choice", xMin: 0, xMax: 2 * Math.PI, yMin: -5, yMax: 5, plots }, evidence: ev(objective, "representation", "graph", misconception) };
}

export const round2AdvancedDepthPacks: LessonDepthPack[] = [
  {
    lessonSlug: "g10-similarity-proofs",
    objectives: [
      { id: "similarity-parallel-length", description: "Use the small-to-whole side ratio in a triangle with an interior parallel segment.", requiredDemands: ["procedure"] },
      { id: "similarity-candidate-sides", description: "Compare a table of candidate triangle side lengths using the SSS similarity criterion.", requiredDemands: ["representation"] },
      { id: "similarity-converse-parallel", description: "Decide whether a side-dividing segment is parallel by comparing corresponding part ratios.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: { q3: "similarity-parallel-length" },
    example: "In triangle ABC, D lies on AB and E on AC, with DE parallel to BC. If AD=5, AB=12, and AC=18, then AE=7.5.",
    exampleSteps: ["Parallel lines give equal corresponding angles, so triangles ADE and ABC are similar by AA.", "Match small-to-whole sides: AD/AB=AE/AC, hence 5/12=AE/18.", "Multiply by 18 to get AE=18·5/12=7.5.", "Check that AE<AC and AD<AB, as required for the interior points."],
    questions: [
      choice(1, "similarity-parallel-length", "procedure", "In triangle ABC, interior points D on AB and E on AC satisfy DE∥BC. AD=6, AB=15, and AC=20. Find AE.", ["8", "9", "12", "50"], "8", "Use AD/AB=AE/AC; AB is the whole side, not DB.", "AA similarity gives AE/20=6/15. Thus AE=8, leaving EC=12.", "Mixing a whole-side ratio with a part-to-part ratio."),
      choice(2, "similarity-parallel-length", "procedure", "D and E are interior points on AB and AC of triangle ABC, with DE∥BC. If AD=8, AB=12, and AC=21, what is AE?", ["7", "14", "18", "31.5"], "14", "The small-to-whole scale factor is 8/12=2/3.", "Corresponding sides satisfy AE/21=8/12. Therefore AE=21·2/3=14.", "Inverting the scale factor and obtaining a small side larger than the whole side."),
      table(3, "similarity-candidate-sides", "A triangle has side lengths 6, 9, and 12. Which candidate triangle in the table is similar to it? Compare sides in increasing order.", ["Shortest side", "Middle side", "Longest side"], [["4", "6", "8"], ["4", "6", "9"], ["4", "7", "8"], ["6", "9", "13"]], 0, "All three ratios must use the same scale factor; two matching ratios are insufficient.", "For sides 4,6,8, the ratios 4/6, 6/9, and 8/12 all equal 2/3. The other candidates have at least one unequal ratio.", "Checking only two side pairs for SSS similarity."),
      table(4, "similarity-candidate-sides", "A triangle has side lengths 5, 7, and 8. Which candidate side-length row gives a similar triangle?", ["Shortest side", "Middle side", "Longest side"], [["10", "14", "18"], ["15", "20", "24"], ["15", "21", "24"], ["10", "12", "16"]], 2, "Divide each candidate's sides by 5, 7, and 8 in matching order.", "The row 15,21,24 multiplies all three reference sides by 3. Every other row breaks at least one required ratio.", "Assuming a similar appearance follows from one matching side ratio."),
      choice(5, "similarity-converse-parallel", "reasoning", "In triangle ABC, D is inside AB and E inside AC. AD=4, DB=6, AE=6, and EC=9. Does this information imply DE∥BC?", ["Yes: AD/DB=AE/EC=2/3, so the converse proportionality theorem applies.", "Yes: AD=AE.", "No: the four lengths are not all equal.", "No: similarity requires the triangles to have equal size."], "Yes: AD/DB=AE/EC=2/3, so the converse proportionality theorem applies.", "Compare the two part-to-part ratios using matching near-vertex and remaining segments.", "AD/DB=4/6=2/3 and AE/EC=6/9=2/3. Interior points dividing two triangle sides proportionally determine a segment parallel to the third side.", "Confusing proportional lengths with equal lengths."),
      choice(6, "similarity-converse-parallel", "reasoning", "In triangle PQR, S lies inside PQ and T inside PR. PS=3, SQ=5, PT=6, and TR=9. Is ST parallel to QR?", ["Yes, because 6 is twice 3.", "Yes, because both points lie on triangle sides.", "No: 3/5 differs from 6/9, so the required proportional division fails.", "No, because a triangle cannot contain a parallel segment."], "No: 3/5 differs from 6/9, so the required proportional division fails.", "A common multiplier must apply to both near and far segments.", "PS/SQ=3/5=0.6, while PT/TR=6/9=2/3. These unequal ratios contradict the proportionality that parallelism would require.", "Using one doubled segment without checking the corresponding second segment."),
    ],
    remainingGaps: ["Student-authored angle-to-ratio proofs, similarity with overlapping triangles, and indirect measurement with uncertainty.", "Similarity-derived area/volume relationships and right-triangle geometric-mean proofs."],
  },
  {
    lessonSlug: "g10-conditional-probability",
    objectives: [
      { id: "conditional-without-replacement", description: "Update favorable and total counts after a known draw without replacement.", requiredDemands: ["procedure"] },
      { id: "conditional-count-table", description: "Compare conditional probabilities computed from group-count table rows.", requiredDemands: ["representation"] },
      { id: "conditional-reverse-counts", description: "Reverse a condition by restricting to a known outcome across two sources.", requiredDemands: ["application"] },
    ],
    legacyObjectives: {},
    example: "A bag contains 7 red and 5 blue counters. Given that the first counter was red and was not replaced, the chance the next is red is 6/11.",
    exampleSteps: ["Start with 7 red counters among 12 counters.", "The known first draw removes one red counter, leaving 6 red and 5 blue.", "Restrict the second draw to the 11 remaining counters.", "The conditional probability is 6 favorable remaining counters divided by 11 total, or 6/11."],
    questions: [
      choice(1, "conditional-without-replacement", "procedure", "A bag has 5 red and 3 blue counters. Given that one red counter was drawn and not replaced, what is the probability the next counter is red?", ["5/8", "4/8", "4/7", "5/7"], "4/7", "Update both the red count and the total after the known first draw.", "Removing a red counter leaves 4 red among 7 counters. The conditional probability of another red is 4/7.", "Updating only the denominator or assuming replacement."),
      choice(2, "conditional-without-replacement", "procedure", "There are 6 green and 4 yellow tiles. A known green tile is removed permanently. What is the probability the next random tile is green?", ["6/10", "5/10", "6/9", "5/9"], "5/9", "One favorable tile and one tile overall have already been removed.", "The remaining collection contains 5 green and 4 yellow tiles, so the required probability is 5/(5+4)=5/9.", "Using the original favorable count after a favorable tile was removed."),
      table(3, "conditional-count-table", "For each group, select a member uniformly from that group. Which row gives a conditional probability of exactly 3/5 that the member prefers option X?", ["Group", "Members who prefer X", "Group total"], [["Art", "18", "30"], ["Band", "20", "40"], ["Chess", "10", "25"], ["Drama", "15", "20"]], 0, "Divide each row's preference count by that same row's group total.", "Art has 18/30=3/5. The other probabilities are 1/2, 2/5, and 3/4, so only Art meets the target.", "Comparing raw counts instead of probabilities within each conditioned group."),
      table(4, "conditional-count-table", "A person is chosen uniformly within one row's group. Which group has P(uses transit given this group)=2/3?", ["Group", "Transit users", "Group total"], [["North", "9", "18"], ["South", "16", "24"], ["East", "15", "30"], ["West", "12", "21"]], 1, "The known group determines the denominator; compare the four row fractions.", "South gives 16/24=2/3. North and East give 1/2, while West gives 4/7.", "Using the total across all groups when the condition specifies one group."),
      choice(5, "conditional-reverse-counts", "application", "A shipment has 60 items from factory A and 40 from B. Exactly 6 A items and 2 B items are defective. An item is selected uniformly from the defective items. What is P(from A given defective)?", ["6/60", "6/100", "6/8", "60/100"], "6/8", "The selected item is known to be defective, so count all defective items first.", "There are 6+2=8 defective items, and 6 came from A. Thus the reverse conditional probability is 6/8=0.75, not A's defect rate 6/60.", "Confusing P(defective given A) with P(A given defective)."),
      choice(6, "conditional-reverse-counts", "application", "A batch contains 80 units from X and 20 from Y. Four X units and two Y units fail inspection. A failed unit is chosen uniformly. What is the probability it came from X?", ["4/80", "4/100", "4/5", "2/3"], "2/3", "Restrict the sample space to the 4+2 failed units.", "Among six failed units, four are from X, so P(X given failed)=4/6=2/3. The original batch proportion 80/100 is different and is not the conditional probability.", "Keeping the original sample space after learning the unit failed."),
    ],
    remainingGaps: ["Three-stage conditional trees, algebraic Bayes calculations from rates, and conditions with zero probability.", "Distinguishing observed conditional association from causal effects."],
  },
  {
    lessonSlug: "g10-independence",
    objectives: [
      { id: "independent-union-calculation", description: "Combine the product rule and addition rule to calculate a union of independent events.", requiredDemands: ["procedure"] },
      { id: "independent-probability-table", description: "Test candidate probability-table rows against the independence product criterion.", requiredDemands: ["representation"] },
      { id: "independent-versus-disjoint", description: "Use positive probabilities to explain why disjoint events are not independent.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "For independent events with P(A)=0.5 and P(B)=0.4, P(A∩B)=0.20 and P(A∪B)=0.70.",
    exampleSteps: ["Independence gives the overlap P(A∩B)=0.5·0.4=0.20.", "The addition rule is P(A∪B)=P(A)+P(B)−P(A∩B).", "Substitute to get 0.5+0.4−0.2=0.7.", "The union exceeds either single probability but remains below 1, consistent with its meaning."],
    questions: [
      choice(1, "independent-union-calculation", "procedure", "A and B are independent, with P(A)=0.4 and P(B)=0.3. Find P(A∪B).", ["0.12", "0.58", "0.70", "0.88"], "0.58", "Compute the overlap by multiplication before applying the addition rule.", "P(A∩B)=0.4·0.3=0.12. Therefore P(A∪B)=0.4+0.3−0.12=0.58.", "Adding independent probabilities as though independence meant no overlap."),
      choice(2, "independent-union-calculation", "procedure", "C and D are independent. P(C)=0.6 and P(D)=0.2. What is P(C∪D)?", ["0.12", "0.80", "0.68", "0.92"], "0.68", "Independent events can overlap; subtract that overlap once.", "The product rule gives overlap 0.6·0.2=0.12, so the union probability is 0.6+0.2−0.12=0.68.", "Treating independent events as mutually exclusive."),
      table(3, "independent-probability-table", "Each row describes a valid pair of events. Which row describes independent events?", ["P(A)", "P(B)", "P(A∩B)"], [["0.4", "0.5", "0.1"], ["0.4", "0.5", "0.2"], ["0.4", "0.5", "0.4"], ["0.4", "0.5", "0"]], 1, "Calculate P(A)P(B) and compare it with the listed overlap.", "The required overlap is 0.4·0.5=0.2. Only the second row satisfies the product criterion.", "Deciding independence from the marginal probabilities alone."),
      table(4, "independent-probability-table", "Which candidate probability row satisfies independence?", ["P(C)", "P(D)", "P(C∩D)"], [["0.3", "0.4", "0.2"], ["0.3", "0.4", "0.3"], ["0.3", "0.4", "0"], ["0.3", "0.4", "0.12"]], 3, "Independence requires the third entry to equal the product of the first two.", "0.3·0.4=0.12, so the row with overlap 0.12 is independent. A zero overlap would make these positive-probability events disjoint, not independent.", "Selecting zero overlap as a sign of independence."),
      choice(5, "independent-versus-disjoint", "reasoning", "A and B are disjoint with P(A)=0.2 and P(B)=0.3. Are they independent?", ["Yes, because they cannot occur together.", "No: P(A∩B)=0 but P(A)P(B)=0.06.", "Yes, because both probabilities are less than 1.", "There is not enough information to find the overlap."], "No: P(A∩B)=0 but P(A)P(B)=0.06.", "Disjointness fixes the overlap at zero; compare that with the product criterion.", "Disjoint events have P(A∩B)=0. Since 0.2·0.3=0.06≠0, these events fail independence. Learning A occurred rules out B.", "Equating 'cannot both happen' with 'one gives no information about the other'."),
      choice(6, "independent-versus-disjoint", "reasoning", "For one fair coin toss, H means heads and T means tails. Which statement correctly analyzes their independence?", ["They are independent because the coin is fair.", "They are independent because each has probability 1/2.", "They are dependent: P(H∩T)=0 differs from (1/2)(1/2)=1/4.", "They can occur together with probability 1/4 on this one toss."], "They are dependent: P(H∩T)=0 differs from (1/2)(1/2)=1/4.", "The events refer to the same single toss, not outcomes from two separate tosses.", "A single toss cannot be both heads and tails. The actual overlap is 0, whereas independence would require 1/4; therefore H and T are dependent.", "Importing independence of separate tosses into mutually exclusive outcomes of one toss."),
    ],
    remainingGaps: ["Independence from two-way count data, multiple-event independence, and sampling with versus without replacement.", "The zero-probability exception to the statement about disjoint events."],
  },
  {
    lessonSlug: "g10-categorical-data",
    objectives: [
      { id: "categorical-rate-difference", description: "Calculate a signed percentage-point difference between conditional rates in unequal-sized groups.", requiredDemands: ["procedure"] },
      { id: "categorical-count-comparison", description: "Compare within-group rates using a table of favorable and unfavorable counts.", requiredDemands: ["representation"] },
      { id: "categorical-association-limit", description: "Interpret an observational difference in categorical rates without inferring causation.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "21 of 30 members in A and 18 of 40 in B support a proposal. Their support rates are 70% and 45%, so A−B=25 percentage points.",
    exampleSteps: ["Use each group's own total: A's support rate is 21/30=0.70.", "B's support rate is 18/40=0.45.", "Subtract in the requested direction: 100·(0.70−0.45)=25 percentage points.", "The rate comparison is meaningful across unequal group sizes; an observational difference alone does not establish a cause."],
    questions: [
      choice(1, "categorical-rate-difference", "procedure", "A has 18 supporters among 30 members; B has 20 among 50. What is A's support rate minus B's in percentage points?", ["−2 percentage points", "2 percentage points", "20 percentage points", "50 percentage points"], "20 percentage points", "Convert each within-group fraction to a percent before subtracting.", "A's rate is 60% and B's is 40%. Their signed difference A−B is 20 percentage points, not the raw-count difference −2.", "Comparing raw counts or confusing percentage points with relative percent change."),
      choice(2, "categorical-rate-difference", "procedure", "Group C has 24 yes responses out of 40; D has 45 out of 60. Find C's yes rate minus D's, in percentage points.", ["−21 percentage points", "−15 percentage points", "15 percentage points", "−25 percentage points"], "−15 percentage points", "The two rates are 24/40 and 45/60; preserve the requested order C−D.", "C has a 60% yes rate and D a 75% yes rate. Thus C−D=60%−75%=−15 percentage points.", "Losing the direction of a rate difference."),
      table(3, "categorical-count-comparison", "Which travel group has the highest proportion preferring a later start? Each row lists all members of that group.", ["Travel group", "Prefers later", "Does not prefer later"], [["Bus", "18", "12"], ["Walk", "20", "30"], ["Bike", "14", "6"], ["Car", "9", "6"]], 2, "For each row, divide 'prefers later' by the sum of that row's two counts.", "The rates are Bus 18/30=60%, Walk 20/50=40%, Bike 14/20=70%, and Car 9/15=60%. Bike has the largest rate.", "Choosing the group with the largest favorable count instead of the largest relative frequency."),
      table(4, "categorical-count-comparison", "Each program's participants answered yes or no. Which program has the highest within-program yes rate?", ["Program", "Yes", "No"], [["A", "12", "8"], ["B", "18", "22"], ["C", "21", "9"], ["D", "16", "4"]], 3, "Add yes and no to get each denominator before comparing.", "The rates are 12/20=60%, 18/40=45%, 21/30=70%, and 16/20=80%. Program D has the highest rate, although C has more yes responses.", "Using a common denominator for groups that contain different numbers of people."),
      choice(5, "categorical-association-limit", "reasoning", "An observational survey finds 60% of bus riders and 40% of walkers prefer a later school start. Which conclusion is justified by these data alone?", ["Riding a bus causes students to prefer a later start.", "Travel group and preference are associated in this surveyed sample; causation is not established.", "The groups have identical preference rates.", "Exactly 20% of bus riders changed their preference because of the bus."], "Travel group and preference are associated in this surveyed sample; causation is not established.", "The study records existing groups; it does not randomly assign travel methods.", "Different conditional rates show an association in the observed sample. Existing travel groups may differ in other ways, so the survey alone does not isolate a causal effect.", "Turning an observational rate difference into a causal treatment effect."),
      choice(6, "categorical-association-limit", "reasoning", "In a nonrandom online survey, 75% of app users and 50% of nonusers report regular exercise. Which interpretation respects the study design?", ["The app makes every user exercise more.", "The difference proves the same rates hold for all adults.", "App use and exercise are associated among respondents, but selection and confounding limit wider or causal claims.", "A 25-point gap proves there is no sampling bias."], "App use and exercise are associated among respondents, but selection and confounding limit wider or causal claims.", "Separate what the respondents show from claims about causation or a wider population.", "The sample shows unequal conditional rates. Because participation was nonrandom and app use was not assigned, selection and other group differences can affect the result; neither a population-wide estimate nor causation follows automatically.", "Assuming a large observed gap repairs nonrandom selection."),
    ],
    remainingGaps: ["Marginal and joint relative-frequency conversions, segmented bar charts, and Simpson's paradox.", "Formal inference about population associations, including chi-square procedures."],
  },
  {
    lessonSlug: "g11-rational-equations",
    objectives: [
      { id: "rational-lcd-solution", description: "Solve a multi-term rational equation by clearing denominators and checking restrictions.", requiredDemands: ["procedure"] },
      { id: "rational-candidate-record", description: "Audit candidate solution records for nonzero denominators and equality in the original equation.", requiredDemands: ["representation"] },
      { id: "rational-excluded-root", description: "Explain why an algebraic root produced after cancellation may leave the original equation with no solution.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "Solve 3/x+1/3=5/6. With x≠0, multiplying by 6x gives 18+2x=5x, so x=6.",
    exampleSteps: ["The original denominator requires x≠0.", "Multiply every term by the common denominator 6x: 18+2x=5x.", "Subtract 2x to get 18=3x, hence x=6.", "Check the original equation: 3/6+1/3=5/6, and x=6 is allowed."],
    questions: [
      choice(1, "rational-lcd-solution", "procedure", "Solve 3/x+1/2=5/4 over the real numbers, keeping x≠0.", ["2", "3", "4", "12"], "4", "Multiplying all terms by 4x produces 12+2x=5x.", "The cleared equation gives 3x=12, so x=4. Substitution gives 3/4+1/2=5/4 and does not violate the restriction.", "Multiplying only the variable-denominator term by the common denominator."),
      choice(2, "rational-lcd-solution", "procedure", "Solve 4/(x−1)+1/3=1 with x≠1.", ["5", "6", "7", "13"], "7", "Subtract 1/3 first to obtain 4/(x−1)=2/3.", "Cross-multiplying gives 12=2(x−1), hence x−1=6 and x=7. The original left side is 4/6+1/3=1.", "Solving for x−1 but reporting that value as x."),
      table(3, "rational-candidate-record", "For (x+1)/(x−1)=3/(x−1), which candidate record is an allowed solution of the original equation?", ["Candidate x", "Denominator x−1", "Left side", "Right side"], [["1", "0", "undefined", "undefined"], ["0", "−1", "−1", "−3"], ["2", "1", "3", "3"], ["4", "3", "5/3", "1"]], 2, "An allowed row needs a nonzero denominator and equal left and right values.", "Only x=2 has a nonzero denominator and both sides equal to 3. At x=1 the equation is undefined; the remaining candidates give unequal sides.", "Treating two undefined expressions as equal and therefore a valid solution."),
      table(4, "rational-candidate-record", "Which row gives a valid solution of (2x+1)/(x−3)=9/(x−3)?", ["Candidate x", "Denominator x−3", "Left side", "Right side"], [["4", "1", "9", "9"], ["3", "0", "undefined", "undefined"], ["1", "−2", "−3/2", "−9/2"], ["5", "2", "11/2", "9/2"]], 0, "Check the original quotient values, including the excluded input x=3.", "At x=4 both quotients equal 9 and the denominator is 1. The x=3 row is undefined and the other rows do not satisfy equality.", "Accepting a candidate from denominator clearing without original-equation substitution."),
      choice(5, "rational-excluded-root", "reasoning", "A student cancels (x²−4)/(x−2)=4 to get x+2=4 and reports x=2. What is the correct original solution set?", ["{2}, because cancellation permits x=2.", "No solution: the only algebraic candidate x=2 is excluded by the original denominator.", "All real numbers except 2.", "{−2,2}, because x²−4 factors."], "No solution: the only algebraic candidate x=2 is excluded by the original denominator.", "Cancellation preserves equality only on the original domain x≠2.", "For x≠2, the equation becomes x+2=4, whose only candidate is x=2. That value makes the original denominator zero, so no allowed solution remains.", "Assuming cancellation removes the original domain restriction."),
      choice(6, "rational-excluded-root", "reasoning", "For (x²−9)/(x−3)=6, simplifying leads to x+3=6. Which conclusion correctly handles the original domain?", ["x=3 is valid because the simplified expression exists there.", "x=−3 is valid because it zeros the numerator.", "Every real x works after cancellation.", "There is no solution because the only candidate x=3 makes the original denominator zero."], "There is no solution because the only candidate x=3 makes the original denominator zero.", "First state x≠3, then compare the simplified equation's candidate with that restriction.", "Factoring gives (x−3)(x+3)/(x−3)=6 for x≠3. The resulting candidate x=3 is excluded, while x=−3 gives 0 rather than 6.", "Treating a removable hole as an allowed original input."),
    ],
    remainingGaps: ["Rational equations with two distinct variable denominators and multiple permitted roots.", "Rate/work word problems and distinguishing identities from inconsistent rational equations."],
  },
  {
    lessonSlug: "g11-exponential-log-equations",
    objectives: [
      { id: "exponential-log-isolation", description: "Isolate time in an exponential equation using a natural logarithm and a stated rounding rule.", requiredDemands: ["procedure"] },
      { id: "log-candidate-domain-table", description: "Inspect candidate arguments and products to retain valid roots of a sum-of-logarithms equation.", requiredDemands: ["representation"] },
      { id: "log-sum-counterexample", description: "Reject a false logarithm-of-a-sum rule with a concrete positive-input counterexample.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "For 2e^(0.3t)=10, divide by 2 and take ln: 0.3t=ln5, so t=ln5/0.3≈5.36.",
    exampleSteps: ["Divide the equation by 2 to isolate e^(0.3t)=5.", "Apply the natural logarithm to both positive sides: 0.3t=ln5.", "Divide by 0.3; using ln5≈1.609438 gives t≈5.364793.", "Round only the final time to two decimals: t≈5.36. The unrounded value makes e^(0.3t) exactly 5."],
    questions: [
      choice(1, "exponential-log-isolation", "procedure", "Solve 5e^(0.4t)=20 for t. Use ln4≈1.386294 and round t to two decimals.", ["0.55", "1.39", "3.47", "10.00"], "3.47", "After dividing by 5, the logarithm gives 0.4t=ln4.", "Isolating t gives ln4/0.4=1.386294/0.4=3.465735, which rounds to 3.47.", "Multiplying by the rate constant instead of dividing by it."),
      choice(2, "exponential-log-isolation", "procedure", "Find t in 3e^(0.5t)=12. Use ln4≈1.386294 and give t to two decimals.", ["0.69", "2.77", "4.00", "8.00"], "2.77", "The ratio 12/3 equals 4, so solve 0.5t=ln4.", "After taking ln, t=ln4/0.5=2.772588, which rounds to 2.77. The multiplier 3 is removed before taking the logarithm.", "Taking ln of the rate coefficient rather than isolating the exponential."),
      table(3, "log-candidate-domain-table", "For log₂(x−1)+log₂(x−3)=3, both arguments must be positive and their product must equal 8. Which candidate row satisfies both requirements?", ["x", "x−1", "x−3", "Product"], [["−1", "−2", "−4", "8"], ["3", "2", "0", "0"], ["4", "3", "1", "3"], ["5", "4", "2", "8"]], 3, "A positive product alone is not enough: each separate logarithm argument must be positive.", "At x=5 the arguments are 4 and 2, both positive, and their product is 8. The algebraic candidate −1 also has product 8 but invalid negative arguments.", "Allowing two negative logarithm arguments because their product is positive."),
      table(4, "log-candidate-domain-table", "For log₂x+log₂(x−2)=3, select the candidate satisfying positive arguments and product 8.", ["x", "First argument x", "Second argument x−2", "Product"], [["−2", "−2", "−4", "8"], ["4", "4", "2", "8"], ["2", "2", "0", "0"], ["3", "3", "1", "3"]], 1, "The original domain requires x>2, in addition to the product equation.", "At x=4 the arguments are 4 and 2 and log₂4+log₂2=2+1=3. The x=−2 product root is outside the logarithms' domain.", "Solving the product equation but omitting the original logarithmic domain."),
      choice(5, "log-sum-counterexample", "reasoning", "A student claims log₂(x+4)=log₂x+2 for every x>0. Which counterexample correctly disproves the claim?", ["At x=4, the left side is 3 but the right side is 4.", "At x=4, both sides equal 4.", "At x=0, both sides are defined and unequal.", "No counterexample exists because logarithms distribute over addition."], "At x=4, the left side is 3 but the right side is 4.", "Choose a positive x that makes x and x+4 powers of 2.", "At x=4, log₂8=3 while log₂4+2=2+2=4. The sum rule is false; log₂x+log₂4 instead equals log₂(4x).", "Distributing a logarithm over addition instead of using its product rule."),
      choice(6, "log-sum-counterexample", "reasoning", "Is log₃(x+3)=log₃x+1 an identity for all x>0? Choose a valid check.", ["Yes: addition inside a logarithm becomes addition outside.", "Yes: taking x=3 gives log₃6=2.", "No: at x=3, the left side is log₃6 but the right side is log₃9=2.", "No: x=−3 is an allowed positive input giving a counterexample."], "No: at x=3, the left side is log₃6 but the right side is log₃9=2.", "Replace 1 with log₃3 to see that the right side is log₃(3x), not log₃(x+3).", "At the valid input x=3, the arguments 6 and 9 differ. Since log₃ is strictly increasing, log₃6≠log₃9, so the asserted identity fails.", "Using the product law as though it were a law for sums."),
    ],
    remainingGaps: ["Equations requiring numerical root finding, substitutions that create quadratic exponentials, and changing logarithm bases.", "Model fitting, half-life/doubling-time comparisons, and extraneous roots from more complex log transformations."],
  },
  {
    lessonSlug: "g11-trig-graphs",
    objectives: [
      { id: "trig-frequency-from-period", description: "Calculate positive angular frequency B from a desired sine/cosine period.", requiredDemands: ["procedure"] },
      { id: "trig-graph-features", description: "Compare plotted sinusoidal candidates by amplitude, midline, period, and initial direction.", requiredDemands: ["representation"] },
      { id: "trig-model-extremum-time", description: "Determine the first minimum time in a positive-amplitude cosine model starting at a maximum.", requiredDemands: ["application"] },
    ],
    legacyObjectives: {},
    example: "For y=4sin(Bx)+1 with B>0 and period 6π, B=1/3. The graph oscillates around 1 between −3 and 5.",
    exampleSteps: ["Use the period formula T=2π/B for positive B.", "Set 6π=2π/B and solve B=2π/(6π)=1/3.", "The coefficient 4 gives amplitude 4 and the constant 1 gives midline 1.", "Adding and subtracting amplitude from the midline gives the range [−3,5]."],
    questions: [
      choice(1, "trig-frequency-from-period", "procedure", "For y=3sin(Bx)−2 with B>0, what B gives period 4π?", ["0.5", "2", "4", "6"], "0.5", "Rearrange T=2π/B to B=2π/T.", "B=2π/(4π)=1/2=0.5. Amplitude and vertical shift do not change the period.", "Using the period itself as the angular frequency."),
      choice(2, "trig-frequency-from-period", "procedure", "A model y=2cos(Bx)+1 has B>0 and required period π/2. Find B.", ["0.25", "0.5", "2", "4"], "4", "Divide 2π by π/2; dividing by a fraction multiplies by its reciprocal.", "B=2π/(π/2)=4, so cos(4x) repeats after π/2.", "Inverting the frequency-period relationship incorrectly."),
      graph(3, "trig-graph-features", "Select the plotted curve with amplitude 2, midline y=1, and period π that crosses its midline upward at x=0. The x-axis uses radians.", [
        { value: "A", optionLabel: "A", label: "At x=0, y=1 and rising; maximum 3 at x=π/2; minimum −1 at x=3π/2; repeats every 2π.", kind: "sine", a: 2, b: 1, k: 1 },
        { value: "B", optionLabel: "B", label: "At x=0, y=1 and rising; maximum 3 at x=π/4; minimum −1 at x=3π/4; repeats every π.", kind: "sine", a: 2, b: 2, k: 1 },
        { value: "C", optionLabel: "C", label: "At x=0, y=1 and rising; maximum 2 at x=π/4; minimum 0 at x=3π/4; repeats every π.", kind: "sine", a: 1, b: 2, k: 1 },
        { value: "D", optionLabel: "D", label: "At x=0, y=1 and falling; minimum −1 at x=π/4; maximum 3 at x=3π/4; repeats every π.", kind: "sine", a: -2, b: 2, k: 1 },
      ], 1, "Check peak 3, trough −1, one full cycle in π radians, and an increasing midline crossing at x=0.", "Graph B represents 2sin(2x)+1: amplitude 2, midline 1, and period 2π/2=π. Its slope at x=0 is positive. A has twice the period, C half the amplitude, and D the opposite initial direction.", "Matching only amplitude while overlooking period or direction."),
      graph(4, "trig-graph-features", "Choose the plotted sinusoid with amplitude 3, midline y=−1, and period 2π that begins at its maximum when x=0. Angles are in radians.", [
        { value: "A", optionLabel: "A", label: "Starts at maximum y=2 when x=0; minimum y=−4 at x=π; returns to the maximum at x=2π.", kind: "cosine", a: 3, b: 1, k: -1 },
        { value: "B", optionLabel: "B", label: "Starts at maximum y=2 when x=0; minimum y=−4 at x=π/2; returns to the maximum at x=π.", kind: "cosine", a: 3, b: 2, k: -1 },
        { value: "C", optionLabel: "C", label: "Starts at maximum y=1 when x=0; minimum y=−3 at x=π; returns to the maximum at x=2π.", kind: "cosine", a: 2, b: 1, k: -1 },
        { value: "D", optionLabel: "D", label: "Starts at maximum y=4 when x=0; minimum y=−2 at x=π; returns to the maximum at x=2π.", kind: "cosine", a: 3, b: 1, k: 1 },
      ], 0, "The desired maximum is 2, minimum −4, and the next maximum is 2π radians later.", "Graph A is 3cos x−1, with range [−4,2] and period 2π. The others change frequency, amplitude, or midline.", "Confusing the maximum value with amplitude when the midline is not zero."),
      choice(5, "trig-model-extremum-time", "application", "A tide model is h(t)=3cos(πt/6)+5 meters, with t in hours after a high tide at t=0. When does the model first reach its minimum for t>0?", ["3 hours", "6 hours", "9 hours", "12 hours"], "6 hours", "Cosine first reaches −1 when its angle reaches π.", "Set πt/6=π to obtain t=6 hours. The model's period is 12 hours, so a minimum occurs half a period after the initial maximum.", "Using the full period as the time from a maximum to the next minimum."),
      choice(6, "trig-model-extremum-time", "application", "A rotating light's height is H(t)=2cos(πt/4)+4 meters, with t in seconds. It starts at its highest point at t=0. Find its first minimum time after starting.", ["2 seconds", "4 seconds", "6 seconds", "8 seconds"], "4 seconds", "The first minimum requires cosine's argument to equal π.", "Solving πt/4=π gives t=4 seconds. The full rotation period is 8 seconds, and the lowest height is 4−2=2 meters.", "Mixing the lowest height with the time at which it occurs."),
    ],
    remainingGaps: ["Phase-shifted models, negative angular frequencies, tangent graphs, and fitting sinusoidal data.", "Interactions that let learners drag a graph and observe parameter changes."],
  },
  {
    lessonSlug: "g11-normal-distributions",
    objectives: [
      { id: "normal-inverse-standardize", description: "Recover a raw measurement from a supplied z-score, mean, and standard deviation.", requiredDemands: ["procedure"] },
      { id: "normal-parameter-records", description: "Compare model-parameter table rows by standardizing their cutoff values.", requiredDemands: ["representation"] },
      { id: "normal-interval-probability", description: "Calculate a normal interval probability from standardized endpoints and supplied cumulative areas.", requiredDemands: ["application"] },
    ],
    legacyObjectives: {},
    example: "For a normal model with μ=60 and σ=6, z=1.5 corresponds to x=60+1.5·6=69.",
    exampleSteps: ["Start with z=(x−μ)/σ and identify μ=60, σ=6, z=1.5.", "Multiply by σ to obtain x−60=1.5·6=9.", "Add the mean to obtain x=69.", "Check (69−60)/6=1.5; the measurement is 1.5 standard deviations above the mean."],
    questions: [
      choice(1, "normal-inverse-standardize", "procedure", "A normal model has mean 50 and standard deviation 8. Which raw value has z=1.5?", ["38", "51.5", "58", "62"], "62", "Rearrange the z-score formula as x=μ+zσ.", "x=50+1.5·8=62. The positive z-score places x above the mean.", "Adding the z-score directly to the mean without converting SD units."),
      choice(2, "normal-inverse-standardize", "procedure", "For mean 100 and standard deviation 12, find the raw value corresponding to z=−1.25.", ["85", "88", "98.75", "115"], "85", "The negative z-score represents a decrease of 1.25 standard deviations.", "x=100+(−1.25)·12=100−15=85. Standardizing again gives −15/12=−1.25.", "Dropping the sign when converting a standardized score to a raw measurement."),
      table(3, "normal-parameter-records", "All rows describe normal models. Given P(Z≤1)=0.8413, which row has P(X≤cutoff)=0.8413?", ["Mean μ", "SD σ", "Cutoff"], [["100", "10", "110"], ["100", "20", "110"], ["100", "10", "90"], ["100", "10", "120"]], 0, "The desired row must satisfy (cutoff−mean)/SD=1.", "The first row standardizes to (110−100)/10=1. The other rows give z=0.5, −1, and 2, so they have different cumulative probabilities.", "Comparing cutoff values without accounting for each model's standard deviation."),
      table(4, "normal-parameter-records", "Each row is a normal model. The supplied standard-normal area is P(Z≤−2)=0.0228. Which row has that probability below its cutoff?", ["Mean μ", "SD σ", "Cutoff"], [["50", "10", "40"], ["50", "5", "60"], ["50", "5", "40"], ["50", "5", "45"]], 2, "The cutoff must be exactly two standard deviations below its row's mean.", "For μ=50, σ=5, cutoff 40, z=(40−50)/5=−2. The remaining rows standardize to −1, 2, and −1.", "Ignoring the lower-tail direction or using a fixed raw offset across different SDs."),
      choice(5, "normal-interval-probability", "application", "Scores follow a normal model with μ=70 and σ=5. Find P(65<X<80). Use Φ(−1)=0.1587 and Φ(2)=0.9772, where Φ is the standard-normal cumulative probability.", ["0.1587", "0.8185", "0.9772", "1.1359"], "0.8185", "Convert the endpoints to −1 and 2, then subtract the lower cumulative area from the upper one.", "The z-scores are (65−70)/5=−1 and (80−70)/5=2. The interval probability is 0.9772−0.1587=0.8185 using the supplied rounded areas.", "Adding two cumulative probabilities or reporting just the upper cumulative area."),
      choice(6, "normal-interval-probability", "application", "A normal measurement has μ=100 and σ=10. Calculate P(85<X<110) using Φ(−1.5)=0.0668 and Φ(1)=0.8413.", ["0.0668", "0.7745", "0.8413", "0.9081"], "0.7745", "The standardized interval is −1.5<Z<1.", "The required area is Φ(1)−Φ(−1.5)=0.8413−0.0668=0.7745. Continuous distributions assign zero probability to individual endpoints, so strict versus inclusive endpoints does not change this result.", "Using the complement of an interval when the question asks for the interval itself."),
    ],
    remainingGaps: ["Finding unsupplied percentile cutoffs, normal-model diagnostics, and tail probabilities from technology.", "Comparing individual-value distributions with sampling distributions of statistics."],
  },
  {
    lessonSlug: "g12-continuity",
    objectives: [
      { id: "continuity-piecewise-parameter", description: "Solve for a parameter that makes two piecewise formulas agree at their joining point.", requiredDemands: ["procedure"] },
      { id: "continuity-profile-table", description: "Compare one-sided-limit and function-value profiles against all continuity conditions.", requiredDemands: ["representation"] },
      { id: "continuity-ivt-conclusion", description: "Apply the Intermediate Value Theorem without claiming a unique root or its exact location.", requiredDemands: ["reasoning"] },
    ],
    legacyObjectives: {},
    example: "Let f(x)=ax+2 for x<1 and f(x)=x²+4 for x≥1. Continuity at 1 requires a+2=5, so a=3.",
    exampleSteps: ["The left-hand limit at 1 from the first formula is a+2.", "The right-hand formula gives both the right-hand limit and f(1)=1²+4=5.", "Set the two values equal: a+2=5, giving a=3.", "For a=3, both one-sided limits and the function value equal 5, satisfying all continuity conditions."],
    questions: [
      choice(1, "continuity-piecewise-parameter", "procedure", "f(x)=ax+1 for x<2 and f(x)=x²−1 for x≥2. Which a makes f continuous at x=2?", ["0", "1", "2", "3"], "1", "Match the left limit 2a+1 to the right-hand value 3.", "The right formula gives f(2)=3. Equating 2a+1=3 yields a=1; both one-sided limits then match f(2).", "Equating coefficients rather than evaluating both pieces at the joining point."),
      choice(2, "continuity-piecewise-parameter", "procedure", "g(x)=ax−2 for x<3 and g(x)=x²+1 for x≥3. Find a so g is continuous at x=3.", ["2", "3", "4", "10"], "4", "The right-hand limit and g(3) both equal 10; the left limit is 3a−2.", "Continuity requires 3a−2=10, so 3a=12 and a=4. Both polynomial pieces are continuous on their sides, so matching at 3 completes the check.", "Using the function value 10 as the coefficient a without solving the matching equation."),
      table(3, "continuity-profile-table", "Each row describes a possible function near x=a. Which profile is continuous at a?", ["Left-hand limit", "Right-hand limit", "f(a)"], [["4", "4", "7"], ["4", "5", "4"], ["4", "4", "4"], ["4", "4", "undefined"]], 2, "Both one-sided limits must agree, and their value must equal a defined f(a).", "Only the row (4,4,4) has a common limit equal to the function value. The others have a mismatched value, a jump, or a missing point value.", "Checking only the existence of a two-sided limit."),
      table(4, "continuity-profile-table", "Select the profile that guarantees continuity at x=b.", ["Limit from the left", "Limit from the right", "g(b)"], [["−2", "−2", "−2"], ["−2", "2", "−2"], ["−2", "−2", "0"], ["does not exist", "−2", "−2"]], 0, "A defined point value alone cannot compensate for unequal or missing limits.", "The first row has equal left and right limits of −2 and g(b)=−2. All three conditions hold; every other row violates at least one.", "Assuming one matching one-sided limit is enough for continuity."),
      choice(5, "continuity-ivt-conclusion", "reasoning", "f is continuous on [1,4], with f(1)=−2 and f(4)=5. What does the Intermediate Value Theorem guarantee?", ["Exactly one root in (1,4).", "At least one c in (1,4) with f(c)=0.", "The root is c=2.5.", "f is increasing throughout [1,4]."], "At least one c in (1,4) with f(c)=0.", "Zero lies between the endpoint values; continuity supplies existence, not uniqueness or monotonicity.", "A continuous function takes every value between −2 and 5. Since 0 lies strictly between them, some interior point has value 0. The theorem gives no root count or exact position.", "Adding uniqueness or monotonicity to an existence theorem."),
      choice(6, "continuity-ivt-conclusion", "reasoning", "g is continuous on [−2,3], with g(−2)=4 and g(3)=−1. Which conclusion necessarily follows?", ["g(0)=0.", "g has exactly one zero.", "g decreases at every point.", "g has at least one zero between −2 and 3."], "g has at least one zero between −2 and 3.", "The endpoint values have opposite signs, but the curve may rise and fall between them.", "The value 0 lies between 4 and −1. Continuity therefore forces at least one zero in the open interval, without specifying its location or whether other zeros occur.", "Inferring a complete graph shape from two endpoint values."),
    ],
    remainingGaps: ["Continuity from actual graphs, infinite and removable discontinuities, and endpoint one-sided continuity.", "Continuity of composites and selecting intervals on which IVT hypotheses hold."],
  },
  {
    lessonSlug: "g12-chain-rule",
    objectives: [
      { id: "chain-polynomial-point", description: "Differentiate a polynomial composition and evaluate the derivative at a specified input.", requiredDemands: ["procedure"] },
      { id: "chain-derivative-table", description: "Combine inner-derivative and outer-derivative entries in a composition table.", requiredDemands: ["representation"] },
      { id: "chain-linked-rate-units", description: "Calculate a rate through two linked physical quantities and report its resulting units.", requiredDemands: ["application"] },
    ],
    legacyObjectives: {},
    example: "For f(x)=(x²+2)³, f′(x)=3(x²+2)²·2x, so f′(1)=54.",
    exampleSteps: ["Set the inner function u=x²+2 and the outer function f=u³.", "Differentiate both layers: df/du=3u² and du/dx=2x.", "Multiply to obtain f′(x)=3(x²+2)²·2x.", "Evaluate at x=1: 3·3²·2=54."],
    questions: [
      choice(1, "chain-polynomial-point", "procedure", "For f(x)=(x²+1)³, calculate f′(1).", ["8", "12", "24", "48"], "24", "Multiply the outer derivative 3(x²+1)² by the inner derivative 2x.", "f′(x)=3(x²+1)²·2x. At x=1, this becomes 3·4·2=24.", "Omitting the inner derivative or evaluating the original function instead of its derivative."),
      choice(2, "chain-polynomial-point", "procedure", "Let g(x)=(2x²+3)⁴. Find g′(1).", ["500", "625", "1000", "2000"], "2000", "The inner derivative of 2x²+3 is 4x.", "The chain rule gives g′(x)=4(2x²+3)³·4x. At 1 the value is 4·5³·4=2000.", "Losing the coefficient 2 when differentiating the inner quadratic."),
      table(3, "chain-derivative-table", "Let h(x)=f(g(x)). Use the derivative records below to select an input where h′(x)=−12.", ["x", "g(x)", "g′(x)", "f′(g(x))"], [["0", "2", "3", "−4"], ["1", "3", "−2", "−5"], ["2", "1", "4", "2"], ["3", "0", "−3", "3"]], 0, "For each row, multiply the last two columns; g(x) itself is not a derivative factor.", "h′(x)=f′(g(x))g′(x). At x=0 the product is (−4)·3=−12. The other rows give 10, 8, and −9.", "Multiplying by the inner function value instead of the inner derivative."),
      table(4, "chain-derivative-table", "For H(x)=F(G(x)), which input row gives H′(x)=18?", ["x", "G(x)", "G′(x)", "F′(G(x))"], [["0", "1", "2", "3"], ["1", "4", "−3", "−6"], ["2", "3", "3", "4"], ["3", "2", "6", "−3"]], 1, "The chain-rule product uses G′(x) and F′ evaluated at G(x).", "The four derivative products are 6, 18, 12, and −18. The row x=1 is correct because (−3)(−6)=18.", "Ignoring the sign of one derivative or using the composition value as a derivative."),
      choice(5, "chain-linked-rate-units", "application", "Within this model's range, temperature is T(h)=20−0.006h °C at height h meters. A balloon follows h(t)=100t² meters, with t in minutes. Find dT/dt at t=2.", ["−0.006 °C/min", "−1.2 °C/min", "−2.4 °C/min", "400 °C/min"], "−2.4 °C/min", "Multiply dT/dh by dh/dt; at t=2 the height rate is 400 m/min.", "dT/dh=−0.006 °C/m and dh/dt=200t=400 m/min. Their product is −2.4 °C/min, with meters canceling.", "Reporting the temperature-height gradient as a time rate without the height's rate of change."),
      choice(6, "chain-linked-rate-units", "application", "A local model gives pressure P(h)=100−0.01h kPa for height h meters. A lift has h(t)=50t² meters, with t in minutes. What is dP/dt at t=3?", ["−0.01 kPa/min", "−1.5 kPa/min", "−3 kPa/min", "300 kPa/min"], "−3 kPa/min", "The lift's height rate is h′(t)=100t, not h(t).", "At t=3, dh/dt=300 m/min. Multiplying by dP/dh=−0.01 kPa/m gives dP/dt=−3 kPa/min.", "Multiplying by height instead of its derivative."),
    ],
    remainingGaps: ["Three-layer compositions, logarithmic/trigonometric outer functions, and implicit differentiation.", "Reading inner/outer derivatives from actual graphs and combining chain with product/quotient rules."],
  },
  {
    lessonSlug: "g12-definite-integrals",
    objectives: [
      { id: "integral-polynomial-evaluation", description: "Evaluate a definite polynomial integral as an antiderivative difference with signed results.", requiredDemands: ["procedure"] },
      { id: "integral-rate-interval-table", description: "Compare signed accumulated contributions from piecewise-constant rate and interval records.", requiredDemands: ["representation"] },
      { id: "integral-displacement-distance", description: "Distinguish net displacement from total distance when a velocity changes sign.", requiredDemands: ["application"] },
    ],
    legacyObjectives: { q1: "integral-polynomial-evaluation", q2: "integral-polynomial-evaluation" },
    example: "∫ from 0 to 3 of (2x−1) dx=[x²−x]₀³=6. The integral measures signed accumulation.",
    exampleSteps: ["An antiderivative of 2x−1 is F(x)=x²−x.", "Evaluate the upper endpoint: F(3)=9−3=6.", "Evaluate the lower endpoint: F(0)=0.", "Subtract upper minus lower: ∫₀³(2x−1)dx=6−0=6; this is net signed area, not automatically total geometric area."],
    questions: [
      choice(1, "integral-polynomial-evaluation", "procedure", "Calculate ∫ from 0 to 2 of (3x²−2) dx.", ["2", "4", "8", "10"], "4", "Use antiderivative x³−2x, then evaluate upper minus lower.", "[x³−2x]₀²=(8−4)−0=4. Evaluating only the integrand at x=2 would give 10, which is not the integral.", "Substituting an endpoint into the integrand instead of an antiderivative."),
      choice(2, "integral-polynomial-evaluation", "procedure", "Find ∫ from 1 to 3 of (2x−5) dx.", ["−6", "−2", "2", "6"], "−2", "Use F(x)=x²−5x and retain the lower-endpoint subtraction.", "F(3)=9−15=−6 and F(1)=1−5=−4. The integral is −6−(−4)=−2, a net negative signed area.", "Reversing the endpoint subtraction or forcing every area-related answer positive."),
      table(3, "integral-rate-interval-table", "A rate is constant within each listed time interval. Which row contributes the greatest positive accumulated change?", ["Start time (s)", "End time (s)", "Constant rate (units/s)"], [["0", "2", "3"], ["2", "3", "−5"], ["3", "6", "1"], ["6", "8", "2"]], 0, "Multiply each signed rate by its interval width; the largest magnitude rate need not give the largest positive change.", "The contributions are 2·3=6, 1·(−5)=−5, 3·1=3, and 2·2=4 units. The first interval contributes the most positive change.", "Comparing rate heights while ignoring interval widths or signs."),
      table(4, "integral-rate-interval-table", "For this piecewise-constant rate, which interval produces the largest positive integral contribution?", ["Start time (min)", "End time (min)", "Rate (liters/min)"], [["0", "1", "4"], ["1", "4", "2"], ["4", "6", "−3"], ["6", "10", "1"]], 1, "An interval's contribution is (end−start) times its rate.", "The changes are 4, 6, −6, and 4 liters. The interval from 1 to 4 minutes supplies the largest positive contribution, 6 liters.", "Treating equal positive and negative magnitudes as equal accumulated changes."),
      choice(5, "integral-displacement-distance", "application", "A particle moves at +3 m/s for 2 seconds, then −2 m/s for 3 seconds. Which pair gives its displacement and total distance over the 5 seconds?", ["Displacement 0 m; distance 12 m", "Displacement 12 m; distance 0 m", "Displacement 0 m; distance 0 m", "Displacement 6 m; distance 6 m"], "Displacement 0 m; distance 12 m", "Displacement adds signed velocity areas; distance adds their magnitudes.", "The two displacements are +3·2=6 m and −2·3=−6 m. Net displacement is 0 m, while total distance is 6+6=12 m.", "Assuming returning to the starting position means no distance was traveled."),
      choice(6, "integral-displacement-distance", "application", "An object moves at +4 m/s for 3 seconds and then −1 m/s for 2 seconds. Find its displacement and total distance.", ["Displacement 14 m; distance 10 m", "Displacement 10 m; distance 10 m", "Displacement 10 m; distance 14 m", "Displacement 12 m; distance 2 m"], "Displacement 10 m; distance 14 m", "The second segment reduces net position but still adds to distance traveled.", "The signed changes are +12 m and −2 m, so displacement is 10 m. Total distance is 12+2=14 m.", "Subtracting backward motion when computing total distance."),
    ],
    remainingGaps: ["Integrals from curved graphs, Riemann sums, reversed bounds, and integral properties across adjacent intervals.", "Total geometric area requiring root finding and splitting a sign-changing continuous integrand."],
  },
  {
    lessonSlug: "g12-sampling-distributions",
    objectives: [
      { id: "sampling-mean-center-se", description: "Compute the center and standard error of a mean from independent observations.", requiredDemands: ["procedure"] },
      { id: "sampling-design-precision-table", description: "Compare population SD and sample-size table rows against a target mean standard error.", requiredDemands: ["representation"] },
      { id: "sampling-mean-tail-probability", description: "Calculate a normal sample-mean probability using the statistic's SE rather than the individual SD.", requiredDemands: ["application"] },
    ],
    legacyObjectives: {},
    example: "Independent observations come from a population with μ=90 and σ=15. For sample size 25, the sample mean has center 90 and SE=15/√25=3.",
    exampleSteps: ["The sample mean is centered at the population mean, so E(x̄)=90.", "For independent observations, SD(x̄)=σ/√n.", "Substitute σ=15 and n=25: SE=15/5=3.", "The individual SD remains 15; averaging changes the statistic's variability. Normal shape additionally needs a normal population or an appropriate large-sample argument."],
    questions: [
      choice(1, "sampling-mean-center-se", "procedure", "Independent observations have population mean 80 and SD 12. For n=36, what are the center and SE of the sample mean?", ["Center 80; SE 2", "Center 80; SE 12", "Center 80/36; SE 2", "Center 80; SE 1/3"], "Center 80; SE 2", "Averaging preserves the center and divides the individual SD by √n.", "E(x̄)=μ=80 and SE=12/√36=12/6=2. Dividing by n instead would incorrectly give 1/3.", "Dividing the mean by sample size or confusing SD/n with SD/√n."),
      choice(2, "sampling-mean-center-se", "procedure", "A population has mean 120 and SD 24. For 64 independent observations, find the sample mean's center and SE.", ["Center 120; SE 24", "Center 120; SE 3", "Center 120/64; SE 3", "Center 120; SE 0.375"], "Center 120; SE 3", "Use √64=8 when shrinking the SD of the mean.", "The sampling distribution remains centered at 120. Its SE is 24/8=3, while 24/64=0.375 is not the correct SE formula.", "Shrinking the center along with the sampling variability."),
      table(3, "sampling-design-precision-table", "Each row samples independent observations. Which design gives the sample mean a standard error of exactly 2?", ["Population SD", "Sample size n"], [["12", "36"], ["6", "36"], ["12", "144"], ["12", "9"]], 0, "Compute σ/√n for each design rather than comparing n alone.", "The four SEs are 12/6=2, 6/6=1, 12/12=1, and 12/3=4. Only the first design has SE 2.", "Assuming sample size determines precision without accounting for population variability."),
      table(4, "sampling-design-precision-table", "For independent samples, which parameter row produces SE(x̄)=3?", ["Population SD σ", "Sample size n"], [["12", "36"], ["6", "16"], ["12", "64"], ["12", "16"]], 3, "Take the square root of each sample size before dividing its SD.", "The SEs are 2, 1.5, 1.5, and 3. The last row gives 12/√16=3.", "Using a fixed precision assumption across populations or sample sizes."),
      choice(5, "sampling-mean-tail-probability", "application", "Take n=36 independent observations from a normal population with μ=50 and σ=12. Find P(x̄>54), using Φ(2)=0.9772.", ["0.0228", "0.3333", "0.5000", "0.9772"], "0.0228", "Standardize the sample mean using SE=12/√36=2, then take the upper tail.", "The sample mean is normal with SE 2. Its z-score at 54 is (54−50)/2=2, so P(x̄>54)=1−0.9772=0.0228.", "Using the individual-observation SD 12 or the lower tail for an upper-tail question."),
      choice(6, "sampling-mean-tail-probability", "application", "A normal population has μ=100 and σ=20. For n=25 independent observations, calculate P(x̄<94). Use Φ(−1.5)=0.0668.", ["0.0668", "0.3000", "0.9332", "0.5000"], "0.0668", "The sample mean's SE is 20/5=4, making the threshold 1.5 SE below its center.", "z=(94−100)/(20/√25)=−6/4=−1.5. Therefore the lower-tail probability is the supplied Φ(−1.5)=0.0668.", "Standardizing a sample mean with the population SD instead of its SE."),
    ],
    remainingGaps: ["Central Limit Theorem conditions for skewed populations, sampling distributions of proportions and differences, and finite-population corrections.", "Simulation of repeated samples and distinguishing random sampling from independence assumptions."],
  },
];
